//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum ZincError {
    /// 6000 - Round is not active
    #[error("Round is not active")]
    RoundNotActive = 0x1770,
    /// 6001 - Round is not deployable
    #[error("Round is not deployable")]
    RoundNotDeployable = 0x1771,
    /// 6002 - Arithmetic overflow
    #[error("Arithmetic overflow")]
    Overflow = 0x1772,
    /// 6003 - Empty Deploy
    #[error("Empty Deploy")]
    EmptyDeploy = 0x1773,
    /// 6004 - Not Crank
    #[error("Not Crank")]
    NotCrank = 0x1774,
    /// 6005 - Round Mismatch
    #[error("Round Mismatch")]
    RoundMismatch = 0x1775,
    /// 6006 - Round Not Closed
    #[error("Round Not Closed")]
    RoundNotClosed = 0x1776,
    /// 6007 - Numerical Overflow
    #[error("Numerical Overflow")]
    NumericalOverflow = 0x1777,
    /// 6008 - Wrong Treasury
    #[error("Wrong Treasury")]
    WrongTreasury = 0x1778,
    /// 6009 - Wrong config
    #[error("Wrong config")]
    WrongConfig = 0x1779,
    /// 6010 - Wrong board
    #[error("Wrong board")]
    WrongBoard = 0x177A,
    /// 6011 - Not Admin
    #[error("Not Admin")]
    NotAdmin = 0x177B,
    /// 6012 - Already Claimed
    #[error("Already Claimed")]
    AlreadyClaimed = 0x177C,
    /// 6013 - Round is not preparing
    #[error("Round is not preparing")]
    RoundNotPreparing = 0x177D,
    /// 6014 - Round is not ready
    #[error("Round is not ready")]
    RoundNotReady = 0x177E,
    /// 6015 - Round is not pending settlement
    #[error("Round is not pending settlement")]
    RoundNotPendingSettlement = 0x177F,
    /// 6016 - Round is not pending batch settlement
    #[error("Round is not pending batch settlement")]
    RoundNotPendingBatchSettlement = 0x1780,
    /// 6017 - No settlement callback is pending
    #[error("No settlement callback is pending")]
    SettlementCallbackNotPending = 0x1781,
    /// 6018 - Settlement callbacks are still pending
    #[error("Settlement callbacks are still pending")]
    SettlementCallbacksPending = 0x1782,
    /// 6019 - Round cleanup delay has not elapsed
    #[error("Round cleanup delay has not elapsed")]
    RoundCleanupDelayNotElapsed = 0x1783,
    /// 6020 - Round is not pending no-winner redirect
    #[error("Round is not pending no-winner redirect")]
    RoundNotPendingNoWinnerRedirect = 0x1784,
    /// 6021 - Round is not settled
    #[error("Round is not settled")]
    RoundNotSettled = 0x1785,
    /// 6022 - Round still has winners
    #[error("Round still has winners")]
    RoundHasWinners = 0x1786,
    /// 6023 - Current round is still active
    #[error("Current round is still active")]
    CurrentRoundStillActive = 0x1787,
    /// 6024 - A round is still waiting for its first deploy
    #[error("A round is still waiting for its first deploy")]
    CurrentRoundStillWaitingForFirstDeploy = 0x1788,
    /// 6025 - Missing current round account
    #[error("Missing current round account")]
    MissingCurrentRound = 0x1789,
    /// 6026 - Missing current stockpile account
    #[error("Missing current stockpile account")]
    MissingCurrentStockpile = 0x178A,
    /// 6027 - Invalid round id
    #[error("Invalid round id")]
    InvalidRoundId = 0x178B,
    /// 6028 - Round secret is missing
    #[error("Round secret is missing")]
    RoundSecretMissing = 0x178C,
    /// 6029 - Round secret is already stored
    #[error("Round secret is already stored")]
    RoundSecretAlreadyStored = 0x178D,
    /// 6030 - Round is already settled
    #[error("Round is already settled")]
    RoundAlreadySettled = 0x178E,
    /// 6031 - Round has already expired
    #[error("Round has already expired")]
    RoundExpired = 0x178F,
    /// 6032 - Round is still open
    #[error("Round is still open")]
    RoundStillOpen = 0x1790,
    /// 6033 - Round timing is not initialized
    #[error("Round timing is not initialized")]
    RoundTimingNotInitialized = 0x1791,
    /// 6034 - Round duration must be greater than zero
    #[error("Round duration must be greater than zero")]
    InvalidRoundDuration = 0x1792,
    /// 6035 - Round start delay must be greater than zero
    #[error("Round start delay must be greater than zero")]
    InvalidRoundStartDelay = 0x1793,
    /// 6036 - Next round selection is waiting for the previous winning tile reveal
    #[error("Next round selection is waiting for the previous winning tile reveal")]
    RoundTransitionRevealPending = 0x1794,
    /// 6037 - Next round reveal delay has not elapsed
    #[error("Next round reveal delay has not elapsed")]
    RoundStartDelayNotElapsed = 0x1795,
    /// 6038 - Round transition does not reference this round
    #[error("Round transition does not reference this round")]
    TransitionRoundMismatch = 0x1796,
    /// 6039 - Not MXE authority
    #[error("Not MXE authority")]
    NotMxeAuthority = 0x1797,
    /// 6040 - MXE authority is not set
    #[error("MXE authority is not set")]
    MxeAuthorityNotSet = 0x1798,
    /// 6041 - The computation was aborted
    #[error("The computation was aborted")]
    AbortedComputation = 0x1799,
    /// 6042 - Invalid batch account count
    #[error("Invalid batch account count")]
    InvalidBatchAccountCount = 0x179A,
    /// 6043 - Too many settlement accounts were provided
    #[error("Too many settlement accounts were provided")]
    SettlementBatchTooLarge = 0x179B,
    /// 6044 - Miner account mismatch
    #[error("Miner account mismatch")]
    MinerAccountMismatch = 0x179C,
    /// 6045 - Player miner mismatch
    #[error("Player miner mismatch")]
    PlayerMinerMismatch = 0x179D,
    /// 6046 - Player profile mismatch
    #[error("Player profile mismatch")]
    PlayerProfileMismatch = 0x179E,
    /// 6047 - Miner is already settled
    #[error("Miner is already settled")]
    MinerAlreadySettled = 0x179F,
    /// 6048 - Winning square is not initialized
    #[error("Winning square is not initialized")]
    WinningSquareMissing = 0x17A0,
    /// 6049 - Event serialization failed
    #[error("Event serialization failed")]
    EventSerializationFailed = 0x17A1,
    /// 6050 - Deploy amount is below the minimum
    #[error("Deploy amount is below the minimum")]
    DeployBelowMinimum = 0x17A2,
    /// 6051 - Round has reached the maximum number of players
    #[error("Round has reached the maximum number of players")]
    RoundFull = 0x17A3,
    /// 6052 - Missing Start Slot
    #[error("Missing Start Slot")]
    MissingStartSlot = 0x17A4,
    /// 6053 - ZINC mint is already initialized
    #[error("ZINC mint is already initialized")]
    ZincMintAlreadyInitialized = 0x17A5,
    /// 6054 - ZINC mint is not initialized
    #[error("ZINC mint is not initialized")]
    ZincMintNotInitialized = 0x17A6,
    /// 6055 - Wrong ZINC mint
    #[error("Wrong ZINC mint")]
    WrongZincMint = 0x17A7,
    /// 6056 - Invalid ZINC mint metadata
    #[error("Invalid ZINC mint metadata")]
    InvalidZincMintMetadata = 0x17A8,
    /// 6057 - Wrong ZINC mint metadata
    #[error("Wrong ZINC mint metadata")]
    WrongZincMintMetadata = 0x17A9,
    /// 6058 - Wrong curve admin token account
    #[error("Wrong curve admin token account")]
    WrongCurveAdminTokenAccount = 0x17AA,
    /// 6059 - Wrong Bonanza token account
    #[error("Wrong Bonanza token account")]
    WrongBonanzaTokenAccount = 0x17AB,
    /// 6060 - Wrong round ZINC payout token account
    #[error("Wrong round ZINC payout token account")]
    WrongRoundZincPayoutTokenAccount = 0x17AC,
    /// 6061 - Wrong player ZINC token account
    #[error("Wrong player ZINC token account")]
    WrongPlayerZincTokenAccount = 0x17AD,
    /// 6062 - Invalid stockpile id
    #[error("Invalid stockpile id")]
    InvalidStockpileId = 0x17AE,
    /// 6063 - Stockpile timing is not initialized
    #[error("Stockpile timing is not initialized")]
    StockpileTimingNotInitialized = 0x17AF,
    /// 6064 - Stockpile is not open
    #[error("Stockpile is not open")]
    StockpileNotOpen = 0x17B0,
    /// 6065 - Stockpile is not preparing
    #[error("Stockpile is not preparing")]
    StockpileNotPreparing = 0x17B1,
    /// 6066 - Stockpile is not pending reveal
    #[error("Stockpile is not pending reveal")]
    StockpileNotPendingReveal = 0x17B2,
    /// 6067 - Stockpile is not pending payout
    #[error("Stockpile is not pending payout")]
    StockpileNotPendingPayout = 0x17B3,
    /// 6068 - Stockpile is not pending extra payout
    #[error("Stockpile is not pending extra payout")]
    StockpileNotPendingExtraPayout = 0x17B4,
    /// 6069 - Stockpile is not paid
    #[error("Stockpile is not paid")]
    StockpileNotPaid = 0x17B5,
    /// 6070 - Stockpile mismatch
    #[error("Stockpile mismatch")]
    StockpileMismatch = 0x17B6,
    /// 6071 - Wrong stockpile secret
    #[error("Wrong stockpile secret")]
    WrongStockpileSecret = 0x17B7,
    /// 6072 - Stockpile is still referenced by the board
    #[error("Stockpile is still referenced by the board")]
    BoardStockpileStillReferenced = 0x17B8,
    /// 6073 - Stockpile secret is missing
    #[error("Stockpile secret is missing")]
    StockpileSecretMissing = 0x17B9,
    /// 6074 - Stockpile secret is already stored
    #[error("Stockpile secret is already stored")]
    StockpileSecretAlreadyStored = 0x17BA,
    /// 6075 - Stockpile is still open
    #[error("Stockpile is still open")]
    StockpileStillOpen = 0x17BB,
    /// 6076 - Previous stockpile is still unresolved
    #[error("Previous stockpile is still unresolved")]
    StockpileStillUnresolved = 0x17BC,
    /// 6077 - Stockpile has no entries
    #[error("Stockpile has no entries")]
    StockpileHasNoEntries = 0x17BD,
    /// 6078 - Stockpile still has entries
    #[error("Stockpile still has entries")]
    StockpileHasEntries = 0x17BE,
    /// 6079 - Stockpile account has no reserved entry capacity
    #[error("Stockpile account has no reserved entry capacity")]
    StockpileFull = 0x17BF,
    /// 6080 - Player already joined this stockpile
    #[error("Player already joined this stockpile")]
    StockpileAlreadyJoined = 0x17C0,
    /// 6081 - Insufficient stockpile bricks
    #[error("Insufficient stockpile bricks")]
    InsufficientStockpileBricks = 0x17C1,
    /// 6082 - Insufficient stockpile ZINC
    #[error("Insufficient stockpile ZINC")]
    InsufficientStockpileZinc = 0x17C2,
    /// 6083 - Stockpile winner is missing
    #[error("Stockpile winner is missing")]
    StockpileWinnerMissing = 0x17C3,
    /// 6084 - Invalid stockpile winner configuration
    #[error("Invalid stockpile winner configuration")]
    InvalidStockpileWinnerConfig = 0x17C4,
    /// 6085 - Invalid stockpile winner rank
    #[error("Invalid stockpile winner rank")]
    InvalidStockpileWinnerRank = 0x17C5,
    /// 6086 - Stockpile winner rank already paid
    #[error("Stockpile winner rank already paid")]
    StockpileWinnerRankAlreadyPaid = 0x17C6,
    /// 6087 - Stockpile winner account is missing
    #[error("Stockpile winner account is missing")]
    StockpileWinnersMissing = 0x17C7,
    /// 6088 - Stockpile winners are not fully paid
    #[error("Stockpile winners are not fully paid")]
    StockpileWinnersNotFullyPaid = 0x17C8,
    /// 6089 - Wrong stockpile token account
    #[error("Wrong stockpile token account")]
    WrongStockpileTokenAccount = 0x17C9,
    /// 6090 - Wrong stockpile SOL vault
    #[error("Wrong stockpile SOL vault")]
    WrongStockpileSolVault = 0x17CA,
    /// 6091 - Wrong buyback SOL vault
    #[error("Wrong buyback SOL vault")]
    WrongBuybackSolVault = 0x17CB,
    /// 6092 - Wrong wrapped SOL mint
    #[error("Wrong wrapped SOL mint")]
    WrongWrappedSolMint = 0x17CC,
    /// 6093 - Insufficient buyback SOL
    #[error("Insufficient buyback SOL")]
    InsufficientBuybackSol = 0x17CD,
    /// 6094 - Insufficient buyback WSOL
    #[error("Insufficient buyback WSOL")]
    InsufficientBuybackWsol = 0x17CE,
    /// 6095 - Wrong Meteora DAMM v2 program
    #[error("Wrong Meteora DAMM v2 program")]
    WrongMeteoraProgram = 0x17CF,
    /// 6096 - Wrong Meteora pool authority
    #[error("Wrong Meteora pool authority")]
    WrongMeteoraPoolAuthority = 0x17D0,
    /// 6097 - Wrong Meteora pool
    #[error("Wrong Meteora pool")]
    WrongMeteoraPool = 0x17D1,
    /// 6098 - Wrong Meteora pool vault
    #[error("Wrong Meteora pool vault")]
    WrongMeteoraVault = 0x17D2,
    /// 6099 - Wrong Meteora position account
    #[error("Wrong Meteora position account")]
    WrongMeteoraPosition = 0x17D3,
    /// 6100 - Wrong Meteora position NFT account
    #[error("Wrong Meteora position NFT account")]
    WrongMeteoraPositionNftAccount = 0x17D4,
    /// 6101 - Wrong Meteora event authority
    #[error("Wrong Meteora event authority")]
    WrongMeteoraEventAuthority = 0x17D5,
    /// 6102 - Meteora instruction data serialization failed
    #[error("Meteora instruction data serialization failed")]
    MeteoraInstructionSerializationFailed = 0x17D6,
    /// 6103 - LP seed ZINC exceeds the configured supply cap
    #[error("LP seed ZINC exceeds the configured supply cap")]
    BuybackPoolSeedExceedsSupplyCap = 0x17D7,
    /// 6104 - Meteora pool did not consume the exact requested LP seed amounts
    #[error("Meteora pool did not consume the exact requested LP seed amounts")]
    BuybackPoolSeedContributionMismatch = 0x17D8,
    /// 6105 - Buyback swap did not spend the exact requested WSOL amount
    #[error("Buyback swap did not spend the exact requested WSOL amount")]
    BuybackInputMismatch = 0x17D9,
    /// 6106 - Buyback output was below the requested minimum
    #[error("Buyback output was below the requested minimum")]
    BuybackSlippageExceeded = 0x17DA,
    /// 6107 - Treasury lamports changed during buyback swap
    #[error("Treasury lamports changed during buyback swap")]
    BuybackTreasuryLamportsChanged = 0x17DB,
    /// 6108 - ZINC mint supply changed during buyback swap
    #[error("ZINC mint supply changed during buyback swap")]
    BuybackMintSupplyChanged = 0x17DC,
    /// 6109 - Wrong staking token account
    #[error("Wrong staking token account")]
    WrongStakingTokenAccount = 0x17DD,
    /// 6110 - Wrong staking reward token account
    #[error("Wrong staking reward token account")]
    WrongStakingRewardTokenAccount = 0x17DE,
    /// 6111 - Wrong round ZINC reward token account
    #[error("Wrong round ZINC reward token account")]
    WrongRoundZincRewardTokenAccount = 0x17DF,
    /// 6112 - Wrong stake position
    #[error("Wrong stake position")]
    WrongStakePosition = 0x17E0,
    /// 6113 - Amount must be greater than zero
    #[error("Amount must be greater than zero")]
    AmountMustBeGreaterThanZero = 0x17E1,
    /// 6114 - No staking rewards are claimable
    #[error("No staking rewards are claimable")]
    NoStakingRewards = 0x17E2,
    /// 6115 - No round ZINC rewards are claimable
    #[error("No round ZINC rewards are claimable")]
    NoRoundZincRewards = 0x17E3,
    /// 6116 - No round SOL rewards are claimable
    #[error("No round SOL rewards are claimable")]
    NoRoundSolRewards = 0x17E4,
    /// 6117 - Insufficient staked balance
    #[error("Insufficient staked balance")]
    InsufficientStakedBalance = 0x17E5,
    /// 6118 - Unsupported account version
    #[error("Unsupported account version")]
    UnsupportedAccountVersion = 0x17E6,
    /// 6119 - Settlement capability mismatch
    #[error("Settlement capability mismatch")]
    SettlementCapabilityMismatch = 0x17E7,
    /// 6120 - Wrong miner ZK mask
    #[error("Wrong miner ZK mask")]
    WrongMinerZkMask = 0x17E8,
    /// 6121 - Stockpile entry is below the minimum
    #[error("Stockpile entry is below the minimum")]
    StockpileEntryBelowMinimum = 0x17E9,
    /// 6122 - Stockpile has reached the maximum number of extras
    #[error("Stockpile has reached the maximum number of extras")]
    StockpileExtrasFull = 0x17EA,
    /// 6123 - Stockpile extra amount must be greater than zero
    #[error("Stockpile extra amount must be greater than zero")]
    InvalidStockpileExtraAmount = 0x17EB,
    /// 6124 - Unsupported stockpile extra mint
    #[error("Unsupported stockpile extra mint")]
    UnsupportedStockpileExtraMint = 0x17EC,
    /// 6125 - Stockpile extras already rolled to a newer stockpile
    #[error("Stockpile extras already rolled to a newer stockpile")]
    StockpileExtrasAlreadyRolled = 0x17ED,
    /// 6126 - Stockpile extra is missing
    #[error("Stockpile extra is missing")]
    StockpileExtraMissing = 0x17EE,
    /// 6127 - Stockpile extra is already paid
    #[error("Stockpile extra is already paid")]
    StockpileExtraAlreadyPaid = 0x17EF,
    /// 6128 - Wrong stockpile extra token account
    #[error("Wrong stockpile extra token account")]
    WrongStockpileExtraTokenAccount = 0x17F0,
    /// 6129 - Wrong winner stockpile extra token account
    #[error("Wrong winner stockpile extra token account")]
    WrongWinnerStockpileExtraTokenAccount = 0x17F1,
    /// 6130 - Treasury does not have enough lamports to reimburse round creation
    #[error("Treasury does not have enough lamports to reimburse round creation")]
    InsufficientTreasuryLamports = 0x17F2,
    /// 6131 - Wrong affiliate account
    #[error("Wrong affiliate account")]
    WrongAffiliate = 0x17F3,
    /// 6132 - Affiliate cannot be the player
    #[error("Affiliate cannot be the player")]
    AffiliateSelfReferral = 0x17F4,
    /// 6133 - Affiliate binding is immutable after the first deploy
    #[error("Affiliate binding is immutable after the first deploy")]
    AffiliateBindingImmutable = 0x17F5,
    /// 6134 - Deploy fee schedule is invalid
    #[error("Deploy fee schedule is invalid")]
    InvalidDeployFeeBps = 0x17F6,
    /// 6135 - Curve ZINC share schedule is invalid
    #[error("Curve ZINC share schedule is invalid")]
    InvalidCurveZincShareBps = 0x17F7,
    /// 6136 - Curve parameter is invalid
    #[error("Curve parameter is invalid")]
    InvalidCurveParameter = 0x17F8,
    /// 6137 - Missing affiliate accounts
    #[error("Missing affiliate accounts")]
    MissingAffiliateAccounts = 0x17F9,
    /// 6138 - No affiliate balance is claimable
    #[error("No affiliate balance is claimable")]
    NoAffiliateBalance = 0x17FA,
    /// 6139 - Affiliate withdrawals are disabled
    #[error("Affiliate withdrawals are disabled")]
    AffiliateWithdrawalsDisabled = 0x17FB,
    /// 6140 - Affiliate profile does not have enough lamports for the claim
    #[error("Affiliate profile does not have enough lamports for the claim")]
    InsufficientAffiliateProfileLamports = 0x17FC,
    /// 6141 - Player profile does not have enough lamports for the claim
    #[error("Player profile does not have enough lamports for the claim")]
    InsufficientPlayerProfileLamports = 0x17FD,
    /// 6142 - Auto-miner session is paused
    #[error("Auto-miner session is paused")]
    AutoMinerSessionPaused = 0x17FE,
    /// 6143 - Auto-miner session has expired
    #[error("Auto-miner session has expired")]
    AutoMinerSessionExpired = 0x17FF,
    /// 6144 - Auto-miner session budget is insufficient
    #[error("Auto-miner session budget is insufficient")]
    AutoMinerInsufficientBudget = 0x1800,
    /// 6145 - Auto-miner authority lamports are insufficient
    #[error("Auto-miner authority lamports are insufficient")]
    AutoMinerAuthorityInsufficientLamports = 0x1801,
    /// 6146 - Auto-miner encrypted tile pattern is invalid
    #[error("Auto-miner encrypted tile pattern is invalid")]
    InvalidAutoMinerEncryptedPattern = 0x1802,
    /// 6147 - Auto-miner SOL reward reload is disabled
    #[error("Auto-miner SOL reward reload is disabled")]
    AutoMinerAutoReloadDisabled = 0x1803,
    /// 6148 - Auto-miner session mismatch
    #[error("Auto-miner session mismatch")]
    AutoMinerSessionMismatch = 0x1804,
    /// 6149 - Stockpile duration must be greater than zero
    #[error("Stockpile duration must be greater than zero")]
    InvalidStockpileDuration = 0x1805,
    /// 6150 - Blockhash reveal delay must be greater than zero
    #[error("Blockhash reveal delay must be greater than zero")]
    InvalidBlockhashRevealDelay = 0x1806,
    /// 6151 - Round randomness mode does not allow this reveal path
    #[error("Round randomness mode does not allow this reveal path")]
    InvalidRoundRandomnessMode = 0x1807,
    /// 6152 - Blockhash reveal sample slot is not ready
    #[error("Blockhash reveal sample slot is not ready")]
    BlockhashRevealNotReady = 0x1808,
    /// 6153 - Blockhash reveal sample slot is missing
    #[error("Blockhash reveal sample slot is missing")]
    BlockhashSampleMissing = 0x1809,
    /// 6154 - Entropy blockhash is missing
    #[error("Entropy blockhash is missing")]
    EntropyBlockhashMissing = 0x180A,
    /// 6155 - Config must be closed with close_config
    #[error("Config must be closed with close_config")]
    ClosePdaCannotCloseConfig = 0x180B,
    /// 6156 - Wrong treasury token account
    #[error("Wrong treasury token account")]
    WrongTreasuryTokenAccount = 0x180C,
    /// 6157 - Not Admin or Crank
    #[error("Not Admin or Crank")]
    NotAdminOrCrank = 0x180D,
    /// 6158 - Round cleanup is incomplete
    #[error("Round cleanup is incomplete")]
    RoundCleanupIncomplete = 0x180E,
    /// 6159 - Round cleanup is already complete
    #[error("Round cleanup is already complete")]
    RoundCleanupComplete = 0x180F,
    /// 6160 - Round is still referenced by the board
    #[error("Round is still referenced by the board")]
    BoardRoundStillReferenced = 0x1810,
    /// 6161 - Miner claim state is not terminal
    #[error("Miner claim state is not terminal")]
    MinerClaimNotTerminal = 0x1811,
    /// 6162 - Round still has outstanding winner claims
    #[error("Round still has outstanding winner claims")]
    OutstandingWinnerClaims = 0x1812,
    /// 6163 - Wrong round secret
    #[error("Wrong round secret")]
    WrongRoundSecret = 0x1813,
    /// 6164 - Wildcat winner selection is not ready
    #[error("Wildcat winner selection is not ready")]
    WildcatSelectionNotReady = 0x1814,
    /// 6165 - Wildcat winner selection is already complete
    #[error("Wildcat winner selection is already complete")]
    WildcatSelectionComplete = 0x1815,
    /// 6166 - Wildcat winner is missing
    #[error("Wildcat winner is missing")]
    WildcatWinnerMissing = 0x1816,
    /// 6167 - Wildcat ZINC claim is not ready
    #[error("Wildcat ZINC claim is not ready")]
    WildcatClaimNotReady = 0x1817,
    /// 6168 - Wildcat ZINC has already been claimed
    #[error("Wildcat ZINC has already been claimed")]
    WildcatAlreadyClaimed = 0x1818,
    /// 6169 - Wildcat ZINC claim is incomplete
    #[error("Wildcat ZINC claim is incomplete")]
    WildcatClaimIncomplete = 0x1819,
    /// 6170 - Wildcat entry capacity is exhausted
    #[error("Wildcat entry capacity is exhausted")]
    WildcatEntryCapacityExceeded = 0x181A,
    /// 6171 - Wildcat winner ZINC share exceeds one million ppm
    #[error("Wildcat winner ZINC share exceeds one million ppm")]
    InvalidWildcatWinnerZincSharePpm = 0x181B,
    /// 6172 - Board cannot be closed with close_pda
    #[error("Board cannot be closed with close_pda")]
    ClosePdaCannotCloseBoard = 0x181C,
    /// 6173 - Treasury cannot be closed with close_pda
    #[error("Treasury cannot be closed with close_pda")]
    ClosePdaCannotCloseTreasury = 0x181D,
    /// 6174 - Ready round is not the next sequential round
    #[error("Ready round is not the next sequential round")]
    RoundNotNextSequential = 0x181E,
    /// 6175 - Groth16 proof A point could not be deserialized
    #[error("Groth16 proof A point could not be deserialized")]
    Groth16DeserializeProofA = 0x181F,
    /// 6176 - Groth16 proof A point could not be serialized
    #[error("Groth16 proof A point could not be serialized")]
    Groth16SerializeProofA = 0x1820,
    /// 6177 - Groth16 proof A bytes could not be extracted
    #[error("Groth16 proof A bytes could not be extracted")]
    Groth16ExtractProofA = 0x1821,
    /// 6178 - Groth16 verifier could not be created
    #[error("Groth16 verifier could not be created")]
    Groth16CreateFailed = 0x1822,
    /// 6179 - Groth16 proof verification failed
    #[error("Groth16 proof verification failed")]
    Groth16VerifyFailed = 0x1823,
    /// 6180 - Groth16 public inputs do not match the expected context
    #[error("Groth16 public inputs do not match the expected context")]
    Groth16PublicInputMismatch = 0x1824,
    /// 6181 - Missing ZK mask attestation
    #[error("Missing ZK mask attestation")]
    MissingZkMaskAttestation = 0x1825,
}

impl From<ZincError> for solana_program_error::ProgramError {
    fn from(e: ZincError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}
