//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::ComputationSignature;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// A computation definition for execution in a MXE.
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ComputationDefinitionMeta {
    pub circuit_len: u32,
    pub signature: ComputationSignature,
}
