//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// location as [ISO 3166-1 alpha-2](https://www.iso.org/iso-3166-country-codes.html) country code
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct NodeMetadata {
    pub ip: [u8; 4],
    pub peer_id: [u8; 32],
    pub location: u8,
}
