//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

/// One inclusive-exclusive weighted ticket range for a Wildcat-eligible round winner.
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct RoundWildcatEntryRange {
    /// Settled winner miner PDA that owns this Wildcat range.
    pub miner: Address,
    /// Player wallet that owns the miner.
    pub player: Address,
    /// Net deploy amount used to keep the bounded Wildcat candidate set deterministic.
    pub deploy_amount: u64,
    /// First weighted ticket index owned by the winner, inclusive.
    pub start: u64,
    /// First weighted ticket index after the winner's range, exclusive.
    pub end: u64,
}
