//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Metaplex token metadata fields managed by the protocol admin.
#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ZincMintMetadataArgs {
    /// Display name persisted in the Metaplex metadata account.
    pub name: String,
    /// Token symbol persisted in the Metaplex metadata account.
    pub symbol: String,
    /// Off-chain metadata JSON URI persisted in the Metaplex metadata account.
    pub uri: String,
}
