//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct PlayerProfile {
    pub discriminator: [u8; 8],
    /// Wallet this lifetime profile belongs to.
    pub player: Address,
    /// True once this PDA has been initialized for a specific player.
    pub initialized: bool,
    /// Total number of rounds this player has entered.
    pub rounds_count: u64,
    /// Previous qualifying round in the player's streak history.
    pub last_streak_round: Option<u64>,
    /// Most recent qualifying round that currently anchors the active streak.
    pub current_streak_round: Option<u64>,
    /// Number of consecutive qualifying rounds in the active streak.
    pub current_streak_count: u64,
    /// Lifetime gross lamports committed before deploy-time fees.
    pub gross_deployed_lamports: u64,
    /// Lifetime net lamports that entered rounds after deploy-time fees.
    pub net_deployed_lamports: u64,
    /// Immutable affiliate wallet bound on the player's first referred deploy, if any.
    pub affiliate: Option<Address>,
    /// Claimable affiliate SOL currently held on this player-profile PDA.
    pub pending_affiliate_pay_lamports: u64,
    /// Lifetime affiliate SOL accrued for this wallet.
    pub total_affiliate_pay_lamports: u64,
    /// Lifetime stockpile bricks earned from streak and hidden-bonus accrual, in `x10k` units.
    pub lifetime_stockpile_bricks_earned_x10k: u64,
    /// Lifetime stockpile bricks earned from deploy streaks, in `x10k` units.
    pub lifetime_streak_stockpile_bricks_earned_x10k: u64,
    /// Lifetime stockpile bricks earned from hidden settlement bonuses, in `x10k` units.
    pub lifetime_hidden_bonus_stockpile_bricks_earned_x10k: u64,
    /// Spendable stockpile bricks in `x10k` units.
    pub available_stockpile_bricks_x10k: u64,
    /// Most recent stockpile cycle this player joined, if any.
    pub last_joined_stockpile_id: Option<u64>,
    /// PDA bump seed.
    pub bump: u8,
}

pub const PLAYER_PROFILE_DISCRIMINATOR: [u8; 8] = [82, 226, 99, 87, 164, 130, 181, 80];

impl PlayerProfile {
    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for PlayerProfile {
    type Error = std::io::Error;

    fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_player_profile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::DecodedAccount<PlayerProfile>, std::io::Error> {
    let accounts = fetch_all_player_profile(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_player_profile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::DecodedAccount<PlayerProfile>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<PlayerProfile>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::other(format!(
            "Account not found: {address}"
        )))?;
        let data = PlayerProfile::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_player_profile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::MaybeAccount<PlayerProfile>, std::io::Error> {
    let accounts = fetch_all_maybe_player_profile(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_player_profile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::MaybeAccount<PlayerProfile>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<PlayerProfile>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = PlayerProfile::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountDeserialize for PlayerProfile {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountSerialize for PlayerProfile {}

#[cfg(feature = "anchor")]
impl anchor_lang::Owner for PlayerProfile {
    fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(crate::ZINC_ID.to_bytes())
    }
}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::IdlBuild for PlayerProfile {}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::Discriminator for PlayerProfile {
    const DISCRIMINATOR: &[u8] = &[0; 8];
}
