//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::StockpileEntry;
use crate::codama_rust::types::StockpileStatus;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct Stockpile {
    pub discriminator: [u8; 8],
    /// Lifecycle state for this stockpile cycle.
    pub status: StockpileStatus,
    /// Sequential stockpile identifier.
    pub id: u64,
    /// True once this PDA has been initialized for a concrete stockpile cycle.
    pub initialized: bool,
    /// Slot duration captured when the cycle was created for historical metadata.
    pub duration_slots: u64,
    /// Slot when the cycle opened for joins.
    pub open_slot: Option<u64>,
    /// Initial close slot captured at open; live close checks use current config duration.
    pub close_after_slot: Option<u64>,
    /// Number of joined entries in this cycle.
    pub entrant_count: u64,
    /// Total committed stockpile bricks in `x10k` units.
    pub total_committed_bricks_x10k: u64,
    /// Revealed random value, if any.
    pub rand: Option<u64>,
    /// Winning ticket index in `x10k` units, if any.
    pub winning_ticket_x10k: Option<u64>,
    /// Winner selected for payout, if any.
    pub winner: Option<Address>,
    /// Snapshotted SOL payout reserved for this cycle.
    pub sol_payout_amount: u64,
    /// Snapshotted ZINC payout reserved for this cycle.
    pub zinc_payout_amount: u64,
    /// PDA bump seed.
    pub bump: u8,
    /// Number of accepted joins including same-player top-ups.
    pub accepted_join_count: u64,
    /// All joined entries for this cycle.
    pub entries: Vec<StockpileEntry>,
}

pub const STOCKPILE_DISCRIMINATOR: [u8; 8] = [218, 41, 100, 84, 84, 16, 69, 252];

impl Stockpile {
    #[inline(always)]
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        let mut data = data;
        Self::deserialize(&mut data)
    }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for Stockpile {
    type Error = std::io::Error;

    fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
        let mut data: &[u8] = &(*account_info.data).borrow();
        Self::deserialize(&mut data)
    }
}

#[cfg(feature = "fetch")]
pub fn fetch_stockpile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::DecodedAccount<Stockpile>, std::io::Error> {
    let accounts = fetch_all_stockpile(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_stockpile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::DecodedAccount<Stockpile>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::DecodedAccount<Stockpile>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        let account = accounts[i].as_ref().ok_or(std::io::Error::other(format!(
            "Account not found: {address}"
        )))?;
        let data = Stockpile::from_bytes(&account.data)?;
        decoded_accounts.push(crate::shared::DecodedAccount {
            address,
            account: account.clone(),
            data,
        });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_stockpile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    address: &solana_address::Address,
) -> Result<crate::shared::MaybeAccount<Stockpile>, std::io::Error> {
    let accounts = fetch_all_maybe_stockpile(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_stockpile(
    rpc: &solana_rpc_client::rpc_client::RpcClient,
    addresses: &[solana_address::Address],
) -> Result<Vec<crate::shared::MaybeAccount<Stockpile>>, std::io::Error> {
    let accounts = rpc
        .get_multiple_accounts(addresses)
        .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::shared::MaybeAccount<Stockpile>> = Vec::new();
    for i in 0..addresses.len() {
        let address = addresses[i];
        if let Some(account) = accounts[i].as_ref() {
            let data = Stockpile::from_bytes(&account.data)?;
            decoded_accounts.push(crate::shared::MaybeAccount::Exists(
                crate::shared::DecodedAccount {
                    address,
                    account: account.clone(),
                    data,
                },
            ));
        } else {
            decoded_accounts.push(crate::shared::MaybeAccount::NotFound(address));
        }
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountDeserialize for Stockpile {
    fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
    }
}

#[cfg(feature = "anchor")]
impl anchor_lang::AccountSerialize for Stockpile {}

#[cfg(feature = "anchor")]
impl anchor_lang::Owner for Stockpile {
    fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(crate::ZINC_ID.to_bytes())
    }
}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::IdlBuild for Stockpile {}

#[cfg(feature = "anchor-idl-build")]
impl anchor_lang::Discriminator for Stockpile {
    const DISCRIMINATOR: &[u8] = &[0; 8];
}
