//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CLAIM_ROUND_SOL_DISCRIMINATOR: [u8; 8] = [245, 106, 176, 41, 4, 167, 225, 92];

/// Accounts.
#[derive(Debug)]
pub struct ClaimRoundSol {
    /// Signer that submits the claim transaction.
    pub signer: solana_address::Address,
    /// Settled round whose SOL payout is being claimed.
    pub round: solana_address::Address,
    /// Per-player round position that tracks winning stake and split claim status.
    pub miner: solana_address::Address,

    pub player: solana_address::Address,
}

impl ClaimRoundSol {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.signer,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.round, false));
        accounts.push(solana_instruction::AccountMeta::new(self.miner, false));
        accounts.push(solana_instruction::AccountMeta::new(self.player, false));
        accounts.extend_from_slice(remaining_accounts);
        let data = ClaimRoundSolInstructionData::new().try_to_vec().unwrap();

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ClaimRoundSolInstructionData {
    discriminator: [u8; 8],
}

impl ClaimRoundSolInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [245, 106, 176, 41, 4, 167, 225, 92],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for ClaimRoundSolInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `ClaimRoundSol`.
///
/// ### Accounts:
///
///   0. `[signer]` signer
///   1. `[writable]` round
///   2. `[writable]` miner
///   3. `[writable]` player
#[derive(Clone, Debug, Default)]
pub struct ClaimRoundSolBuilder {
    signer: Option<solana_address::Address>,
    round: Option<solana_address::Address>,
    miner: Option<solana_address::Address>,
    player: Option<solana_address::Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClaimRoundSolBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Signer that submits the claim transaction.
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    /// Settled round whose SOL payout is being claimed.
    #[inline(always)]
    pub fn round(&mut self, round: solana_address::Address) -> &mut Self {
        self.round = Some(round);
        self
    }
    /// Per-player round position that tracks winning stake and split claim status.
    #[inline(always)]
    pub fn miner(&mut self, miner: solana_address::Address) -> &mut Self {
        self.miner = Some(miner);
        self
    }
    #[inline(always)]
    pub fn player(&mut self, player: solana_address::Address) -> &mut Self {
        self.player = Some(player);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ClaimRoundSol {
            signer: self.signer.expect("signer is not set"),
            round: self.round.expect("round is not set"),
            miner: self.miner.expect("miner is not set"),
            player: self.player.expect("player is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `claim_round_sol` CPI accounts.
pub struct ClaimRoundSolCpiAccounts<'a, 'b> {
    /// Signer that submits the claim transaction.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Settled round whose SOL payout is being claimed.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Per-player round position that tracks winning stake and split claim status.
    pub miner: &'b solana_account_info::AccountInfo<'a>,

    pub player: &'b solana_account_info::AccountInfo<'a>,
}

/// `claim_round_sol` CPI instruction.
pub struct ClaimRoundSolCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Signer that submits the claim transaction.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Settled round whose SOL payout is being claimed.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Per-player round position that tracks winning stake and split claim status.
    pub miner: &'b solana_account_info::AccountInfo<'a>,

    pub player: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> ClaimRoundSolCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ClaimRoundSolCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            round: accounts.round,
            miner: accounts.miner,
            player: accounts.player,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.signer.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.round.key, false));
        accounts.push(solana_instruction::AccountMeta::new(*self.miner.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.player.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = ClaimRoundSolInstructionData::new().try_to_vec().unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.round.clone());
        account_infos.push(self.miner.clone());
        account_infos.push(self.player.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ClaimRoundSol` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` signer
///   1. `[writable]` round
///   2. `[writable]` miner
///   3. `[writable]` player
#[derive(Clone, Debug)]
pub struct ClaimRoundSolCpiBuilder<'a, 'b> {
    instruction: Box<ClaimRoundSolCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClaimRoundSolCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ClaimRoundSolCpiBuilderInstruction {
            __program: program,
            signer: None,
            round: None,
            miner: None,
            player: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Signer that submits the claim transaction.
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    /// Settled round whose SOL payout is being claimed.
    #[inline(always)]
    pub fn round(&mut self, round: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.round = Some(round);
        self
    }
    /// Per-player round position that tracks winning stake and split claim status.
    #[inline(always)]
    pub fn miner(&mut self, miner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.miner = Some(miner);
        self
    }
    #[inline(always)]
    pub fn player(&mut self, player: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.player = Some(player);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = ClaimRoundSolCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            round: self.instruction.round.expect("round is not set"),

            miner: self.instruction.miner.expect("miner is not set"),

            player: self.instruction.player.expect("player is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ClaimRoundSolCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    round: Option<&'b solana_account_info::AccountInfo<'a>>,
    miner: Option<&'b solana_account_info::AccountInfo<'a>>,
    player: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
