//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CLOSE_ROUND_ACCOUNTS_DISCRIMINATOR: [u8; 8] = [158, 92, 241, 90, 112, 189, 63, 133];

/// Accounts.
#[derive(Debug)]
pub struct CloseRoundAccounts {
    /// Crank signer authorized to submit cleanup transactions.
    pub signer: solana_address::Address,
    /// Global config containing the crank authority and canonical treasury address.
    pub config: solana_address::Address,
    /// Board account used to ensure no live pointer references the round.
    pub board: solana_address::Address,
    /// Fully cleaned round account being closed to the crank signer.
    pub round: solana_address::Address,
    /// Matching round-secret account being closed to the crank signer.
    pub round_secret: solana_address::Address,
    /// Canonical treasury PDA used to validate the payout sweep destination.
    pub treasury: solana_address::Address,
    /// Protocol ZINC mint used by the round payout vault.
    pub zinc_mint: solana_address::Address,
    /// Round-owned ZINC vault being swept and closed.
    pub round_zinc_payout_token_account: solana_address::Address,
    /// Treasury curve-admin vault that receives residual round ZINC dust.
    pub curve_admin_token_account: solana_address::Address,
    /// SPL Token program used to sweep and close the round ZINC vault.
    pub token_program: solana_address::Address,
}

impl CloseRoundAccounts {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.board, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.round, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.round_secret,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.treasury, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.zinc_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.round_zinc_payout_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.curve_admin_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = CloseRoundAccountsInstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CloseRoundAccountsInstructionData {
    discriminator: [u8; 8],
}

impl CloseRoundAccountsInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [158, 92, 241, 90, 112, 189, 63, 133],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for CloseRoundAccountsInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `CloseRoundAccounts`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[]` config
///   2. `[]` board
///   3. `[writable]` round
///   4. `[writable]` round_secret
///   5. `[writable]` treasury
///   6. `[]` zinc_mint
///   7. `[writable]` round_zinc_payout_token_account
///   8. `[writable]` curve_admin_token_account
///   9. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
#[derive(Clone, Debug, Default)]
pub struct CloseRoundAccountsBuilder {
    signer: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    board: Option<solana_address::Address>,
    round: Option<solana_address::Address>,
    round_secret: Option<solana_address::Address>,
    treasury: Option<solana_address::Address>,
    zinc_mint: Option<solana_address::Address>,
    round_zinc_payout_token_account: Option<solana_address::Address>,
    curve_admin_token_account: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CloseRoundAccountsBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Crank signer authorized to submit cleanup transactions.
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    /// Global config containing the crank authority and canonical treasury address.
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// Board account used to ensure no live pointer references the round.
    #[inline(always)]
    pub fn board(&mut self, board: solana_address::Address) -> &mut Self {
        self.board = Some(board);
        self
    }
    /// Fully cleaned round account being closed to the crank signer.
    #[inline(always)]
    pub fn round(&mut self, round: solana_address::Address) -> &mut Self {
        self.round = Some(round);
        self
    }
    /// Matching round-secret account being closed to the crank signer.
    #[inline(always)]
    pub fn round_secret(&mut self, round_secret: solana_address::Address) -> &mut Self {
        self.round_secret = Some(round_secret);
        self
    }
    /// Canonical treasury PDA used to validate the payout sweep destination.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: solana_address::Address) -> &mut Self {
        self.treasury = Some(treasury);
        self
    }
    /// Protocol ZINC mint used by the round payout vault.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: solana_address::Address) -> &mut Self {
        self.zinc_mint = Some(zinc_mint);
        self
    }
    /// Round-owned ZINC vault being swept and closed.
    #[inline(always)]
    pub fn round_zinc_payout_token_account(
        &mut self,
        round_zinc_payout_token_account: solana_address::Address,
    ) -> &mut Self {
        self.round_zinc_payout_token_account = Some(round_zinc_payout_token_account);
        self
    }
    /// Treasury curve-admin vault that receives residual round ZINC dust.
    #[inline(always)]
    pub fn curve_admin_token_account(
        &mut self,
        curve_admin_token_account: solana_address::Address,
    ) -> &mut Self {
        self.curve_admin_token_account = Some(curve_admin_token_account);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    /// SPL Token program used to sweep and close the round ZINC vault.
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CloseRoundAccounts {
            signer: self.signer.expect("signer is not set"),
            config: self.config.expect("config is not set"),
            board: self.board.expect("board is not set"),
            round: self.round.expect("round is not set"),
            round_secret: self.round_secret.expect("round_secret is not set"),
            treasury: self.treasury.expect("treasury is not set"),
            zinc_mint: self.zinc_mint.expect("zinc_mint is not set"),
            round_zinc_payout_token_account: self
                .round_zinc_payout_token_account
                .expect("round_zinc_payout_token_account is not set"),
            curve_admin_token_account: self
                .curve_admin_token_account
                .expect("curve_admin_token_account is not set"),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `close_round_accounts` CPI accounts.
pub struct CloseRoundAccountsCpiAccounts<'a, 'b> {
    /// Crank signer authorized to submit cleanup transactions.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority and canonical treasury address.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Board account used to ensure no live pointer references the round.
    pub board: &'b solana_account_info::AccountInfo<'a>,
    /// Fully cleaned round account being closed to the crank signer.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Matching round-secret account being closed to the crank signer.
    pub round_secret: &'b solana_account_info::AccountInfo<'a>,
    /// Canonical treasury PDA used to validate the payout sweep destination.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used by the round payout vault.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Round-owned ZINC vault being swept and closed.
    pub round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury curve-admin vault that receives residual round ZINC dust.
    pub curve_admin_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token program used to sweep and close the round ZINC vault.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `close_round_accounts` CPI instruction.
pub struct CloseRoundAccountsCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Crank signer authorized to submit cleanup transactions.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority and canonical treasury address.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Board account used to ensure no live pointer references the round.
    pub board: &'b solana_account_info::AccountInfo<'a>,
    /// Fully cleaned round account being closed to the crank signer.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Matching round-secret account being closed to the crank signer.
    pub round_secret: &'b solana_account_info::AccountInfo<'a>,
    /// Canonical treasury PDA used to validate the payout sweep destination.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used by the round payout vault.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Round-owned ZINC vault being swept and closed.
    pub round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury curve-admin vault that receives residual round ZINC dust.
    pub curve_admin_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token program used to sweep and close the round ZINC vault.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> CloseRoundAccountsCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CloseRoundAccountsCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            config: accounts.config,
            board: accounts.board,
            round: accounts.round,
            round_secret: accounts.round_secret,
            treasury: accounts.treasury,
            zinc_mint: accounts.zinc_mint,
            round_zinc_payout_token_account: accounts.round_zinc_payout_token_account,
            curve_admin_token_account: accounts.curve_admin_token_account,
            token_program: accounts.token_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.board.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.round.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.round_secret.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.treasury.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.zinc_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.round_zinc_payout_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.curve_admin_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = CloseRoundAccountsInstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(11 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.board.clone());
        account_infos.push(self.round.clone());
        account_infos.push(self.round_secret.clone());
        account_infos.push(self.treasury.clone());
        account_infos.push(self.zinc_mint.clone());
        account_infos.push(self.round_zinc_payout_token_account.clone());
        account_infos.push(self.curve_admin_token_account.clone());
        account_infos.push(self.token_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CloseRoundAccounts` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[]` config
///   2. `[]` board
///   3. `[writable]` round
///   4. `[writable]` round_secret
///   5. `[writable]` treasury
///   6. `[]` zinc_mint
///   7. `[writable]` round_zinc_payout_token_account
///   8. `[writable]` curve_admin_token_account
///   9. `[]` token_program
#[derive(Clone, Debug)]
pub struct CloseRoundAccountsCpiBuilder<'a, 'b> {
    instruction: Box<CloseRoundAccountsCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CloseRoundAccountsCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CloseRoundAccountsCpiBuilderInstruction {
            __program: program,
            signer: None,
            config: None,
            board: None,
            round: None,
            round_secret: None,
            treasury: None,
            zinc_mint: None,
            round_zinc_payout_token_account: None,
            curve_admin_token_account: None,
            token_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Crank signer authorized to submit cleanup transactions.
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    /// Global config containing the crank authority and canonical treasury address.
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    /// Board account used to ensure no live pointer references the round.
    #[inline(always)]
    pub fn board(&mut self, board: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.board = Some(board);
        self
    }
    /// Fully cleaned round account being closed to the crank signer.
    #[inline(always)]
    pub fn round(&mut self, round: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.round = Some(round);
        self
    }
    /// Matching round-secret account being closed to the crank signer.
    #[inline(always)]
    pub fn round_secret(
        &mut self,
        round_secret: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.round_secret = Some(round_secret);
        self
    }
    /// Canonical treasury PDA used to validate the payout sweep destination.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.treasury = Some(treasury);
        self
    }
    /// Protocol ZINC mint used by the round payout vault.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.zinc_mint = Some(zinc_mint);
        self
    }
    /// Round-owned ZINC vault being swept and closed.
    #[inline(always)]
    pub fn round_zinc_payout_token_account(
        &mut self,
        round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.round_zinc_payout_token_account = Some(round_zinc_payout_token_account);
        self
    }
    /// Treasury curve-admin vault that receives residual round ZINC dust.
    #[inline(always)]
    pub fn curve_admin_token_account(
        &mut self,
        curve_admin_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.curve_admin_token_account = Some(curve_admin_token_account);
        self
    }
    /// SPL Token program used to sweep and close the round ZINC vault.
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = CloseRoundAccountsCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            config: self.instruction.config.expect("config is not set"),

            board: self.instruction.board.expect("board is not set"),

            round: self.instruction.round.expect("round is not set"),

            round_secret: self
                .instruction
                .round_secret
                .expect("round_secret is not set"),

            treasury: self.instruction.treasury.expect("treasury is not set"),

            zinc_mint: self.instruction.zinc_mint.expect("zinc_mint is not set"),

            round_zinc_payout_token_account: self
                .instruction
                .round_zinc_payout_token_account
                .expect("round_zinc_payout_token_account is not set"),

            curve_admin_token_account: self
                .instruction
                .curve_admin_token_account
                .expect("curve_admin_token_account is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CloseRoundAccountsCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    board: Option<&'b solana_account_info::AccountInfo<'a>>,
    round: Option<&'b solana_account_info::AccountInfo<'a>>,
    round_secret: Option<&'b solana_account_info::AccountInfo<'a>>,
    treasury: Option<&'b solana_account_info::AccountInfo<'a>>,
    zinc_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    round_zinc_payout_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    curve_admin_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
