//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CREATE_BUYBACK_POOL_DISCRIMINATOR: [u8; 8] = [149, 112, 78, 105, 27, 160, 104, 167];

/// Accounts.
#[derive(Debug)]
pub struct CreateBuybackPool {
    /// Admin authorized to register the protocol buyback pool.
    pub admin: solana_address::Address,
    /// Global config containing admin and treasury settings.
    pub config: solana_address::Address,
    /// Treasury PDA that owns the ZINC mint authority.
    pub treasury: solana_address::Address,
    /// Singleton buyback pool manifest created after the Meteora pool exists.
    pub buyback_pool: solana_address::Address,
    /// SPL native mint used as the pool's WSOL side.
    pub wsol_mint: solana_address::Address,
    /// Protocol ZINC mint used as the pool's ZINC side.
    pub zinc_mint: solana_address::Address,
    /// Admin-owned WSOL ATA funded from admin SOL for initial LP seeding.
    pub admin_wsol_token_account: solana_address::Address,
    /// Admin-owned ZINC ATA funded by the protocol mint for initial LP seeding.
    pub admin_zinc_token_account: solana_address::Address,

    pub damm_config: solana_address::Address,

    pub meteora_program: solana_address::Address,

    pub pool_authority: solana_address::Address,

    pub pool: solana_address::Address,

    pub position_nft_mint: solana_address::Address,

    pub position_nft_account: solana_address::Address,

    pub position: solana_address::Address,

    pub token_a_vault: solana_address::Address,

    pub token_b_vault: solana_address::Address,

    pub event_authority: solana_address::Address,
    /// Associated Token Program used to create admin ATAs when missing.
    pub associated_token_program: solana_address::Address,
    /// SPL Token Program for WSOL and ZINC.
    pub token_program: solana_address::Address,
    /// Token-2022 Program used by Meteora for the initial position NFT.
    pub token2022_program: solana_address::Address,
    /// System Program used for pool account creation and SOL wrapping.
    pub system_program: solana_address::Address,
}

impl CreateBuybackPool {
    pub fn instruction(
        &self,
        args: CreateBuybackPoolInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: CreateBuybackPoolInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(22 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.admin, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.treasury, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.buyback_pool,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.wsol_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.zinc_mint, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.admin_wsol_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.admin_zinc_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.damm_config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.meteora_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.pool, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.position_nft_mint,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.position_nft_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.position, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_a_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_b_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token2022_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = CreateBuybackPoolInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CreateBuybackPoolInstructionData {
    discriminator: [u8; 8],
}

impl CreateBuybackPoolInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [149, 112, 78, 105, 27, 160, 104, 167],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for CreateBuybackPoolInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CreateBuybackPoolInstructionArgs {
    pub lp_zinc_amount: u64,
    pub initial_wsol_lamports: u64,
    pub liquidity: u128,
    pub sqrt_price: u128,
    pub activation_point: Option<u64>,
}

impl CreateBuybackPoolInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `CreateBuybackPool`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[]` config
///   2. `[writable]` treasury
///   3. `[writable]` buyback_pool
///   4. `[optional]` wsol_mint (default to `So11111111111111111111111111111111111111112`)
///   5. `[writable]` zinc_mint
///   6. `[writable]` admin_wsol_token_account
///   7. `[writable]` admin_zinc_token_account
///   8. `[]` damm_config
///   9. `[optional]` meteora_program (default to `cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG`)
///   10. `[]` pool_authority
///   11. `[writable]` pool
///   12. `[writable, signer]` position_nft_mint
///   13. `[writable]` position_nft_account
///   14. `[writable]` position
///   15. `[writable]` token_a_vault
///   16. `[writable]` token_b_vault
///   17. `[]` event_authority
///   18. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
///   19. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   20. `[optional]` token2022_program (default to `TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb`)
///   21. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CreateBuybackPoolBuilder {
    admin: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    treasury: Option<solana_address::Address>,
    buyback_pool: Option<solana_address::Address>,
    wsol_mint: Option<solana_address::Address>,
    zinc_mint: Option<solana_address::Address>,
    admin_wsol_token_account: Option<solana_address::Address>,
    admin_zinc_token_account: Option<solana_address::Address>,
    damm_config: Option<solana_address::Address>,
    meteora_program: Option<solana_address::Address>,
    pool_authority: Option<solana_address::Address>,
    pool: Option<solana_address::Address>,
    position_nft_mint: Option<solana_address::Address>,
    position_nft_account: Option<solana_address::Address>,
    position: Option<solana_address::Address>,
    token_a_vault: Option<solana_address::Address>,
    token_b_vault: Option<solana_address::Address>,
    event_authority: Option<solana_address::Address>,
    associated_token_program: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    token2022_program: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    lp_zinc_amount: Option<u64>,
    initial_wsol_lamports: Option<u64>,
    liquidity: Option<u128>,
    sqrt_price: Option<u128>,
    activation_point: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CreateBuybackPoolBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Admin authorized to register the protocol buyback pool.
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_address::Address) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    /// Global config containing admin and treasury settings.
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// Treasury PDA that owns the ZINC mint authority.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: solana_address::Address) -> &mut Self {
        self.treasury = Some(treasury);
        self
    }
    /// Singleton buyback pool manifest created after the Meteora pool exists.
    #[inline(always)]
    pub fn buyback_pool(&mut self, buyback_pool: solana_address::Address) -> &mut Self {
        self.buyback_pool = Some(buyback_pool);
        self
    }
    /// `[optional account, default to 'So11111111111111111111111111111111111111112']`
    /// SPL native mint used as the pool's WSOL side.
    #[inline(always)]
    pub fn wsol_mint(&mut self, wsol_mint: solana_address::Address) -> &mut Self {
        self.wsol_mint = Some(wsol_mint);
        self
    }
    /// Protocol ZINC mint used as the pool's ZINC side.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: solana_address::Address) -> &mut Self {
        self.zinc_mint = Some(zinc_mint);
        self
    }
    /// Admin-owned WSOL ATA funded from admin SOL for initial LP seeding.
    #[inline(always)]
    pub fn admin_wsol_token_account(
        &mut self,
        admin_wsol_token_account: solana_address::Address,
    ) -> &mut Self {
        self.admin_wsol_token_account = Some(admin_wsol_token_account);
        self
    }
    /// Admin-owned ZINC ATA funded by the protocol mint for initial LP seeding.
    #[inline(always)]
    pub fn admin_zinc_token_account(
        &mut self,
        admin_zinc_token_account: solana_address::Address,
    ) -> &mut Self {
        self.admin_zinc_token_account = Some(admin_zinc_token_account);
        self
    }
    #[inline(always)]
    pub fn damm_config(&mut self, damm_config: solana_address::Address) -> &mut Self {
        self.damm_config = Some(damm_config);
        self
    }
    /// `[optional account, default to 'cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG']`
    #[inline(always)]
    pub fn meteora_program(&mut self, meteora_program: solana_address::Address) -> &mut Self {
        self.meteora_program = Some(meteora_program);
        self
    }
    #[inline(always)]
    pub fn pool_authority(&mut self, pool_authority: solana_address::Address) -> &mut Self {
        self.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: solana_address::Address) -> &mut Self {
        self.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn position_nft_mint(&mut self, position_nft_mint: solana_address::Address) -> &mut Self {
        self.position_nft_mint = Some(position_nft_mint);
        self
    }
    #[inline(always)]
    pub fn position_nft_account(
        &mut self,
        position_nft_account: solana_address::Address,
    ) -> &mut Self {
        self.position_nft_account = Some(position_nft_account);
        self
    }
    #[inline(always)]
    pub fn position(&mut self, position: solana_address::Address) -> &mut Self {
        self.position = Some(position);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(&mut self, token_a_vault: solana_address::Address) -> &mut Self {
        self.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(&mut self, token_b_vault: solana_address::Address) -> &mut Self {
        self.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_address::Address) -> &mut Self {
        self.event_authority = Some(event_authority);
        self
    }
    /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
    /// Associated Token Program used to create admin ATAs when missing.
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: solana_address::Address,
    ) -> &mut Self {
        self.associated_token_program = Some(associated_token_program);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    /// SPL Token Program for WSOL and ZINC.
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// `[optional account, default to 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb']`
    /// Token-2022 Program used by Meteora for the initial position NFT.
    #[inline(always)]
    pub fn token2022_program(&mut self, token2022_program: solana_address::Address) -> &mut Self {
        self.token2022_program = Some(token2022_program);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// System Program used for pool account creation and SOL wrapping.
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn lp_zinc_amount(&mut self, lp_zinc_amount: u64) -> &mut Self {
        self.lp_zinc_amount = Some(lp_zinc_amount);
        self
    }
    #[inline(always)]
    pub fn initial_wsol_lamports(&mut self, initial_wsol_lamports: u64) -> &mut Self {
        self.initial_wsol_lamports = Some(initial_wsol_lamports);
        self
    }
    #[inline(always)]
    pub fn liquidity(&mut self, liquidity: u128) -> &mut Self {
        self.liquidity = Some(liquidity);
        self
    }
    #[inline(always)]
    pub fn sqrt_price(&mut self, sqrt_price: u128) -> &mut Self {
        self.sqrt_price = Some(sqrt_price);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn activation_point(&mut self, activation_point: u64) -> &mut Self {
        self.activation_point = Some(activation_point);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CreateBuybackPool {
            admin: self.admin.expect("admin is not set"),
            config: self.config.expect("config is not set"),
            treasury: self.treasury.expect("treasury is not set"),
            buyback_pool: self.buyback_pool.expect("buyback_pool is not set"),
            wsol_mint: self.wsol_mint.unwrap_or(solana_address::address!(
                "So11111111111111111111111111111111111111112"
            )),
            zinc_mint: self.zinc_mint.expect("zinc_mint is not set"),
            admin_wsol_token_account: self
                .admin_wsol_token_account
                .expect("admin_wsol_token_account is not set"),
            admin_zinc_token_account: self
                .admin_zinc_token_account
                .expect("admin_zinc_token_account is not set"),
            damm_config: self.damm_config.expect("damm_config is not set"),
            meteora_program: self.meteora_program.unwrap_or(solana_address::address!(
                "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"
            )),
            pool_authority: self.pool_authority.expect("pool_authority is not set"),
            pool: self.pool.expect("pool is not set"),
            position_nft_mint: self
                .position_nft_mint
                .expect("position_nft_mint is not set"),
            position_nft_account: self
                .position_nft_account
                .expect("position_nft_account is not set"),
            position: self.position.expect("position is not set"),
            token_a_vault: self.token_a_vault.expect("token_a_vault is not set"),
            token_b_vault: self.token_b_vault.expect("token_b_vault is not set"),
            event_authority: self.event_authority.expect("event_authority is not set"),
            associated_token_program: self.associated_token_program.unwrap_or(
                solana_address::address!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
            ),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            token2022_program: self.token2022_program.unwrap_or(solana_address::address!(
                "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = CreateBuybackPoolInstructionArgs {
            lp_zinc_amount: self
                .lp_zinc_amount
                .clone()
                .expect("lp_zinc_amount is not set"),
            initial_wsol_lamports: self
                .initial_wsol_lamports
                .clone()
                .expect("initial_wsol_lamports is not set"),
            liquidity: self.liquidity.clone().expect("liquidity is not set"),
            sqrt_price: self.sqrt_price.clone().expect("sqrt_price is not set"),
            activation_point: self.activation_point.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `create_buyback_pool` CPI accounts.
pub struct CreateBuybackPoolCpiAccounts<'a, 'b> {
    /// Admin authorized to register the protocol buyback pool.
    pub admin: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing admin and treasury settings.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury PDA that owns the ZINC mint authority.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Singleton buyback pool manifest created after the Meteora pool exists.
    pub buyback_pool: &'b solana_account_info::AccountInfo<'a>,
    /// SPL native mint used as the pool's WSOL side.
    pub wsol_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used as the pool's ZINC side.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Admin-owned WSOL ATA funded from admin SOL for initial LP seeding.
    pub admin_wsol_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Admin-owned ZINC ATA funded by the protocol mint for initial LP seeding.
    pub admin_zinc_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub damm_config: &'b solana_account_info::AccountInfo<'a>,

    pub meteora_program: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub position_nft_mint: &'b solana_account_info::AccountInfo<'a>,

    pub position_nft_account: &'b solana_account_info::AccountInfo<'a>,

    pub position: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,
    /// Associated Token Program used to create admin ATAs when missing.
    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token Program for WSOL and ZINC.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token-2022 Program used by Meteora for the initial position NFT.
    pub token2022_program: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used for pool account creation and SOL wrapping.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `create_buyback_pool` CPI instruction.
pub struct CreateBuybackPoolCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Admin authorized to register the protocol buyback pool.
    pub admin: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing admin and treasury settings.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury PDA that owns the ZINC mint authority.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Singleton buyback pool manifest created after the Meteora pool exists.
    pub buyback_pool: &'b solana_account_info::AccountInfo<'a>,
    /// SPL native mint used as the pool's WSOL side.
    pub wsol_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used as the pool's ZINC side.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Admin-owned WSOL ATA funded from admin SOL for initial LP seeding.
    pub admin_wsol_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Admin-owned ZINC ATA funded by the protocol mint for initial LP seeding.
    pub admin_zinc_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub damm_config: &'b solana_account_info::AccountInfo<'a>,

    pub meteora_program: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub position_nft_mint: &'b solana_account_info::AccountInfo<'a>,

    pub position_nft_account: &'b solana_account_info::AccountInfo<'a>,

    pub position: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,
    /// Associated Token Program used to create admin ATAs when missing.
    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token Program for WSOL and ZINC.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token-2022 Program used by Meteora for the initial position NFT.
    pub token2022_program: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used for pool account creation and SOL wrapping.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: CreateBuybackPoolInstructionArgs,
}

impl<'a, 'b> CreateBuybackPoolCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CreateBuybackPoolCpiAccounts<'a, 'b>,
        args: CreateBuybackPoolInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            config: accounts.config,
            treasury: accounts.treasury,
            buyback_pool: accounts.buyback_pool,
            wsol_mint: accounts.wsol_mint,
            zinc_mint: accounts.zinc_mint,
            admin_wsol_token_account: accounts.admin_wsol_token_account,
            admin_zinc_token_account: accounts.admin_zinc_token_account,
            damm_config: accounts.damm_config,
            meteora_program: accounts.meteora_program,
            pool_authority: accounts.pool_authority,
            pool: accounts.pool,
            position_nft_mint: accounts.position_nft_mint,
            position_nft_account: accounts.position_nft_account,
            position: accounts.position,
            token_a_vault: accounts.token_a_vault,
            token_b_vault: accounts.token_b_vault,
            event_authority: accounts.event_authority,
            associated_token_program: accounts.associated_token_program,
            token_program: accounts.token_program,
            token2022_program: accounts.token2022_program,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(22 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.admin.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.treasury.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.buyback_pool.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.wsol_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.zinc_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.admin_wsol_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.admin_zinc_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.damm_config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.meteora_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.pool.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.position_nft_mint.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.position_nft_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.position.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_a_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_b_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token2022_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = CreateBuybackPoolInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(23 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.treasury.clone());
        account_infos.push(self.buyback_pool.clone());
        account_infos.push(self.wsol_mint.clone());
        account_infos.push(self.zinc_mint.clone());
        account_infos.push(self.admin_wsol_token_account.clone());
        account_infos.push(self.admin_zinc_token_account.clone());
        account_infos.push(self.damm_config.clone());
        account_infos.push(self.meteora_program.clone());
        account_infos.push(self.pool_authority.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.position_nft_mint.clone());
        account_infos.push(self.position_nft_account.clone());
        account_infos.push(self.position.clone());
        account_infos.push(self.token_a_vault.clone());
        account_infos.push(self.token_b_vault.clone());
        account_infos.push(self.event_authority.clone());
        account_infos.push(self.associated_token_program.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.token2022_program.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CreateBuybackPool` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[]` config
///   2. `[writable]` treasury
///   3. `[writable]` buyback_pool
///   4. `[]` wsol_mint
///   5. `[writable]` zinc_mint
///   6. `[writable]` admin_wsol_token_account
///   7. `[writable]` admin_zinc_token_account
///   8. `[]` damm_config
///   9. `[]` meteora_program
///   10. `[]` pool_authority
///   11. `[writable]` pool
///   12. `[writable, signer]` position_nft_mint
///   13. `[writable]` position_nft_account
///   14. `[writable]` position
///   15. `[writable]` token_a_vault
///   16. `[writable]` token_b_vault
///   17. `[]` event_authority
///   18. `[]` associated_token_program
///   19. `[]` token_program
///   20. `[]` token2022_program
///   21. `[]` system_program
#[derive(Clone, Debug)]
pub struct CreateBuybackPoolCpiBuilder<'a, 'b> {
    instruction: Box<CreateBuybackPoolCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateBuybackPoolCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CreateBuybackPoolCpiBuilderInstruction {
            __program: program,
            admin: None,
            config: None,
            treasury: None,
            buyback_pool: None,
            wsol_mint: None,
            zinc_mint: None,
            admin_wsol_token_account: None,
            admin_zinc_token_account: None,
            damm_config: None,
            meteora_program: None,
            pool_authority: None,
            pool: None,
            position_nft_mint: None,
            position_nft_account: None,
            position: None,
            token_a_vault: None,
            token_b_vault: None,
            event_authority: None,
            associated_token_program: None,
            token_program: None,
            token2022_program: None,
            system_program: None,
            lp_zinc_amount: None,
            initial_wsol_lamports: None,
            liquidity: None,
            sqrt_price: None,
            activation_point: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Admin authorized to register the protocol buyback pool.
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    /// Global config containing admin and treasury settings.
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    /// Treasury PDA that owns the ZINC mint authority.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.treasury = Some(treasury);
        self
    }
    /// Singleton buyback pool manifest created after the Meteora pool exists.
    #[inline(always)]
    pub fn buyback_pool(
        &mut self,
        buyback_pool: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.buyback_pool = Some(buyback_pool);
        self
    }
    /// SPL native mint used as the pool's WSOL side.
    #[inline(always)]
    pub fn wsol_mint(&mut self, wsol_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.wsol_mint = Some(wsol_mint);
        self
    }
    /// Protocol ZINC mint used as the pool's ZINC side.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.zinc_mint = Some(zinc_mint);
        self
    }
    /// Admin-owned WSOL ATA funded from admin SOL for initial LP seeding.
    #[inline(always)]
    pub fn admin_wsol_token_account(
        &mut self,
        admin_wsol_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.admin_wsol_token_account = Some(admin_wsol_token_account);
        self
    }
    /// Admin-owned ZINC ATA funded by the protocol mint for initial LP seeding.
    #[inline(always)]
    pub fn admin_zinc_token_account(
        &mut self,
        admin_zinc_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.admin_zinc_token_account = Some(admin_zinc_token_account);
        self
    }
    #[inline(always)]
    pub fn damm_config(
        &mut self,
        damm_config: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.damm_config = Some(damm_config);
        self
    }
    #[inline(always)]
    pub fn meteora_program(
        &mut self,
        meteora_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.meteora_program = Some(meteora_program);
        self
    }
    #[inline(always)]
    pub fn pool_authority(
        &mut self,
        pool_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn position_nft_mint(
        &mut self,
        position_nft_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.position_nft_mint = Some(position_nft_mint);
        self
    }
    #[inline(always)]
    pub fn position_nft_account(
        &mut self,
        position_nft_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.position_nft_account = Some(position_nft_account);
        self
    }
    #[inline(always)]
    pub fn position(&mut self, position: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.position = Some(position);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(
        &mut self,
        token_a_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(
        &mut self,
        token_b_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn event_authority(
        &mut self,
        event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_authority = Some(event_authority);
        self
    }
    /// Associated Token Program used to create admin ATAs when missing.
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.associated_token_program = Some(associated_token_program);
        self
    }
    /// SPL Token Program for WSOL and ZINC.
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    /// Token-2022 Program used by Meteora for the initial position NFT.
    #[inline(always)]
    pub fn token2022_program(
        &mut self,
        token2022_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token2022_program = Some(token2022_program);
        self
    }
    /// System Program used for pool account creation and SOL wrapping.
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn lp_zinc_amount(&mut self, lp_zinc_amount: u64) -> &mut Self {
        self.instruction.lp_zinc_amount = Some(lp_zinc_amount);
        self
    }
    #[inline(always)]
    pub fn initial_wsol_lamports(&mut self, initial_wsol_lamports: u64) -> &mut Self {
        self.instruction.initial_wsol_lamports = Some(initial_wsol_lamports);
        self
    }
    #[inline(always)]
    pub fn liquidity(&mut self, liquidity: u128) -> &mut Self {
        self.instruction.liquidity = Some(liquidity);
        self
    }
    #[inline(always)]
    pub fn sqrt_price(&mut self, sqrt_price: u128) -> &mut Self {
        self.instruction.sqrt_price = Some(sqrt_price);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn activation_point(&mut self, activation_point: u64) -> &mut Self {
        self.instruction.activation_point = Some(activation_point);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = CreateBuybackPoolInstructionArgs {
            lp_zinc_amount: self
                .instruction
                .lp_zinc_amount
                .clone()
                .expect("lp_zinc_amount is not set"),
            initial_wsol_lamports: self
                .instruction
                .initial_wsol_lamports
                .clone()
                .expect("initial_wsol_lamports is not set"),
            liquidity: self
                .instruction
                .liquidity
                .clone()
                .expect("liquidity is not set"),
            sqrt_price: self
                .instruction
                .sqrt_price
                .clone()
                .expect("sqrt_price is not set"),
            activation_point: self.instruction.activation_point.clone(),
        };
        let instruction = CreateBuybackPoolCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            config: self.instruction.config.expect("config is not set"),

            treasury: self.instruction.treasury.expect("treasury is not set"),

            buyback_pool: self
                .instruction
                .buyback_pool
                .expect("buyback_pool is not set"),

            wsol_mint: self.instruction.wsol_mint.expect("wsol_mint is not set"),

            zinc_mint: self.instruction.zinc_mint.expect("zinc_mint is not set"),

            admin_wsol_token_account: self
                .instruction
                .admin_wsol_token_account
                .expect("admin_wsol_token_account is not set"),

            admin_zinc_token_account: self
                .instruction
                .admin_zinc_token_account
                .expect("admin_zinc_token_account is not set"),

            damm_config: self
                .instruction
                .damm_config
                .expect("damm_config is not set"),

            meteora_program: self
                .instruction
                .meteora_program
                .expect("meteora_program is not set"),

            pool_authority: self
                .instruction
                .pool_authority
                .expect("pool_authority is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            position_nft_mint: self
                .instruction
                .position_nft_mint
                .expect("position_nft_mint is not set"),

            position_nft_account: self
                .instruction
                .position_nft_account
                .expect("position_nft_account is not set"),

            position: self.instruction.position.expect("position is not set"),

            token_a_vault: self
                .instruction
                .token_a_vault
                .expect("token_a_vault is not set"),

            token_b_vault: self
                .instruction
                .token_b_vault
                .expect("token_b_vault is not set"),

            event_authority: self
                .instruction
                .event_authority
                .expect("event_authority is not set"),

            associated_token_program: self
                .instruction
                .associated_token_program
                .expect("associated_token_program is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            token2022_program: self
                .instruction
                .token2022_program
                .expect("token2022_program is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CreateBuybackPoolCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    treasury: Option<&'b solana_account_info::AccountInfo<'a>>,
    buyback_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    wsol_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    zinc_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    admin_wsol_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    admin_zinc_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    damm_config: Option<&'b solana_account_info::AccountInfo<'a>>,
    meteora_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    position_nft_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    position_nft_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    position: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token2022_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    lp_zinc_amount: Option<u64>,
    initial_wsol_lamports: Option<u64>,
    liquidity: Option<u128>,
    sqrt_price: Option<u128>,
    activation_point: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
