//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CREDIT_ROUND_ZINC_DISCRIMINATOR: [u8; 8] = [236, 221, 193, 26, 45, 137, 4, 147];

/// Accounts.
#[derive(Debug)]
pub struct CreditRoundZinc {
    /// Crank signer that submits the reward-credit transaction.
    pub signer: solana_address::Address,
    /// Global config containing the crank authority.
    pub config: solana_address::Address,
    /// Settled round whose ZINC rewards are being credited.
    pub round: solana_address::Address,
    /// Per-player round position that tracks winning stake and split terminal state.
    pub miner: solana_address::Address,

    pub player: solana_address::Address,

    pub player_profile: solana_address::Address,
    /// Treasury PDA that owns the Bonanza and singleton round-reward vaults.
    pub treasury: solana_address::Address,
    /// Protocol ZINC mint used for round reward credits.
    pub zinc_mint: solana_address::Address,
    /// Round-owned payout vault that funds direct-winner credits.
    pub round_zinc_payout_token_account: solana_address::Address,
    /// Treasury-owned Bonanza vault that funds captured Bonanza credits.
    pub bonanza_token_account: solana_address::Address,
    /// Treasury-owned singleton vault that holds credited but unclaimed round ZINC.
    pub round_zinc_reward_token_account: solana_address::Address,
    /// SPL Token Program that owns the ZINC mint and token accounts.
    pub token_program: solana_address::Address,
    /// System Program used if the player's profile needs to be created.
    pub system_program: solana_address::Address,
}

impl CreditRoundZinc {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(13 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.round, false));
        accounts.push(solana_instruction::AccountMeta::new(self.miner, false));
        accounts.push(solana_instruction::AccountMeta::new(self.player, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.player_profile,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.treasury, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.zinc_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.round_zinc_payout_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.bonanza_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.round_zinc_reward_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = CreditRoundZincInstructionData::new().try_to_vec().unwrap();

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CreditRoundZincInstructionData {
    discriminator: [u8; 8],
}

impl CreditRoundZincInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [236, 221, 193, 26, 45, 137, 4, 147],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for CreditRoundZincInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `CreditRoundZinc`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[]` config
///   2. `[writable]` round
///   3. `[writable]` miner
///   4. `[writable]` player
///   5. `[writable]` player_profile
///   6. `[writable]` treasury
///   7. `[]` zinc_mint
///   8. `[writable]` round_zinc_payout_token_account
///   9. `[writable]` bonanza_token_account
///   10. `[writable]` round_zinc_reward_token_account
///   11. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   12. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CreditRoundZincBuilder {
    signer: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    round: Option<solana_address::Address>,
    miner: Option<solana_address::Address>,
    player: Option<solana_address::Address>,
    player_profile: Option<solana_address::Address>,
    treasury: Option<solana_address::Address>,
    zinc_mint: Option<solana_address::Address>,
    round_zinc_payout_token_account: Option<solana_address::Address>,
    bonanza_token_account: Option<solana_address::Address>,
    round_zinc_reward_token_account: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CreditRoundZincBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Crank signer that submits the reward-credit transaction.
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    /// Global config containing the crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// Settled round whose ZINC rewards are being credited.
    #[inline(always)]
    pub fn round(&mut self, round: solana_address::Address) -> &mut Self {
        self.round = Some(round);
        self
    }
    /// Per-player round position that tracks winning stake and split terminal state.
    #[inline(always)]
    pub fn miner(&mut self, miner: solana_address::Address) -> &mut Self {
        self.miner = Some(miner);
        self
    }
    #[inline(always)]
    pub fn player(&mut self, player: solana_address::Address) -> &mut Self {
        self.player = Some(player);
        self
    }
    #[inline(always)]
    pub fn player_profile(&mut self, player_profile: solana_address::Address) -> &mut Self {
        self.player_profile = Some(player_profile);
        self
    }
    /// Treasury PDA that owns the Bonanza and singleton round-reward vaults.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: solana_address::Address) -> &mut Self {
        self.treasury = Some(treasury);
        self
    }
    /// Protocol ZINC mint used for round reward credits.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: solana_address::Address) -> &mut Self {
        self.zinc_mint = Some(zinc_mint);
        self
    }
    /// Round-owned payout vault that funds direct-winner credits.
    #[inline(always)]
    pub fn round_zinc_payout_token_account(
        &mut self,
        round_zinc_payout_token_account: solana_address::Address,
    ) -> &mut Self {
        self.round_zinc_payout_token_account = Some(round_zinc_payout_token_account);
        self
    }
    /// Treasury-owned Bonanza vault that funds captured Bonanza credits.
    #[inline(always)]
    pub fn bonanza_token_account(
        &mut self,
        bonanza_token_account: solana_address::Address,
    ) -> &mut Self {
        self.bonanza_token_account = Some(bonanza_token_account);
        self
    }
    /// Treasury-owned singleton vault that holds credited but unclaimed round ZINC.
    #[inline(always)]
    pub fn round_zinc_reward_token_account(
        &mut self,
        round_zinc_reward_token_account: solana_address::Address,
    ) -> &mut Self {
        self.round_zinc_reward_token_account = Some(round_zinc_reward_token_account);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    /// SPL Token Program that owns the ZINC mint and token accounts.
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// System Program used if the player's profile needs to be created.
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CreditRoundZinc {
            signer: self.signer.expect("signer is not set"),
            config: self.config.expect("config is not set"),
            round: self.round.expect("round is not set"),
            miner: self.miner.expect("miner is not set"),
            player: self.player.expect("player is not set"),
            player_profile: self.player_profile.expect("player_profile is not set"),
            treasury: self.treasury.expect("treasury is not set"),
            zinc_mint: self.zinc_mint.expect("zinc_mint is not set"),
            round_zinc_payout_token_account: self
                .round_zinc_payout_token_account
                .expect("round_zinc_payout_token_account is not set"),
            bonanza_token_account: self
                .bonanza_token_account
                .expect("bonanza_token_account is not set"),
            round_zinc_reward_token_account: self
                .round_zinc_reward_token_account
                .expect("round_zinc_reward_token_account is not set"),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `credit_round_zinc` CPI accounts.
pub struct CreditRoundZincCpiAccounts<'a, 'b> {
    /// Crank signer that submits the reward-credit transaction.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Settled round whose ZINC rewards are being credited.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Per-player round position that tracks winning stake and split terminal state.
    pub miner: &'b solana_account_info::AccountInfo<'a>,

    pub player: &'b solana_account_info::AccountInfo<'a>,

    pub player_profile: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury PDA that owns the Bonanza and singleton round-reward vaults.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used for round reward credits.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Round-owned payout vault that funds direct-winner credits.
    pub round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned Bonanza vault that funds captured Bonanza credits.
    pub bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned singleton vault that holds credited but unclaimed round ZINC.
    pub round_zinc_reward_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token Program that owns the ZINC mint and token accounts.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used if the player's profile needs to be created.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `credit_round_zinc` CPI instruction.
pub struct CreditRoundZincCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Crank signer that submits the reward-credit transaction.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Settled round whose ZINC rewards are being credited.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Per-player round position that tracks winning stake and split terminal state.
    pub miner: &'b solana_account_info::AccountInfo<'a>,

    pub player: &'b solana_account_info::AccountInfo<'a>,

    pub player_profile: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury PDA that owns the Bonanza and singleton round-reward vaults.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used for round reward credits.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Round-owned payout vault that funds direct-winner credits.
    pub round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned Bonanza vault that funds captured Bonanza credits.
    pub bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned singleton vault that holds credited but unclaimed round ZINC.
    pub round_zinc_reward_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token Program that owns the ZINC mint and token accounts.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used if the player's profile needs to be created.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> CreditRoundZincCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CreditRoundZincCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            config: accounts.config,
            round: accounts.round,
            miner: accounts.miner,
            player: accounts.player,
            player_profile: accounts.player_profile,
            treasury: accounts.treasury,
            zinc_mint: accounts.zinc_mint,
            round_zinc_payout_token_account: accounts.round_zinc_payout_token_account,
            bonanza_token_account: accounts.bonanza_token_account,
            round_zinc_reward_token_account: accounts.round_zinc_reward_token_account,
            token_program: accounts.token_program,
            system_program: accounts.system_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(13 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.round.key, false));
        accounts.push(solana_instruction::AccountMeta::new(*self.miner.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.player.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.player_profile.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.treasury.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.zinc_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.round_zinc_payout_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.bonanza_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.round_zinc_reward_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = CreditRoundZincInstructionData::new().try_to_vec().unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(14 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.round.clone());
        account_infos.push(self.miner.clone());
        account_infos.push(self.player.clone());
        account_infos.push(self.player_profile.clone());
        account_infos.push(self.treasury.clone());
        account_infos.push(self.zinc_mint.clone());
        account_infos.push(self.round_zinc_payout_token_account.clone());
        account_infos.push(self.bonanza_token_account.clone());
        account_infos.push(self.round_zinc_reward_token_account.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CreditRoundZinc` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[]` config
///   2. `[writable]` round
///   3. `[writable]` miner
///   4. `[writable]` player
///   5. `[writable]` player_profile
///   6. `[writable]` treasury
///   7. `[]` zinc_mint
///   8. `[writable]` round_zinc_payout_token_account
///   9. `[writable]` bonanza_token_account
///   10. `[writable]` round_zinc_reward_token_account
///   11. `[]` token_program
///   12. `[]` system_program
#[derive(Clone, Debug)]
pub struct CreditRoundZincCpiBuilder<'a, 'b> {
    instruction: Box<CreditRoundZincCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreditRoundZincCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CreditRoundZincCpiBuilderInstruction {
            __program: program,
            signer: None,
            config: None,
            round: None,
            miner: None,
            player: None,
            player_profile: None,
            treasury: None,
            zinc_mint: None,
            round_zinc_payout_token_account: None,
            bonanza_token_account: None,
            round_zinc_reward_token_account: None,
            token_program: None,
            system_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Crank signer that submits the reward-credit transaction.
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    /// Global config containing the crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    /// Settled round whose ZINC rewards are being credited.
    #[inline(always)]
    pub fn round(&mut self, round: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.round = Some(round);
        self
    }
    /// Per-player round position that tracks winning stake and split terminal state.
    #[inline(always)]
    pub fn miner(&mut self, miner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.miner = Some(miner);
        self
    }
    #[inline(always)]
    pub fn player(&mut self, player: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.player = Some(player);
        self
    }
    #[inline(always)]
    pub fn player_profile(
        &mut self,
        player_profile: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.player_profile = Some(player_profile);
        self
    }
    /// Treasury PDA that owns the Bonanza and singleton round-reward vaults.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.treasury = Some(treasury);
        self
    }
    /// Protocol ZINC mint used for round reward credits.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.zinc_mint = Some(zinc_mint);
        self
    }
    /// Round-owned payout vault that funds direct-winner credits.
    #[inline(always)]
    pub fn round_zinc_payout_token_account(
        &mut self,
        round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.round_zinc_payout_token_account = Some(round_zinc_payout_token_account);
        self
    }
    /// Treasury-owned Bonanza vault that funds captured Bonanza credits.
    #[inline(always)]
    pub fn bonanza_token_account(
        &mut self,
        bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.bonanza_token_account = Some(bonanza_token_account);
        self
    }
    /// Treasury-owned singleton vault that holds credited but unclaimed round ZINC.
    #[inline(always)]
    pub fn round_zinc_reward_token_account(
        &mut self,
        round_zinc_reward_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.round_zinc_reward_token_account = Some(round_zinc_reward_token_account);
        self
    }
    /// SPL Token Program that owns the ZINC mint and token accounts.
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    /// System Program used if the player's profile needs to be created.
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = CreditRoundZincCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            config: self.instruction.config.expect("config is not set"),

            round: self.instruction.round.expect("round is not set"),

            miner: self.instruction.miner.expect("miner is not set"),

            player: self.instruction.player.expect("player is not set"),

            player_profile: self
                .instruction
                .player_profile
                .expect("player_profile is not set"),

            treasury: self.instruction.treasury.expect("treasury is not set"),

            zinc_mint: self.instruction.zinc_mint.expect("zinc_mint is not set"),

            round_zinc_payout_token_account: self
                .instruction
                .round_zinc_payout_token_account
                .expect("round_zinc_payout_token_account is not set"),

            bonanza_token_account: self
                .instruction
                .bonanza_token_account
                .expect("bonanza_token_account is not set"),

            round_zinc_reward_token_account: self
                .instruction
                .round_zinc_reward_token_account
                .expect("round_zinc_reward_token_account is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CreditRoundZincCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    round: Option<&'b solana_account_info::AccountInfo<'a>>,
    miner: Option<&'b solana_account_info::AccountInfo<'a>>,
    player: Option<&'b solana_account_info::AccountInfo<'a>>,
    player_profile: Option<&'b solana_account_info::AccountInfo<'a>>,
    treasury: Option<&'b solana_account_info::AccountInfo<'a>>,
    zinc_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    round_zinc_payout_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    bonanza_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    round_zinc_reward_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
