//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::ZkMaskAttestationArgs;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const DEPLOY_ROUND_DISCRIMINATOR: [u8; 8] = [30, 1, 160, 127, 39, 199, 134, 0];

/// Accounts.
#[derive(Debug)]
pub struct DeployRound {
    pub signer: solana_address::Address,

    pub round: solana_address::Address,

    pub config: solana_address::Address,

    pub miner: solana_address::Address,
    /// Lifetime deploy profile for the signing player.
    pub player_profile: solana_address::Address,
    /// Board singleton that tracks the currently enabled round, if any.
    pub board: solana_address::Address,

    pub treasury: solana_address::Address,
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    pub stockpile_sol_vault: solana_address::Address,
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    pub buyback_sol_vault: solana_address::Address,
    /// Active stockpile account, omitted when no cycle is currently joinable.
    pub stockpile: Option<solana_address::Address>,

    pub affiliate: Option<solana_address::Address>,

    pub affiliate_profile: Option<solana_address::Address>,

    pub system_program: solana_address::Address,
}

impl DeployRound {
    pub fn instruction(&self, args: DeployRoundInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: DeployRoundInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(13 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new(self.round, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.miner, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.player_profile,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.board, false));
        accounts.push(solana_instruction::AccountMeta::new(self.treasury, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.stockpile_sol_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.buyback_sol_vault,
            false,
        ));
        if let Some(stockpile) = self.stockpile {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                stockpile, false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::ZINC_ID,
                false,
            ));
        }
        if let Some(affiliate) = self.affiliate {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                affiliate, false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::ZINC_ID,
                false,
            ));
        }
        if let Some(affiliate_profile) = self.affiliate_profile {
            accounts.push(solana_instruction::AccountMeta::new(
                affiliate_profile,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::ZINC_ID,
                false,
            ));
        }
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = DeployRoundInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct DeployRoundInstructionData {
    discriminator: [u8; 8],
}

impl DeployRoundInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [30, 1, 160, 127, 39, 199, 134, 0],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for DeployRoundInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct DeployRoundInstructionArgs {
    pub total_amount: u64,
    pub mask_encryption_key: [u8; 32],
    pub mask_nonce: u128,
    pub mask_ciphertext: [u8; 64],
    pub zk_mask_attestation: Option<ZkMaskAttestationArgs>,
}

impl DeployRoundInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `DeployRound`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` round
///   2. `[]` config
///   3. `[writable]` miner
///   4. `[writable]` player_profile
///   5. `[writable]` board
///   6. `[writable]` treasury
///   7. `[writable]` stockpile_sol_vault
///   8. `[writable]` buyback_sol_vault
///   9. `[optional]` stockpile
///   10. `[optional]` affiliate
///   11. `[writable, optional]` affiliate_profile
///   12. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct DeployRoundBuilder {
    signer: Option<solana_address::Address>,
    round: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    miner: Option<solana_address::Address>,
    player_profile: Option<solana_address::Address>,
    board: Option<solana_address::Address>,
    treasury: Option<solana_address::Address>,
    stockpile_sol_vault: Option<solana_address::Address>,
    buyback_sol_vault: Option<solana_address::Address>,
    stockpile: Option<solana_address::Address>,
    affiliate: Option<solana_address::Address>,
    affiliate_profile: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    total_amount: Option<u64>,
    mask_encryption_key: Option<[u8; 32]>,
    mask_nonce: Option<u128>,
    mask_ciphertext: Option<[u8; 64]>,
    zk_mask_attestation: Option<ZkMaskAttestationArgs>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl DeployRoundBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn round(&mut self, round: solana_address::Address) -> &mut Self {
        self.round = Some(round);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn miner(&mut self, miner: solana_address::Address) -> &mut Self {
        self.miner = Some(miner);
        self
    }
    /// Lifetime deploy profile for the signing player.
    #[inline(always)]
    pub fn player_profile(&mut self, player_profile: solana_address::Address) -> &mut Self {
        self.player_profile = Some(player_profile);
        self
    }
    /// Board singleton that tracks the currently enabled round, if any.
    #[inline(always)]
    pub fn board(&mut self, board: solana_address::Address) -> &mut Self {
        self.board = Some(board);
        self
    }
    #[inline(always)]
    pub fn treasury(&mut self, treasury: solana_address::Address) -> &mut Self {
        self.treasury = Some(treasury);
        self
    }
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    #[inline(always)]
    pub fn stockpile_sol_vault(
        &mut self,
        stockpile_sol_vault: solana_address::Address,
    ) -> &mut Self {
        self.stockpile_sol_vault = Some(stockpile_sol_vault);
        self
    }
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    #[inline(always)]
    pub fn buyback_sol_vault(&mut self, buyback_sol_vault: solana_address::Address) -> &mut Self {
        self.buyback_sol_vault = Some(buyback_sol_vault);
        self
    }
    /// `[optional account]`
    /// Active stockpile account, omitted when no cycle is currently joinable.
    #[inline(always)]
    pub fn stockpile(&mut self, stockpile: Option<solana_address::Address>) -> &mut Self {
        self.stockpile = stockpile;
        self
    }
    /// `[optional account]`
    #[inline(always)]
    pub fn affiliate(&mut self, affiliate: Option<solana_address::Address>) -> &mut Self {
        self.affiliate = affiliate;
        self
    }
    /// `[optional account]`
    #[inline(always)]
    pub fn affiliate_profile(
        &mut self,
        affiliate_profile: Option<solana_address::Address>,
    ) -> &mut Self {
        self.affiliate_profile = affiliate_profile;
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn total_amount(&mut self, total_amount: u64) -> &mut Self {
        self.total_amount = Some(total_amount);
        self
    }
    #[inline(always)]
    pub fn mask_encryption_key(&mut self, mask_encryption_key: [u8; 32]) -> &mut Self {
        self.mask_encryption_key = Some(mask_encryption_key);
        self
    }
    #[inline(always)]
    pub fn mask_nonce(&mut self, mask_nonce: u128) -> &mut Self {
        self.mask_nonce = Some(mask_nonce);
        self
    }
    #[inline(always)]
    pub fn mask_ciphertext(&mut self, mask_ciphertext: [u8; 64]) -> &mut Self {
        self.mask_ciphertext = Some(mask_ciphertext);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_attestation(&mut self, zk_mask_attestation: ZkMaskAttestationArgs) -> &mut Self {
        self.zk_mask_attestation = Some(zk_mask_attestation);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = DeployRound {
            signer: self.signer.expect("signer is not set"),
            round: self.round.expect("round is not set"),
            config: self.config.expect("config is not set"),
            miner: self.miner.expect("miner is not set"),
            player_profile: self.player_profile.expect("player_profile is not set"),
            board: self.board.expect("board is not set"),
            treasury: self.treasury.expect("treasury is not set"),
            stockpile_sol_vault: self
                .stockpile_sol_vault
                .expect("stockpile_sol_vault is not set"),
            buyback_sol_vault: self
                .buyback_sol_vault
                .expect("buyback_sol_vault is not set"),
            stockpile: self.stockpile,
            affiliate: self.affiliate,
            affiliate_profile: self.affiliate_profile,
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = DeployRoundInstructionArgs {
            total_amount: self.total_amount.clone().expect("total_amount is not set"),
            mask_encryption_key: self
                .mask_encryption_key
                .clone()
                .expect("mask_encryption_key is not set"),
            mask_nonce: self.mask_nonce.clone().expect("mask_nonce is not set"),
            mask_ciphertext: self
                .mask_ciphertext
                .clone()
                .expect("mask_ciphertext is not set"),
            zk_mask_attestation: self.zk_mask_attestation.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `deploy_round` CPI accounts.
pub struct DeployRoundCpiAccounts<'a, 'b> {
    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub round: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub miner: &'b solana_account_info::AccountInfo<'a>,
    /// Lifetime deploy profile for the signing player.
    pub player_profile: &'b solana_account_info::AccountInfo<'a>,
    /// Board singleton that tracks the currently enabled round, if any.
    pub board: &'b solana_account_info::AccountInfo<'a>,

    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    pub stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    pub buyback_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Active stockpile account, omitted when no cycle is currently joinable.
    pub stockpile: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub affiliate: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub affiliate_profile: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `deploy_round` CPI instruction.
pub struct DeployRoundCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub round: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub miner: &'b solana_account_info::AccountInfo<'a>,
    /// Lifetime deploy profile for the signing player.
    pub player_profile: &'b solana_account_info::AccountInfo<'a>,
    /// Board singleton that tracks the currently enabled round, if any.
    pub board: &'b solana_account_info::AccountInfo<'a>,

    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    pub stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    pub buyback_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Active stockpile account, omitted when no cycle is currently joinable.
    pub stockpile: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub affiliate: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub affiliate_profile: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: DeployRoundInstructionArgs,
}

impl<'a, 'b> DeployRoundCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: DeployRoundCpiAccounts<'a, 'b>,
        args: DeployRoundInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            round: accounts.round,
            config: accounts.config,
            miner: accounts.miner,
            player_profile: accounts.player_profile,
            board: accounts.board,
            treasury: accounts.treasury,
            stockpile_sol_vault: accounts.stockpile_sol_vault,
            buyback_sol_vault: accounts.buyback_sol_vault,
            stockpile: accounts.stockpile,
            affiliate: accounts.affiliate,
            affiliate_profile: accounts.affiliate_profile,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(13 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(*self.round.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.miner.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.player_profile.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.board.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.treasury.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.stockpile_sol_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.buyback_sol_vault.key,
            false,
        ));
        if let Some(stockpile) = self.stockpile {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                *stockpile.key,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::ZINC_ID,
                false,
            ));
        }
        if let Some(affiliate) = self.affiliate {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                *affiliate.key,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::ZINC_ID,
                false,
            ));
        }
        if let Some(affiliate_profile) = self.affiliate_profile {
            accounts.push(solana_instruction::AccountMeta::new(
                *affiliate_profile.key,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::ZINC_ID,
                false,
            ));
        }
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = DeployRoundInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(14 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.round.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.miner.clone());
        account_infos.push(self.player_profile.clone());
        account_infos.push(self.board.clone());
        account_infos.push(self.treasury.clone());
        account_infos.push(self.stockpile_sol_vault.clone());
        account_infos.push(self.buyback_sol_vault.clone());
        if let Some(stockpile) = self.stockpile {
            account_infos.push(stockpile.clone());
        }
        if let Some(affiliate) = self.affiliate {
            account_infos.push(affiliate.clone());
        }
        if let Some(affiliate_profile) = self.affiliate_profile {
            account_infos.push(affiliate_profile.clone());
        }
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `DeployRound` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` round
///   2. `[]` config
///   3. `[writable]` miner
///   4. `[writable]` player_profile
///   5. `[writable]` board
///   6. `[writable]` treasury
///   7. `[writable]` stockpile_sol_vault
///   8. `[writable]` buyback_sol_vault
///   9. `[optional]` stockpile
///   10. `[optional]` affiliate
///   11. `[writable, optional]` affiliate_profile
///   12. `[]` system_program
#[derive(Clone, Debug)]
pub struct DeployRoundCpiBuilder<'a, 'b> {
    instruction: Box<DeployRoundCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> DeployRoundCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(DeployRoundCpiBuilderInstruction {
            __program: program,
            signer: None,
            round: None,
            config: None,
            miner: None,
            player_profile: None,
            board: None,
            treasury: None,
            stockpile_sol_vault: None,
            buyback_sol_vault: None,
            stockpile: None,
            affiliate: None,
            affiliate_profile: None,
            system_program: None,
            total_amount: None,
            mask_encryption_key: None,
            mask_nonce: None,
            mask_ciphertext: None,
            zk_mask_attestation: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn round(&mut self, round: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.round = Some(round);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn miner(&mut self, miner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.miner = Some(miner);
        self
    }
    /// Lifetime deploy profile for the signing player.
    #[inline(always)]
    pub fn player_profile(
        &mut self,
        player_profile: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.player_profile = Some(player_profile);
        self
    }
    /// Board singleton that tracks the currently enabled round, if any.
    #[inline(always)]
    pub fn board(&mut self, board: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.board = Some(board);
        self
    }
    #[inline(always)]
    pub fn treasury(&mut self, treasury: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.treasury = Some(treasury);
        self
    }
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    #[inline(always)]
    pub fn stockpile_sol_vault(
        &mut self,
        stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stockpile_sol_vault = Some(stockpile_sol_vault);
        self
    }
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    #[inline(always)]
    pub fn buyback_sol_vault(
        &mut self,
        buyback_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.buyback_sol_vault = Some(buyback_sol_vault);
        self
    }
    /// `[optional account]`
    /// Active stockpile account, omitted when no cycle is currently joinable.
    #[inline(always)]
    pub fn stockpile(
        &mut self,
        stockpile: Option<&'b solana_account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.stockpile = stockpile;
        self
    }
    /// `[optional account]`
    #[inline(always)]
    pub fn affiliate(
        &mut self,
        affiliate: Option<&'b solana_account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.affiliate = affiliate;
        self
    }
    /// `[optional account]`
    #[inline(always)]
    pub fn affiliate_profile(
        &mut self,
        affiliate_profile: Option<&'b solana_account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.affiliate_profile = affiliate_profile;
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn total_amount(&mut self, total_amount: u64) -> &mut Self {
        self.instruction.total_amount = Some(total_amount);
        self
    }
    #[inline(always)]
    pub fn mask_encryption_key(&mut self, mask_encryption_key: [u8; 32]) -> &mut Self {
        self.instruction.mask_encryption_key = Some(mask_encryption_key);
        self
    }
    #[inline(always)]
    pub fn mask_nonce(&mut self, mask_nonce: u128) -> &mut Self {
        self.instruction.mask_nonce = Some(mask_nonce);
        self
    }
    #[inline(always)]
    pub fn mask_ciphertext(&mut self, mask_ciphertext: [u8; 64]) -> &mut Self {
        self.instruction.mask_ciphertext = Some(mask_ciphertext);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_attestation(&mut self, zk_mask_attestation: ZkMaskAttestationArgs) -> &mut Self {
        self.instruction.zk_mask_attestation = Some(zk_mask_attestation);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = DeployRoundInstructionArgs {
            total_amount: self
                .instruction
                .total_amount
                .clone()
                .expect("total_amount is not set"),
            mask_encryption_key: self
                .instruction
                .mask_encryption_key
                .clone()
                .expect("mask_encryption_key is not set"),
            mask_nonce: self
                .instruction
                .mask_nonce
                .clone()
                .expect("mask_nonce is not set"),
            mask_ciphertext: self
                .instruction
                .mask_ciphertext
                .clone()
                .expect("mask_ciphertext is not set"),
            zk_mask_attestation: self.instruction.zk_mask_attestation.clone(),
        };
        let instruction = DeployRoundCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            round: self.instruction.round.expect("round is not set"),

            config: self.instruction.config.expect("config is not set"),

            miner: self.instruction.miner.expect("miner is not set"),

            player_profile: self
                .instruction
                .player_profile
                .expect("player_profile is not set"),

            board: self.instruction.board.expect("board is not set"),

            treasury: self.instruction.treasury.expect("treasury is not set"),

            stockpile_sol_vault: self
                .instruction
                .stockpile_sol_vault
                .expect("stockpile_sol_vault is not set"),

            buyback_sol_vault: self
                .instruction
                .buyback_sol_vault
                .expect("buyback_sol_vault is not set"),

            stockpile: self.instruction.stockpile,

            affiliate: self.instruction.affiliate,

            affiliate_profile: self.instruction.affiliate_profile,

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct DeployRoundCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    round: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    miner: Option<&'b solana_account_info::AccountInfo<'a>>,
    player_profile: Option<&'b solana_account_info::AccountInfo<'a>>,
    board: Option<&'b solana_account_info::AccountInfo<'a>>,
    treasury: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile_sol_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    buyback_sol_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile: Option<&'b solana_account_info::AccountInfo<'a>>,
    affiliate: Option<&'b solana_account_info::AccountInfo<'a>>,
    affiliate_profile: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    total_amount: Option<u64>,
    mask_encryption_key: Option<[u8; 32]>,
    mask_nonce: Option<u128>,
    mask_ciphertext: Option<[u8; 64]>,
    zk_mask_attestation: Option<ZkMaskAttestationArgs>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
