//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const FINALIZE_NO_WINNER_ROUND_DISCRIMINATOR: [u8; 8] = [208, 203, 217, 27, 206, 70, 45, 36];

/// Accounts.
#[derive(Debug)]
pub struct FinalizeNoWinnerRound {
    /// Crank authorized to finalize a zero-winner round.
    pub signer: solana_address::Address,
    /// Global config containing the crank authority and treasury address.
    pub config: solana_address::Address,
    /// Board authority source for crank checks.
    pub board: solana_address::Address,
    /// Settled round waiting on zero-winner redirect finalization.
    pub round: solana_address::Address,
    /// Treasury signer and accounting state updated by the redirect.
    pub treasury: solana_address::Address,
    /// Program-owned lamport vault that accumulates stockpile SOL across rounds.
    pub stockpile_sol_vault: solana_address::Address,
    /// Protocol ZINC mint used for the no-winner redirect transfer.
    pub zinc_mint: solana_address::Address,
    /// Round-owned ZINC vault that funds the no-winner redirect.
    pub round_zinc_payout_token_account: solana_address::Address,
    /// Treasury-owned Bonanza vault that receives the 70% redirect share.
    pub bonanza_token_account: solana_address::Address,
    /// Treasury-owned stockpile ZINC vault that receives the 30% redirect share.
    pub stockpile_token_account: solana_address::Address,
    /// SPL Token program used for the direct-winner redirect transfer.
    pub token_program: solana_address::Address,
}

impl FinalizeNoWinnerRound {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(11 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.board, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.round, false));
        accounts.push(solana_instruction::AccountMeta::new(self.treasury, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.stockpile_sol_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.zinc_mint, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.round_zinc_payout_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.bonanza_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.stockpile_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = FinalizeNoWinnerRoundInstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct FinalizeNoWinnerRoundInstructionData {
    discriminator: [u8; 8],
}

impl FinalizeNoWinnerRoundInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [208, 203, 217, 27, 206, 70, 45, 36],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for FinalizeNoWinnerRoundInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `FinalizeNoWinnerRound`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[]` config
///   2. `[]` board
///   3. `[writable]` round
///   4. `[writable]` treasury
///   5. `[writable]` stockpile_sol_vault
///   6. `[writable]` zinc_mint
///   7. `[writable]` round_zinc_payout_token_account
///   8. `[writable]` bonanza_token_account
///   9. `[writable]` stockpile_token_account
///   10. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
#[derive(Clone, Debug, Default)]
pub struct FinalizeNoWinnerRoundBuilder {
    signer: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    board: Option<solana_address::Address>,
    round: Option<solana_address::Address>,
    treasury: Option<solana_address::Address>,
    stockpile_sol_vault: Option<solana_address::Address>,
    zinc_mint: Option<solana_address::Address>,
    round_zinc_payout_token_account: Option<solana_address::Address>,
    bonanza_token_account: Option<solana_address::Address>,
    stockpile_token_account: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl FinalizeNoWinnerRoundBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Crank authorized to finalize a zero-winner round.
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_address::Address) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    /// Global config containing the crank authority and treasury address.
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// Board authority source for crank checks.
    #[inline(always)]
    pub fn board(&mut self, board: solana_address::Address) -> &mut Self {
        self.board = Some(board);
        self
    }
    /// Settled round waiting on zero-winner redirect finalization.
    #[inline(always)]
    pub fn round(&mut self, round: solana_address::Address) -> &mut Self {
        self.round = Some(round);
        self
    }
    /// Treasury signer and accounting state updated by the redirect.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: solana_address::Address) -> &mut Self {
        self.treasury = Some(treasury);
        self
    }
    /// Program-owned lamport vault that accumulates stockpile SOL across rounds.
    #[inline(always)]
    pub fn stockpile_sol_vault(
        &mut self,
        stockpile_sol_vault: solana_address::Address,
    ) -> &mut Self {
        self.stockpile_sol_vault = Some(stockpile_sol_vault);
        self
    }
    /// Protocol ZINC mint used for the no-winner redirect transfer.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: solana_address::Address) -> &mut Self {
        self.zinc_mint = Some(zinc_mint);
        self
    }
    /// Round-owned ZINC vault that funds the no-winner redirect.
    #[inline(always)]
    pub fn round_zinc_payout_token_account(
        &mut self,
        round_zinc_payout_token_account: solana_address::Address,
    ) -> &mut Self {
        self.round_zinc_payout_token_account = Some(round_zinc_payout_token_account);
        self
    }
    /// Treasury-owned Bonanza vault that receives the 70% redirect share.
    #[inline(always)]
    pub fn bonanza_token_account(
        &mut self,
        bonanza_token_account: solana_address::Address,
    ) -> &mut Self {
        self.bonanza_token_account = Some(bonanza_token_account);
        self
    }
    /// Treasury-owned stockpile ZINC vault that receives the 30% redirect share.
    #[inline(always)]
    pub fn stockpile_token_account(
        &mut self,
        stockpile_token_account: solana_address::Address,
    ) -> &mut Self {
        self.stockpile_token_account = Some(stockpile_token_account);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    /// SPL Token program used for the direct-winner redirect transfer.
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = FinalizeNoWinnerRound {
            signer: self.signer.expect("signer is not set"),
            config: self.config.expect("config is not set"),
            board: self.board.expect("board is not set"),
            round: self.round.expect("round is not set"),
            treasury: self.treasury.expect("treasury is not set"),
            stockpile_sol_vault: self
                .stockpile_sol_vault
                .expect("stockpile_sol_vault is not set"),
            zinc_mint: self.zinc_mint.expect("zinc_mint is not set"),
            round_zinc_payout_token_account: self
                .round_zinc_payout_token_account
                .expect("round_zinc_payout_token_account is not set"),
            bonanza_token_account: self
                .bonanza_token_account
                .expect("bonanza_token_account is not set"),
            stockpile_token_account: self
                .stockpile_token_account
                .expect("stockpile_token_account is not set"),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `finalize_no_winner_round` CPI accounts.
pub struct FinalizeNoWinnerRoundCpiAccounts<'a, 'b> {
    /// Crank authorized to finalize a zero-winner round.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority and treasury address.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Board authority source for crank checks.
    pub board: &'b solana_account_info::AccountInfo<'a>,
    /// Settled round waiting on zero-winner redirect finalization.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury signer and accounting state updated by the redirect.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates stockpile SOL across rounds.
    pub stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used for the no-winner redirect transfer.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Round-owned ZINC vault that funds the no-winner redirect.
    pub round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned Bonanza vault that receives the 70% redirect share.
    pub bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned stockpile ZINC vault that receives the 30% redirect share.
    pub stockpile_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token program used for the direct-winner redirect transfer.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `finalize_no_winner_round` CPI instruction.
pub struct FinalizeNoWinnerRoundCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Crank authorized to finalize a zero-winner round.
    pub signer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority and treasury address.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Board authority source for crank checks.
    pub board: &'b solana_account_info::AccountInfo<'a>,
    /// Settled round waiting on zero-winner redirect finalization.
    pub round: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury signer and accounting state updated by the redirect.
    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates stockpile SOL across rounds.
    pub stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol ZINC mint used for the no-winner redirect transfer.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Round-owned ZINC vault that funds the no-winner redirect.
    pub round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned Bonanza vault that receives the 70% redirect share.
    pub bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned stockpile ZINC vault that receives the 30% redirect share.
    pub stockpile_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token program used for the direct-winner redirect transfer.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> FinalizeNoWinnerRoundCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: FinalizeNoWinnerRoundCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            config: accounts.config,
            board: accounts.board,
            round: accounts.round,
            treasury: accounts.treasury,
            stockpile_sol_vault: accounts.stockpile_sol_vault,
            zinc_mint: accounts.zinc_mint,
            round_zinc_payout_token_account: accounts.round_zinc_payout_token_account,
            bonanza_token_account: accounts.bonanza_token_account,
            stockpile_token_account: accounts.stockpile_token_account,
            token_program: accounts.token_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(11 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.board.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.round.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.treasury.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.stockpile_sol_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.zinc_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.round_zinc_payout_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.bonanza_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.stockpile_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = FinalizeNoWinnerRoundInstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(12 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.board.clone());
        account_infos.push(self.round.clone());
        account_infos.push(self.treasury.clone());
        account_infos.push(self.stockpile_sol_vault.clone());
        account_infos.push(self.zinc_mint.clone());
        account_infos.push(self.round_zinc_payout_token_account.clone());
        account_infos.push(self.bonanza_token_account.clone());
        account_infos.push(self.stockpile_token_account.clone());
        account_infos.push(self.token_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `FinalizeNoWinnerRound` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[]` config
///   2. `[]` board
///   3. `[writable]` round
///   4. `[writable]` treasury
///   5. `[writable]` stockpile_sol_vault
///   6. `[writable]` zinc_mint
///   7. `[writable]` round_zinc_payout_token_account
///   8. `[writable]` bonanza_token_account
///   9. `[writable]` stockpile_token_account
///   10. `[]` token_program
#[derive(Clone, Debug)]
pub struct FinalizeNoWinnerRoundCpiBuilder<'a, 'b> {
    instruction: Box<FinalizeNoWinnerRoundCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> FinalizeNoWinnerRoundCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(FinalizeNoWinnerRoundCpiBuilderInstruction {
            __program: program,
            signer: None,
            config: None,
            board: None,
            round: None,
            treasury: None,
            stockpile_sol_vault: None,
            zinc_mint: None,
            round_zinc_payout_token_account: None,
            bonanza_token_account: None,
            stockpile_token_account: None,
            token_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Crank authorized to finalize a zero-winner round.
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    /// Global config containing the crank authority and treasury address.
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    /// Board authority source for crank checks.
    #[inline(always)]
    pub fn board(&mut self, board: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.board = Some(board);
        self
    }
    /// Settled round waiting on zero-winner redirect finalization.
    #[inline(always)]
    pub fn round(&mut self, round: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.round = Some(round);
        self
    }
    /// Treasury signer and accounting state updated by the redirect.
    #[inline(always)]
    pub fn treasury(&mut self, treasury: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.treasury = Some(treasury);
        self
    }
    /// Program-owned lamport vault that accumulates stockpile SOL across rounds.
    #[inline(always)]
    pub fn stockpile_sol_vault(
        &mut self,
        stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stockpile_sol_vault = Some(stockpile_sol_vault);
        self
    }
    /// Protocol ZINC mint used for the no-winner redirect transfer.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.zinc_mint = Some(zinc_mint);
        self
    }
    /// Round-owned ZINC vault that funds the no-winner redirect.
    #[inline(always)]
    pub fn round_zinc_payout_token_account(
        &mut self,
        round_zinc_payout_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.round_zinc_payout_token_account = Some(round_zinc_payout_token_account);
        self
    }
    /// Treasury-owned Bonanza vault that receives the 70% redirect share.
    #[inline(always)]
    pub fn bonanza_token_account(
        &mut self,
        bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.bonanza_token_account = Some(bonanza_token_account);
        self
    }
    /// Treasury-owned stockpile ZINC vault that receives the 30% redirect share.
    #[inline(always)]
    pub fn stockpile_token_account(
        &mut self,
        stockpile_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stockpile_token_account = Some(stockpile_token_account);
        self
    }
    /// SPL Token program used for the direct-winner redirect transfer.
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = FinalizeNoWinnerRoundCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            config: self.instruction.config.expect("config is not set"),

            board: self.instruction.board.expect("board is not set"),

            round: self.instruction.round.expect("round is not set"),

            treasury: self.instruction.treasury.expect("treasury is not set"),

            stockpile_sol_vault: self
                .instruction
                .stockpile_sol_vault
                .expect("stockpile_sol_vault is not set"),

            zinc_mint: self.instruction.zinc_mint.expect("zinc_mint is not set"),

            round_zinc_payout_token_account: self
                .instruction
                .round_zinc_payout_token_account
                .expect("round_zinc_payout_token_account is not set"),

            bonanza_token_account: self
                .instruction
                .bonanza_token_account
                .expect("bonanza_token_account is not set"),

            stockpile_token_account: self
                .instruction
                .stockpile_token_account
                .expect("stockpile_token_account is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct FinalizeNoWinnerRoundCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    board: Option<&'b solana_account_info::AccountInfo<'a>>,
    round: Option<&'b solana_account_info::AccountInfo<'a>>,
    treasury: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile_sol_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    zinc_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    round_zinc_payout_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    bonanza_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
