//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const INIT_STOCKPILE_WINNERS_DISCRIMINATOR: [u8; 8] = [174, 106, 84, 155, 219, 146, 37, 247];

/// Accounts.
#[derive(Debug)]
pub struct InitStockpileWinners {
    /// Crank payer that funds ranked winner storage.
    pub payer: solana_address::Address,
    /// Global config containing the crank authority.
    pub config: solana_address::Address,
    /// Board authority source and unresolved stockpile pointer.
    pub board: solana_address::Address,
    /// Stockpile cycle that will own the ranked winners account.
    pub stockpile: solana_address::Address,
    /// Ranked winner storage for the stockpile cycle.
    pub stockpile_winners: solana_address::Address,
    /// System program used to allocate the ranked winners account.
    pub system_program: solana_address::Address,
}

impl InitStockpileWinners {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.board, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.stockpile,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.stockpile_winners,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = InitStockpileWinnersInstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitStockpileWinnersInstructionData {
    discriminator: [u8; 8],
}

impl InitStockpileWinnersInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [174, 106, 84, 155, 219, 146, 37, 247],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for InitStockpileWinnersInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `InitStockpileWinners`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[]` config
///   2. `[]` board
///   3. `[]` stockpile
///   4. `[writable]` stockpile_winners
///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct InitStockpileWinnersBuilder {
    payer: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    board: Option<solana_address::Address>,
    stockpile: Option<solana_address::Address>,
    stockpile_winners: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitStockpileWinnersBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Crank payer that funds ranked winner storage.
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// Global config containing the crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// Board authority source and unresolved stockpile pointer.
    #[inline(always)]
    pub fn board(&mut self, board: solana_address::Address) -> &mut Self {
        self.board = Some(board);
        self
    }
    /// Stockpile cycle that will own the ranked winners account.
    #[inline(always)]
    pub fn stockpile(&mut self, stockpile: solana_address::Address) -> &mut Self {
        self.stockpile = Some(stockpile);
        self
    }
    /// Ranked winner storage for the stockpile cycle.
    #[inline(always)]
    pub fn stockpile_winners(&mut self, stockpile_winners: solana_address::Address) -> &mut Self {
        self.stockpile_winners = Some(stockpile_winners);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// System program used to allocate the ranked winners account.
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = InitStockpileWinners {
            payer: self.payer.expect("payer is not set"),
            config: self.config.expect("config is not set"),
            board: self.board.expect("board is not set"),
            stockpile: self.stockpile.expect("stockpile is not set"),
            stockpile_winners: self
                .stockpile_winners
                .expect("stockpile_winners is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `init_stockpile_winners` CPI accounts.
pub struct InitStockpileWinnersCpiAccounts<'a, 'b> {
    /// Crank payer that funds ranked winner storage.
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Board authority source and unresolved stockpile pointer.
    pub board: &'b solana_account_info::AccountInfo<'a>,
    /// Stockpile cycle that will own the ranked winners account.
    pub stockpile: &'b solana_account_info::AccountInfo<'a>,
    /// Ranked winner storage for the stockpile cycle.
    pub stockpile_winners: &'b solana_account_info::AccountInfo<'a>,
    /// System program used to allocate the ranked winners account.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `init_stockpile_winners` CPI instruction.
pub struct InitStockpileWinnersCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Crank payer that funds ranked winner storage.
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Board authority source and unresolved stockpile pointer.
    pub board: &'b solana_account_info::AccountInfo<'a>,
    /// Stockpile cycle that will own the ranked winners account.
    pub stockpile: &'b solana_account_info::AccountInfo<'a>,
    /// Ranked winner storage for the stockpile cycle.
    pub stockpile_winners: &'b solana_account_info::AccountInfo<'a>,
    /// System program used to allocate the ranked winners account.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> InitStockpileWinnersCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: InitStockpileWinnersCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            payer: accounts.payer,
            config: accounts.config,
            board: accounts.board,
            stockpile: accounts.stockpile,
            stockpile_winners: accounts.stockpile_winners,
            system_program: accounts.system_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.board.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.stockpile.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.stockpile_winners.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = InitStockpileWinnersInstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.board.clone());
        account_infos.push(self.stockpile.clone());
        account_infos.push(self.stockpile_winners.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `InitStockpileWinners` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[]` config
///   2. `[]` board
///   3. `[]` stockpile
///   4. `[writable]` stockpile_winners
///   5. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitStockpileWinnersCpiBuilder<'a, 'b> {
    instruction: Box<InitStockpileWinnersCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitStockpileWinnersCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(InitStockpileWinnersCpiBuilderInstruction {
            __program: program,
            payer: None,
            config: None,
            board: None,
            stockpile: None,
            stockpile_winners: None,
            system_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Crank payer that funds ranked winner storage.
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    /// Global config containing the crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    /// Board authority source and unresolved stockpile pointer.
    #[inline(always)]
    pub fn board(&mut self, board: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.board = Some(board);
        self
    }
    /// Stockpile cycle that will own the ranked winners account.
    #[inline(always)]
    pub fn stockpile(&mut self, stockpile: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.stockpile = Some(stockpile);
        self
    }
    /// Ranked winner storage for the stockpile cycle.
    #[inline(always)]
    pub fn stockpile_winners(
        &mut self,
        stockpile_winners: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stockpile_winners = Some(stockpile_winners);
        self
    }
    /// System program used to allocate the ranked winners account.
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = InitStockpileWinnersCpi {
            __program: self.instruction.__program,

            payer: self.instruction.payer.expect("payer is not set"),

            config: self.instruction.config.expect("config is not set"),

            board: self.instruction.board.expect("board is not set"),

            stockpile: self.instruction.stockpile.expect("stockpile is not set"),

            stockpile_winners: self
                .instruction
                .stockpile_winners
                .expect("stockpile_winners is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct InitStockpileWinnersCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    board: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile_winners: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
