//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::InitCompDefArgs;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const INIT_STOCKPILE_RAND_COMP_DEF_DISCRIMINATOR: [u8; 8] =
    [125, 176, 101, 247, 237, 176, 50, 211];

/// Accounts.
#[derive(Debug)]
pub struct InitStockpileRandCompDef {
    /// Pays for the computation-definition account initialization.
    pub payer: solana_address::Address,
    /// Global config containing the crank authority.
    pub config: solana_address::Address,
    /// MXE account for this program's encrypted circuits.
    pub mxe_account: solana_address::Address,

    pub comp_def_account: solana_address::Address,

    pub address_lookup_table: solana_address::Address,

    pub lut_program: solana_address::Address,

    pub arcium_program: solana_address::Address,

    pub system_program: solana_address::Address,
}

impl InitStockpileRandCompDef {
    pub fn instruction(
        &self,
        args: InitStockpileRandCompDefInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: InitStockpileRandCompDefInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(8 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.mxe_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.comp_def_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.address_lookup_table,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.lut_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.arcium_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = InitStockpileRandCompDefInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitStockpileRandCompDefInstructionData {
    discriminator: [u8; 8],
}

impl InitStockpileRandCompDefInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [125, 176, 101, 247, 237, 176, 50, 211],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for InitStockpileRandCompDefInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitStockpileRandCompDefInstructionArgs {
    pub args: InitCompDefArgs,
}

impl InitStockpileRandCompDefInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `InitStockpileRandCompDef`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[]` config
///   2. `[writable]` mxe_account
///   3. `[writable]` comp_def_account
///   4. `[writable]` address_lookup_table
///   5. `[optional]` lut_program (default to `AddressLookupTab1e1111111111111111111111111`)
///   6. `[optional]` arcium_program (default to `Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ`)
///   7. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct InitStockpileRandCompDefBuilder {
    payer: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    mxe_account: Option<solana_address::Address>,
    comp_def_account: Option<solana_address::Address>,
    address_lookup_table: Option<solana_address::Address>,
    lut_program: Option<solana_address::Address>,
    arcium_program: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    args: Option<InitCompDefArgs>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitStockpileRandCompDefBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Pays for the computation-definition account initialization.
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// Global config containing the crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// MXE account for this program's encrypted circuits.
    #[inline(always)]
    pub fn mxe_account(&mut self, mxe_account: solana_address::Address) -> &mut Self {
        self.mxe_account = Some(mxe_account);
        self
    }
    #[inline(always)]
    pub fn comp_def_account(&mut self, comp_def_account: solana_address::Address) -> &mut Self {
        self.comp_def_account = Some(comp_def_account);
        self
    }
    #[inline(always)]
    pub fn address_lookup_table(
        &mut self,
        address_lookup_table: solana_address::Address,
    ) -> &mut Self {
        self.address_lookup_table = Some(address_lookup_table);
        self
    }
    /// `[optional account, default to 'AddressLookupTab1e1111111111111111111111111']`
    #[inline(always)]
    pub fn lut_program(&mut self, lut_program: solana_address::Address) -> &mut Self {
        self.lut_program = Some(lut_program);
        self
    }
    /// `[optional account, default to 'Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ']`
    #[inline(always)]
    pub fn arcium_program(&mut self, arcium_program: solana_address::Address) -> &mut Self {
        self.arcium_program = Some(arcium_program);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn args(&mut self, args: InitCompDefArgs) -> &mut Self {
        self.args = Some(args);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = InitStockpileRandCompDef {
            payer: self.payer.expect("payer is not set"),
            config: self.config.expect("config is not set"),
            mxe_account: self.mxe_account.expect("mxe_account is not set"),
            comp_def_account: self.comp_def_account.expect("comp_def_account is not set"),
            address_lookup_table: self
                .address_lookup_table
                .expect("address_lookup_table is not set"),
            lut_program: self.lut_program.unwrap_or(solana_address::address!(
                "AddressLookupTab1e1111111111111111111111111"
            )),
            arcium_program: self.arcium_program.unwrap_or(solana_address::address!(
                "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = InitStockpileRandCompDefInstructionArgs {
            args: self.args.clone().expect("args is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `init_stockpile_rand_comp_def` CPI accounts.
pub struct InitStockpileRandCompDefCpiAccounts<'a, 'b> {
    /// Pays for the computation-definition account initialization.
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// MXE account for this program's encrypted circuits.
    pub mxe_account: &'b solana_account_info::AccountInfo<'a>,

    pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,

    pub address_lookup_table: &'b solana_account_info::AccountInfo<'a>,

    pub lut_program: &'b solana_account_info::AccountInfo<'a>,

    pub arcium_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `init_stockpile_rand_comp_def` CPI instruction.
pub struct InitStockpileRandCompDefCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Pays for the computation-definition account initialization.
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Global config containing the crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// MXE account for this program's encrypted circuits.
    pub mxe_account: &'b solana_account_info::AccountInfo<'a>,

    pub comp_def_account: &'b solana_account_info::AccountInfo<'a>,

    pub address_lookup_table: &'b solana_account_info::AccountInfo<'a>,

    pub lut_program: &'b solana_account_info::AccountInfo<'a>,

    pub arcium_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: InitStockpileRandCompDefInstructionArgs,
}

impl<'a, 'b> InitStockpileRandCompDefCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: InitStockpileRandCompDefCpiAccounts<'a, 'b>,
        args: InitStockpileRandCompDefInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            payer: accounts.payer,
            config: accounts.config,
            mxe_account: accounts.mxe_account,
            comp_def_account: accounts.comp_def_account,
            address_lookup_table: accounts.address_lookup_table,
            lut_program: accounts.lut_program,
            arcium_program: accounts.arcium_program,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(8 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.mxe_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.comp_def_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.address_lookup_table.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.lut_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.arcium_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = InitStockpileRandCompDefInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(9 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.mxe_account.clone());
        account_infos.push(self.comp_def_account.clone());
        account_infos.push(self.address_lookup_table.clone());
        account_infos.push(self.lut_program.clone());
        account_infos.push(self.arcium_program.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `InitStockpileRandCompDef` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[]` config
///   2. `[writable]` mxe_account
///   3. `[writable]` comp_def_account
///   4. `[writable]` address_lookup_table
///   5. `[]` lut_program
///   6. `[]` arcium_program
///   7. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitStockpileRandCompDefCpiBuilder<'a, 'b> {
    instruction: Box<InitStockpileRandCompDefCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitStockpileRandCompDefCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(InitStockpileRandCompDefCpiBuilderInstruction {
            __program: program,
            payer: None,
            config: None,
            mxe_account: None,
            comp_def_account: None,
            address_lookup_table: None,
            lut_program: None,
            arcium_program: None,
            system_program: None,
            args: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Pays for the computation-definition account initialization.
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    /// Global config containing the crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    /// MXE account for this program's encrypted circuits.
    #[inline(always)]
    pub fn mxe_account(
        &mut self,
        mxe_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.mxe_account = Some(mxe_account);
        self
    }
    #[inline(always)]
    pub fn comp_def_account(
        &mut self,
        comp_def_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.comp_def_account = Some(comp_def_account);
        self
    }
    #[inline(always)]
    pub fn address_lookup_table(
        &mut self,
        address_lookup_table: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.address_lookup_table = Some(address_lookup_table);
        self
    }
    #[inline(always)]
    pub fn lut_program(
        &mut self,
        lut_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.lut_program = Some(lut_program);
        self
    }
    #[inline(always)]
    pub fn arcium_program(
        &mut self,
        arcium_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.arcium_program = Some(arcium_program);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn args(&mut self, args: InitCompDefArgs) -> &mut Self {
        self.instruction.args = Some(args);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = InitStockpileRandCompDefInstructionArgs {
            args: self.instruction.args.clone().expect("args is not set"),
        };
        let instruction = InitStockpileRandCompDefCpi {
            __program: self.instruction.__program,

            payer: self.instruction.payer.expect("payer is not set"),

            config: self.instruction.config.expect("config is not set"),

            mxe_account: self
                .instruction
                .mxe_account
                .expect("mxe_account is not set"),

            comp_def_account: self
                .instruction
                .comp_def_account
                .expect("comp_def_account is not set"),

            address_lookup_table: self
                .instruction
                .address_lookup_table
                .expect("address_lookup_table is not set"),

            lut_program: self
                .instruction
                .lut_program
                .expect("lut_program is not set"),

            arcium_program: self
                .instruction
                .arcium_program
                .expect("arcium_program is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct InitStockpileRandCompDefCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    mxe_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    comp_def_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    address_lookup_table: Option<&'b solana_account_info::AccountInfo<'a>>,
    lut_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    arcium_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    args: Option<InitCompDefArgs>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
