//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::ZincMintMetadataArgs;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const INIT_CONFIG_DISCRIMINATOR: [u8; 8] = [23, 235, 115, 232, 168, 96, 1, 231];

/// Accounts.
#[derive(Debug)]
pub struct InitConfig {
    pub admin: solana_address::Address,

    pub crank: solana_address::Address,

    pub config: solana_address::Address,

    pub treasury: solana_address::Address,
    /// Newly created classic SPL mint for ZINC rewards.
    pub zinc_mint: solana_address::Address,

    pub zinc_metadata: solana_address::Address,
    /// Treasury ATA that holds curve-admin ZINC inventory outside the Bonanza pot.
    pub curve_admin_token_account: solana_address::Address,
    /// Treasury-owned Bonanza vault that holds rolling Bonanza ZINC.
    pub bonanza_token_account: solana_address::Address,
    /// Dedicated stockpile vault that holds stockpile ZINC separately from Bonanza accrual.
    pub stockpile_token_account: solana_address::Address,
    /// Dedicated staking vault that escrows staked ZINC balances.
    pub staking_token_account: solana_address::Address,
    /// Dedicated reward vault that funds staker-yield claims.
    pub staking_reward_token_account: solana_address::Address,
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    pub stockpile_sol_vault: solana_address::Address,
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    pub buyback_sol_vault: solana_address::Address,
    /// Singleton account that tracks pending stockpile extras for the current cycle.
    pub stockpile_extras: solana_address::Address,
    /// Associated Token Program used to create the treasury ATA.
    pub associated_token_program: solana_address::Address,
    /// SPL Token Program that owns the ZINC mint and treasury vaults.
    pub token_program: solana_address::Address,
    /// Metaplex Token Metadata Program used to create ZINC mint metadata.
    pub metadata_program: solana_address::Address,
    /// Rent sysvar forwarded to the Metaplex metadata CPI.
    pub rent: solana_address::Address,
    /// System Program used to allocate protocol and metadata accounts.
    pub system_program: solana_address::Address,
}

impl InitConfig {
    pub fn instruction(&self, args: InitConfigInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: InitConfigInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(19 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.admin, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.crank, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.config, false));
        accounts.push(solana_instruction::AccountMeta::new(self.treasury, false));
        accounts.push(solana_instruction::AccountMeta::new(self.zinc_mint, true));
        accounts.push(solana_instruction::AccountMeta::new(
            self.zinc_metadata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.curve_admin_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.bonanza_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.stockpile_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.staking_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.staking_reward_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.stockpile_sol_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.buyback_sol_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.stockpile_extras,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.metadata_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.rent, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = InitConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitConfigInstructionData {
    discriminator: [u8; 8],
}

impl InitConfigInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [23, 235, 115, 232, 168, 96, 1, 231],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for InitConfigInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct InitConfigInstructionArgs {
    pub args: ZincMintMetadataArgs,
}

impl InitConfigInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `InitConfig`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[]` crank
///   2. `[writable]` config
///   3. `[writable]` treasury
///   4. `[writable, signer]` zinc_mint
///   5. `[writable]` zinc_metadata
///   6. `[writable]` curve_admin_token_account
///   7. `[writable]` bonanza_token_account
///   8. `[writable]` stockpile_token_account
///   9. `[writable]` staking_token_account
///   10. `[writable]` staking_reward_token_account
///   11. `[writable]` stockpile_sol_vault
///   12. `[writable]` buyback_sol_vault
///   13. `[writable]` stockpile_extras
///   14. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
///   15. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   16. `[optional]` metadata_program (default to `metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s`)
///   17. `[optional]` rent (default to `SysvarRent111111111111111111111111111111111`)
///   18. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct InitConfigBuilder {
    admin: Option<solana_address::Address>,
    crank: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    treasury: Option<solana_address::Address>,
    zinc_mint: Option<solana_address::Address>,
    zinc_metadata: Option<solana_address::Address>,
    curve_admin_token_account: Option<solana_address::Address>,
    bonanza_token_account: Option<solana_address::Address>,
    stockpile_token_account: Option<solana_address::Address>,
    staking_token_account: Option<solana_address::Address>,
    staking_reward_token_account: Option<solana_address::Address>,
    stockpile_sol_vault: Option<solana_address::Address>,
    buyback_sol_vault: Option<solana_address::Address>,
    stockpile_extras: Option<solana_address::Address>,
    associated_token_program: Option<solana_address::Address>,
    token_program: Option<solana_address::Address>,
    metadata_program: Option<solana_address::Address>,
    rent: Option<solana_address::Address>,
    system_program: Option<solana_address::Address>,
    args: Option<ZincMintMetadataArgs>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitConfigBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_address::Address) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn crank(&mut self, crank: solana_address::Address) -> &mut Self {
        self.crank = Some(crank);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn treasury(&mut self, treasury: solana_address::Address) -> &mut Self {
        self.treasury = Some(treasury);
        self
    }
    /// Newly created classic SPL mint for ZINC rewards.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: solana_address::Address) -> &mut Self {
        self.zinc_mint = Some(zinc_mint);
        self
    }
    #[inline(always)]
    pub fn zinc_metadata(&mut self, zinc_metadata: solana_address::Address) -> &mut Self {
        self.zinc_metadata = Some(zinc_metadata);
        self
    }
    /// Treasury ATA that holds curve-admin ZINC inventory outside the Bonanza pot.
    #[inline(always)]
    pub fn curve_admin_token_account(
        &mut self,
        curve_admin_token_account: solana_address::Address,
    ) -> &mut Self {
        self.curve_admin_token_account = Some(curve_admin_token_account);
        self
    }
    /// Treasury-owned Bonanza vault that holds rolling Bonanza ZINC.
    #[inline(always)]
    pub fn bonanza_token_account(
        &mut self,
        bonanza_token_account: solana_address::Address,
    ) -> &mut Self {
        self.bonanza_token_account = Some(bonanza_token_account);
        self
    }
    /// Dedicated stockpile vault that holds stockpile ZINC separately from Bonanza accrual.
    #[inline(always)]
    pub fn stockpile_token_account(
        &mut self,
        stockpile_token_account: solana_address::Address,
    ) -> &mut Self {
        self.stockpile_token_account = Some(stockpile_token_account);
        self
    }
    /// Dedicated staking vault that escrows staked ZINC balances.
    #[inline(always)]
    pub fn staking_token_account(
        &mut self,
        staking_token_account: solana_address::Address,
    ) -> &mut Self {
        self.staking_token_account = Some(staking_token_account);
        self
    }
    /// Dedicated reward vault that funds staker-yield claims.
    #[inline(always)]
    pub fn staking_reward_token_account(
        &mut self,
        staking_reward_token_account: solana_address::Address,
    ) -> &mut Self {
        self.staking_reward_token_account = Some(staking_reward_token_account);
        self
    }
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    #[inline(always)]
    pub fn stockpile_sol_vault(
        &mut self,
        stockpile_sol_vault: solana_address::Address,
    ) -> &mut Self {
        self.stockpile_sol_vault = Some(stockpile_sol_vault);
        self
    }
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    #[inline(always)]
    pub fn buyback_sol_vault(&mut self, buyback_sol_vault: solana_address::Address) -> &mut Self {
        self.buyback_sol_vault = Some(buyback_sol_vault);
        self
    }
    /// Singleton account that tracks pending stockpile extras for the current cycle.
    #[inline(always)]
    pub fn stockpile_extras(&mut self, stockpile_extras: solana_address::Address) -> &mut Self {
        self.stockpile_extras = Some(stockpile_extras);
        self
    }
    /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
    /// Associated Token Program used to create the treasury ATA.
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: solana_address::Address,
    ) -> &mut Self {
        self.associated_token_program = Some(associated_token_program);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    /// SPL Token Program that owns the ZINC mint and treasury vaults.
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_address::Address) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// `[optional account, default to 'metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s']`
    /// Metaplex Token Metadata Program used to create ZINC mint metadata.
    #[inline(always)]
    pub fn metadata_program(&mut self, metadata_program: solana_address::Address) -> &mut Self {
        self.metadata_program = Some(metadata_program);
        self
    }
    /// `[optional account, default to 'SysvarRent111111111111111111111111111111111']`
    /// Rent sysvar forwarded to the Metaplex metadata CPI.
    #[inline(always)]
    pub fn rent(&mut self, rent: solana_address::Address) -> &mut Self {
        self.rent = Some(rent);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// System Program used to allocate protocol and metadata accounts.
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn args(&mut self, args: ZincMintMetadataArgs) -> &mut Self {
        self.args = Some(args);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = InitConfig {
            admin: self.admin.expect("admin is not set"),
            crank: self.crank.expect("crank is not set"),
            config: self.config.expect("config is not set"),
            treasury: self.treasury.expect("treasury is not set"),
            zinc_mint: self.zinc_mint.expect("zinc_mint is not set"),
            zinc_metadata: self.zinc_metadata.expect("zinc_metadata is not set"),
            curve_admin_token_account: self
                .curve_admin_token_account
                .expect("curve_admin_token_account is not set"),
            bonanza_token_account: self
                .bonanza_token_account
                .expect("bonanza_token_account is not set"),
            stockpile_token_account: self
                .stockpile_token_account
                .expect("stockpile_token_account is not set"),
            staking_token_account: self
                .staking_token_account
                .expect("staking_token_account is not set"),
            staking_reward_token_account: self
                .staking_reward_token_account
                .expect("staking_reward_token_account is not set"),
            stockpile_sol_vault: self
                .stockpile_sol_vault
                .expect("stockpile_sol_vault is not set"),
            buyback_sol_vault: self
                .buyback_sol_vault
                .expect("buyback_sol_vault is not set"),
            stockpile_extras: self.stockpile_extras.expect("stockpile_extras is not set"),
            associated_token_program: self.associated_token_program.unwrap_or(
                solana_address::address!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
            ),
            token_program: self.token_program.unwrap_or(solana_address::address!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            metadata_program: self.metadata_program.unwrap_or(solana_address::address!(
                "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
            )),
            rent: self.rent.unwrap_or(solana_address::address!(
                "SysvarRent111111111111111111111111111111111"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_address::address!("11111111111111111111111111111111")),
        };
        let args = InitConfigInstructionArgs {
            args: self.args.clone().expect("args is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `init_config` CPI accounts.
pub struct InitConfigCpiAccounts<'a, 'b> {
    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub crank: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Newly created classic SPL mint for ZINC rewards.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,

    pub zinc_metadata: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury ATA that holds curve-admin ZINC inventory outside the Bonanza pot.
    pub curve_admin_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned Bonanza vault that holds rolling Bonanza ZINC.
    pub bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Dedicated stockpile vault that holds stockpile ZINC separately from Bonanza accrual.
    pub stockpile_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Dedicated staking vault that escrows staked ZINC balances.
    pub staking_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Dedicated reward vault that funds staker-yield claims.
    pub staking_reward_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    pub stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    pub buyback_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Singleton account that tracks pending stockpile extras for the current cycle.
    pub stockpile_extras: &'b solana_account_info::AccountInfo<'a>,
    /// Associated Token Program used to create the treasury ATA.
    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token Program that owns the ZINC mint and treasury vaults.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Metaplex Token Metadata Program used to create ZINC mint metadata.
    pub metadata_program: &'b solana_account_info::AccountInfo<'a>,
    /// Rent sysvar forwarded to the Metaplex metadata CPI.
    pub rent: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used to allocate protocol and metadata accounts.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `init_config` CPI instruction.
pub struct InitConfigCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub crank: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub treasury: &'b solana_account_info::AccountInfo<'a>,
    /// Newly created classic SPL mint for ZINC rewards.
    pub zinc_mint: &'b solana_account_info::AccountInfo<'a>,

    pub zinc_metadata: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury ATA that holds curve-admin ZINC inventory outside the Bonanza pot.
    pub curve_admin_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Treasury-owned Bonanza vault that holds rolling Bonanza ZINC.
    pub bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Dedicated stockpile vault that holds stockpile ZINC separately from Bonanza accrual.
    pub stockpile_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Dedicated staking vault that escrows staked ZINC balances.
    pub staking_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Dedicated reward vault that funds staker-yield claims.
    pub staking_reward_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    pub stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    pub buyback_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Singleton account that tracks pending stockpile extras for the current cycle.
    pub stockpile_extras: &'b solana_account_info::AccountInfo<'a>,
    /// Associated Token Program used to create the treasury ATA.
    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// SPL Token Program that owns the ZINC mint and treasury vaults.
    pub token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Metaplex Token Metadata Program used to create ZINC mint metadata.
    pub metadata_program: &'b solana_account_info::AccountInfo<'a>,
    /// Rent sysvar forwarded to the Metaplex metadata CPI.
    pub rent: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used to allocate protocol and metadata accounts.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: InitConfigInstructionArgs,
}

impl<'a, 'b> InitConfigCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: InitConfigCpiAccounts<'a, 'b>,
        args: InitConfigInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            crank: accounts.crank,
            config: accounts.config,
            treasury: accounts.treasury,
            zinc_mint: accounts.zinc_mint,
            zinc_metadata: accounts.zinc_metadata,
            curve_admin_token_account: accounts.curve_admin_token_account,
            bonanza_token_account: accounts.bonanza_token_account,
            stockpile_token_account: accounts.stockpile_token_account,
            staking_token_account: accounts.staking_token_account,
            staking_reward_token_account: accounts.staking_reward_token_account,
            stockpile_sol_vault: accounts.stockpile_sol_vault,
            buyback_sol_vault: accounts.buyback_sol_vault,
            stockpile_extras: accounts.stockpile_extras,
            associated_token_program: accounts.associated_token_program,
            token_program: accounts.token_program,
            metadata_program: accounts.metadata_program,
            rent: accounts.rent,
            system_program: accounts.system_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(19 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.admin.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.crank.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.treasury.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.zinc_mint.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.zinc_metadata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.curve_admin_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.bonanza_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.stockpile_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.staking_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.staking_reward_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.stockpile_sol_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.buyback_sol_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.stockpile_extras.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.metadata_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = InitConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(20 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.crank.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.treasury.clone());
        account_infos.push(self.zinc_mint.clone());
        account_infos.push(self.zinc_metadata.clone());
        account_infos.push(self.curve_admin_token_account.clone());
        account_infos.push(self.bonanza_token_account.clone());
        account_infos.push(self.stockpile_token_account.clone());
        account_infos.push(self.staking_token_account.clone());
        account_infos.push(self.staking_reward_token_account.clone());
        account_infos.push(self.stockpile_sol_vault.clone());
        account_infos.push(self.buyback_sol_vault.clone());
        account_infos.push(self.stockpile_extras.clone());
        account_infos.push(self.associated_token_program.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.metadata_program.clone());
        account_infos.push(self.rent.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `InitConfig` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[]` crank
///   2. `[writable]` config
///   3. `[writable]` treasury
///   4. `[writable, signer]` zinc_mint
///   5. `[writable]` zinc_metadata
///   6. `[writable]` curve_admin_token_account
///   7. `[writable]` bonanza_token_account
///   8. `[writable]` stockpile_token_account
///   9. `[writable]` staking_token_account
///   10. `[writable]` staking_reward_token_account
///   11. `[writable]` stockpile_sol_vault
///   12. `[writable]` buyback_sol_vault
///   13. `[writable]` stockpile_extras
///   14. `[]` associated_token_program
///   15. `[]` token_program
///   16. `[]` metadata_program
///   17. `[]` rent
///   18. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitConfigCpiBuilder<'a, 'b> {
    instruction: Box<InitConfigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitConfigCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(InitConfigCpiBuilderInstruction {
            __program: program,
            admin: None,
            crank: None,
            config: None,
            treasury: None,
            zinc_mint: None,
            zinc_metadata: None,
            curve_admin_token_account: None,
            bonanza_token_account: None,
            stockpile_token_account: None,
            staking_token_account: None,
            staking_reward_token_account: None,
            stockpile_sol_vault: None,
            buyback_sol_vault: None,
            stockpile_extras: None,
            associated_token_program: None,
            token_program: None,
            metadata_program: None,
            rent: None,
            system_program: None,
            args: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn crank(&mut self, crank: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.crank = Some(crank);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn treasury(&mut self, treasury: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.treasury = Some(treasury);
        self
    }
    /// Newly created classic SPL mint for ZINC rewards.
    #[inline(always)]
    pub fn zinc_mint(&mut self, zinc_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.zinc_mint = Some(zinc_mint);
        self
    }
    #[inline(always)]
    pub fn zinc_metadata(
        &mut self,
        zinc_metadata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.zinc_metadata = Some(zinc_metadata);
        self
    }
    /// Treasury ATA that holds curve-admin ZINC inventory outside the Bonanza pot.
    #[inline(always)]
    pub fn curve_admin_token_account(
        &mut self,
        curve_admin_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.curve_admin_token_account = Some(curve_admin_token_account);
        self
    }
    /// Treasury-owned Bonanza vault that holds rolling Bonanza ZINC.
    #[inline(always)]
    pub fn bonanza_token_account(
        &mut self,
        bonanza_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.bonanza_token_account = Some(bonanza_token_account);
        self
    }
    /// Dedicated stockpile vault that holds stockpile ZINC separately from Bonanza accrual.
    #[inline(always)]
    pub fn stockpile_token_account(
        &mut self,
        stockpile_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stockpile_token_account = Some(stockpile_token_account);
        self
    }
    /// Dedicated staking vault that escrows staked ZINC balances.
    #[inline(always)]
    pub fn staking_token_account(
        &mut self,
        staking_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.staking_token_account = Some(staking_token_account);
        self
    }
    /// Dedicated reward vault that funds staker-yield claims.
    #[inline(always)]
    pub fn staking_reward_token_account(
        &mut self,
        staking_reward_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.staking_reward_token_account = Some(staking_reward_token_account);
        self
    }
    /// Program-owned lamport vault that accumulates stockpile SOL across cycles.
    #[inline(always)]
    pub fn stockpile_sol_vault(
        &mut self,
        stockpile_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stockpile_sol_vault = Some(stockpile_sol_vault);
        self
    }
    /// Program-owned lamport vault that accumulates buyback SOL across deploys.
    #[inline(always)]
    pub fn buyback_sol_vault(
        &mut self,
        buyback_sol_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.buyback_sol_vault = Some(buyback_sol_vault);
        self
    }
    /// Singleton account that tracks pending stockpile extras for the current cycle.
    #[inline(always)]
    pub fn stockpile_extras(
        &mut self,
        stockpile_extras: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stockpile_extras = Some(stockpile_extras);
        self
    }
    /// Associated Token Program used to create the treasury ATA.
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.associated_token_program = Some(associated_token_program);
        self
    }
    /// SPL Token Program that owns the ZINC mint and treasury vaults.
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    /// Metaplex Token Metadata Program used to create ZINC mint metadata.
    #[inline(always)]
    pub fn metadata_program(
        &mut self,
        metadata_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.metadata_program = Some(metadata_program);
        self
    }
    /// Rent sysvar forwarded to the Metaplex metadata CPI.
    #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.rent = Some(rent);
        self
    }
    /// System Program used to allocate protocol and metadata accounts.
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn args(&mut self, args: ZincMintMetadataArgs) -> &mut Self {
        self.instruction.args = Some(args);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = InitConfigInstructionArgs {
            args: self.instruction.args.clone().expect("args is not set"),
        };
        let instruction = InitConfigCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            crank: self.instruction.crank.expect("crank is not set"),

            config: self.instruction.config.expect("config is not set"),

            treasury: self.instruction.treasury.expect("treasury is not set"),

            zinc_mint: self.instruction.zinc_mint.expect("zinc_mint is not set"),

            zinc_metadata: self
                .instruction
                .zinc_metadata
                .expect("zinc_metadata is not set"),

            curve_admin_token_account: self
                .instruction
                .curve_admin_token_account
                .expect("curve_admin_token_account is not set"),

            bonanza_token_account: self
                .instruction
                .bonanza_token_account
                .expect("bonanza_token_account is not set"),

            stockpile_token_account: self
                .instruction
                .stockpile_token_account
                .expect("stockpile_token_account is not set"),

            staking_token_account: self
                .instruction
                .staking_token_account
                .expect("staking_token_account is not set"),

            staking_reward_token_account: self
                .instruction
                .staking_reward_token_account
                .expect("staking_reward_token_account is not set"),

            stockpile_sol_vault: self
                .instruction
                .stockpile_sol_vault
                .expect("stockpile_sol_vault is not set"),

            buyback_sol_vault: self
                .instruction
                .buyback_sol_vault
                .expect("buyback_sol_vault is not set"),

            stockpile_extras: self
                .instruction
                .stockpile_extras
                .expect("stockpile_extras is not set"),

            associated_token_program: self
                .instruction
                .associated_token_program
                .expect("associated_token_program is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            metadata_program: self
                .instruction
                .metadata_program
                .expect("metadata_program is not set"),

            rent: self.instruction.rent.expect("rent is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct InitConfigCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    crank: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    treasury: Option<&'b solana_account_info::AccountInfo<'a>>,
    zinc_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    zinc_metadata: Option<&'b solana_account_info::AccountInfo<'a>>,
    curve_admin_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    bonanza_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    staking_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    staking_reward_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile_sol_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    buyback_sol_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    stockpile_extras: Option<&'b solana_account_info::AccountInfo<'a>>,
    associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    metadata_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    rent: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    args: Option<ZincMintMetadataArgs>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
