//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const RELOAD_AUTO_MINER_SESSION_SOL_DISCRIMINATOR: [u8; 8] =
    [26, 170, 147, 196, 38, 148, 159, 234];

/// Accounts.
#[derive(Debug)]
pub struct ReloadAutoMinerSessionSol {
    /// Configured crank executing the reward reload.
    pub executor: solana_address::Address,
    /// Protocol config containing the active crank authority.
    pub config: solana_address::Address,

    pub authority: solana_address::Address,
    /// Auto-miner session PDA receiving the reloaded SOL budget.
    pub auto_miner_session: solana_address::Address,
    /// Player profile PDA holding credited round SOL rewards.
    pub player_profile: solana_address::Address,
}

impl ReloadAutoMinerSessionSol {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.executor, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.auto_miner_session,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.player_profile,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = ReloadAutoMinerSessionSolInstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct ReloadAutoMinerSessionSolInstructionData {
    discriminator: [u8; 8],
}

impl ReloadAutoMinerSessionSolInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [26, 170, 147, 196, 38, 148, 159, 234],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for ReloadAutoMinerSessionSolInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `ReloadAutoMinerSessionSol`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` executor
///   1. `[]` config
///   2. `[]` authority
///   3. `[writable]` auto_miner_session
///   4. `[writable]` player_profile
#[derive(Clone, Debug, Default)]
pub struct ReloadAutoMinerSessionSolBuilder {
    executor: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    authority: Option<solana_address::Address>,
    auto_miner_session: Option<solana_address::Address>,
    player_profile: Option<solana_address::Address>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ReloadAutoMinerSessionSolBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Configured crank executing the reward reload.
    #[inline(always)]
    pub fn executor(&mut self, executor: solana_address::Address) -> &mut Self {
        self.executor = Some(executor);
        self
    }
    /// Protocol config containing the active crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Auto-miner session PDA receiving the reloaded SOL budget.
    #[inline(always)]
    pub fn auto_miner_session(&mut self, auto_miner_session: solana_address::Address) -> &mut Self {
        self.auto_miner_session = Some(auto_miner_session);
        self
    }
    /// Player profile PDA holding credited round SOL rewards.
    #[inline(always)]
    pub fn player_profile(&mut self, player_profile: solana_address::Address) -> &mut Self {
        self.player_profile = Some(player_profile);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ReloadAutoMinerSessionSol {
            executor: self.executor.expect("executor is not set"),
            config: self.config.expect("config is not set"),
            authority: self.authority.expect("authority is not set"),
            auto_miner_session: self
                .auto_miner_session
                .expect("auto_miner_session is not set"),
            player_profile: self.player_profile.expect("player_profile is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `reload_auto_miner_session_sol` CPI accounts.
pub struct ReloadAutoMinerSessionSolCpiAccounts<'a, 'b> {
    /// Configured crank executing the reward reload.
    pub executor: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol config containing the active crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Auto-miner session PDA receiving the reloaded SOL budget.
    pub auto_miner_session: &'b solana_account_info::AccountInfo<'a>,
    /// Player profile PDA holding credited round SOL rewards.
    pub player_profile: &'b solana_account_info::AccountInfo<'a>,
}

/// `reload_auto_miner_session_sol` CPI instruction.
pub struct ReloadAutoMinerSessionSolCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Configured crank executing the reward reload.
    pub executor: &'b solana_account_info::AccountInfo<'a>,
    /// Protocol config containing the active crank authority.
    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Auto-miner session PDA receiving the reloaded SOL budget.
    pub auto_miner_session: &'b solana_account_info::AccountInfo<'a>,
    /// Player profile PDA holding credited round SOL rewards.
    pub player_profile: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> ReloadAutoMinerSessionSolCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ReloadAutoMinerSessionSolCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            executor: accounts.executor,
            config: accounts.config,
            authority: accounts.authority,
            auto_miner_session: accounts.auto_miner_session,
            player_profile: accounts.player_profile,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            *self.executor.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.auto_miner_session.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.player_profile.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = ReloadAutoMinerSessionSolInstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.executor.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.auto_miner_session.clone());
        account_infos.push(self.player_profile.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ReloadAutoMinerSessionSol` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` executor
///   1. `[]` config
///   2. `[]` authority
///   3. `[writable]` auto_miner_session
///   4. `[writable]` player_profile
#[derive(Clone, Debug)]
pub struct ReloadAutoMinerSessionSolCpiBuilder<'a, 'b> {
    instruction: Box<ReloadAutoMinerSessionSolCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ReloadAutoMinerSessionSolCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ReloadAutoMinerSessionSolCpiBuilderInstruction {
            __program: program,
            executor: None,
            config: None,
            authority: None,
            auto_miner_session: None,
            player_profile: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Configured crank executing the reward reload.
    #[inline(always)]
    pub fn executor(&mut self, executor: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.executor = Some(executor);
        self
    }
    /// Protocol config containing the active crank authority.
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Auto-miner session PDA receiving the reloaded SOL budget.
    #[inline(always)]
    pub fn auto_miner_session(
        &mut self,
        auto_miner_session: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.auto_miner_session = Some(auto_miner_session);
        self
    }
    /// Player profile PDA holding credited round SOL rewards.
    #[inline(always)]
    pub fn player_profile(
        &mut self,
        player_profile: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.player_profile = Some(player_profile);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = ReloadAutoMinerSessionSolCpi {
            __program: self.instruction.__program,

            executor: self.instruction.executor.expect("executor is not set"),

            config: self.instruction.config.expect("config is not set"),

            authority: self.instruction.authority.expect("authority is not set"),

            auto_miner_session: self
                .instruction
                .auto_miner_session
                .expect("auto_miner_session is not set"),

            player_profile: self
                .instruction
                .player_profile
                .expect("player_profile is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ReloadAutoMinerSessionSolCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    executor: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    auto_miner_session: Option<&'b solana_account_info::AccountInfo<'a>>,
    player_profile: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
