//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

pub const UPDATE_AUTO_MINER_SESSION_DISCRIMINATOR: [u8; 8] = [123, 139, 24, 168, 50, 205, 157, 81];

/// Accounts.
#[derive(Debug)]
pub struct UpdateAutoMinerSession {
    /// Wallet that owns and controls the session.
    pub authority: solana_address::Address,
    /// Player-owned auto-miner session PDA.
    pub auto_miner_session: solana_address::Address,
}

impl UpdateAutoMinerSession {
    pub fn instruction(
        &self,
        args: UpdateAutoMinerSessionInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: UpdateAutoMinerSessionInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.auto_miner_session,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = UpdateAutoMinerSessionInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateAutoMinerSessionInstructionData {
    discriminator: [u8; 8],
}

impl UpdateAutoMinerSessionInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [123, 139, 24, 168, 50, 205, 157, 81],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for UpdateAutoMinerSessionInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateAutoMinerSessionInstructionArgs {
    pub executor: Address,
    pub amount_per_round: u64,
    pub mask_bits_encryption_key: [u8; 32],
    pub mask_bits_nonce: u128,
    pub mask_bits_ciphertext: [u8; 32],
    pub mask_bits_key_version: u16,
    pub max_rounds: u64,
    pub expiry_slot: Option<u64>,
    pub paused: bool,
    pub crank_reimbursement_lamports: u64,
}

impl UpdateAutoMinerSessionInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `UpdateAutoMinerSession`.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[writable]` auto_miner_session
#[derive(Clone, Debug, Default)]
pub struct UpdateAutoMinerSessionBuilder {
    authority: Option<solana_address::Address>,
    auto_miner_session: Option<solana_address::Address>,
    executor: Option<Address>,
    amount_per_round: Option<u64>,
    mask_bits_encryption_key: Option<[u8; 32]>,
    mask_bits_nonce: Option<u128>,
    mask_bits_ciphertext: Option<[u8; 32]>,
    mask_bits_key_version: Option<u16>,
    max_rounds: Option<u64>,
    expiry_slot: Option<u64>,
    paused: Option<bool>,
    crank_reimbursement_lamports: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateAutoMinerSessionBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Wallet that owns and controls the session.
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Player-owned auto-miner session PDA.
    #[inline(always)]
    pub fn auto_miner_session(&mut self, auto_miner_session: solana_address::Address) -> &mut Self {
        self.auto_miner_session = Some(auto_miner_session);
        self
    }
    #[inline(always)]
    pub fn executor(&mut self, executor: Address) -> &mut Self {
        self.executor = Some(executor);
        self
    }
    #[inline(always)]
    pub fn amount_per_round(&mut self, amount_per_round: u64) -> &mut Self {
        self.amount_per_round = Some(amount_per_round);
        self
    }
    #[inline(always)]
    pub fn mask_bits_encryption_key(&mut self, mask_bits_encryption_key: [u8; 32]) -> &mut Self {
        self.mask_bits_encryption_key = Some(mask_bits_encryption_key);
        self
    }
    #[inline(always)]
    pub fn mask_bits_nonce(&mut self, mask_bits_nonce: u128) -> &mut Self {
        self.mask_bits_nonce = Some(mask_bits_nonce);
        self
    }
    #[inline(always)]
    pub fn mask_bits_ciphertext(&mut self, mask_bits_ciphertext: [u8; 32]) -> &mut Self {
        self.mask_bits_ciphertext = Some(mask_bits_ciphertext);
        self
    }
    #[inline(always)]
    pub fn mask_bits_key_version(&mut self, mask_bits_key_version: u16) -> &mut Self {
        self.mask_bits_key_version = Some(mask_bits_key_version);
        self
    }
    #[inline(always)]
    pub fn max_rounds(&mut self, max_rounds: u64) -> &mut Self {
        self.max_rounds = Some(max_rounds);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn expiry_slot(&mut self, expiry_slot: u64) -> &mut Self {
        self.expiry_slot = Some(expiry_slot);
        self
    }
    #[inline(always)]
    pub fn paused(&mut self, paused: bool) -> &mut Self {
        self.paused = Some(paused);
        self
    }
    #[inline(always)]
    pub fn crank_reimbursement_lamports(&mut self, crank_reimbursement_lamports: u64) -> &mut Self {
        self.crank_reimbursement_lamports = Some(crank_reimbursement_lamports);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = UpdateAutoMinerSession {
            authority: self.authority.expect("authority is not set"),
            auto_miner_session: self
                .auto_miner_session
                .expect("auto_miner_session is not set"),
        };
        let args = UpdateAutoMinerSessionInstructionArgs {
            executor: self.executor.clone().expect("executor is not set"),
            amount_per_round: self
                .amount_per_round
                .clone()
                .expect("amount_per_round is not set"),
            mask_bits_encryption_key: self
                .mask_bits_encryption_key
                .clone()
                .expect("mask_bits_encryption_key is not set"),
            mask_bits_nonce: self
                .mask_bits_nonce
                .clone()
                .expect("mask_bits_nonce is not set"),
            mask_bits_ciphertext: self
                .mask_bits_ciphertext
                .clone()
                .expect("mask_bits_ciphertext is not set"),
            mask_bits_key_version: self
                .mask_bits_key_version
                .clone()
                .expect("mask_bits_key_version is not set"),
            max_rounds: self.max_rounds.clone().expect("max_rounds is not set"),
            expiry_slot: self.expiry_slot.clone(),
            paused: self.paused.clone().expect("paused is not set"),
            crank_reimbursement_lamports: self
                .crank_reimbursement_lamports
                .clone()
                .expect("crank_reimbursement_lamports is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `update_auto_miner_session` CPI accounts.
pub struct UpdateAutoMinerSessionCpiAccounts<'a, 'b> {
    /// Wallet that owns and controls the session.
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Player-owned auto-miner session PDA.
    pub auto_miner_session: &'b solana_account_info::AccountInfo<'a>,
}

/// `update_auto_miner_session` CPI instruction.
pub struct UpdateAutoMinerSessionCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Wallet that owns and controls the session.
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Player-owned auto-miner session PDA.
    pub auto_miner_session: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: UpdateAutoMinerSessionInstructionArgs,
}

impl<'a, 'b> UpdateAutoMinerSessionCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: UpdateAutoMinerSessionCpiAccounts<'a, 'b>,
        args: UpdateAutoMinerSessionInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            auto_miner_session: accounts.auto_miner_session,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.auto_miner_session.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = UpdateAutoMinerSessionInstructionData::new()
            .try_to_vec()
            .unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.auto_miner_session.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `UpdateAutoMinerSession` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[writable]` auto_miner_session
#[derive(Clone, Debug)]
pub struct UpdateAutoMinerSessionCpiBuilder<'a, 'b> {
    instruction: Box<UpdateAutoMinerSessionCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateAutoMinerSessionCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(UpdateAutoMinerSessionCpiBuilderInstruction {
            __program: program,
            authority: None,
            auto_miner_session: None,
            executor: None,
            amount_per_round: None,
            mask_bits_encryption_key: None,
            mask_bits_nonce: None,
            mask_bits_ciphertext: None,
            mask_bits_key_version: None,
            max_rounds: None,
            expiry_slot: None,
            paused: None,
            crank_reimbursement_lamports: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Wallet that owns and controls the session.
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Player-owned auto-miner session PDA.
    #[inline(always)]
    pub fn auto_miner_session(
        &mut self,
        auto_miner_session: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.auto_miner_session = Some(auto_miner_session);
        self
    }
    #[inline(always)]
    pub fn executor(&mut self, executor: Address) -> &mut Self {
        self.instruction.executor = Some(executor);
        self
    }
    #[inline(always)]
    pub fn amount_per_round(&mut self, amount_per_round: u64) -> &mut Self {
        self.instruction.amount_per_round = Some(amount_per_round);
        self
    }
    #[inline(always)]
    pub fn mask_bits_encryption_key(&mut self, mask_bits_encryption_key: [u8; 32]) -> &mut Self {
        self.instruction.mask_bits_encryption_key = Some(mask_bits_encryption_key);
        self
    }
    #[inline(always)]
    pub fn mask_bits_nonce(&mut self, mask_bits_nonce: u128) -> &mut Self {
        self.instruction.mask_bits_nonce = Some(mask_bits_nonce);
        self
    }
    #[inline(always)]
    pub fn mask_bits_ciphertext(&mut self, mask_bits_ciphertext: [u8; 32]) -> &mut Self {
        self.instruction.mask_bits_ciphertext = Some(mask_bits_ciphertext);
        self
    }
    #[inline(always)]
    pub fn mask_bits_key_version(&mut self, mask_bits_key_version: u16) -> &mut Self {
        self.instruction.mask_bits_key_version = Some(mask_bits_key_version);
        self
    }
    #[inline(always)]
    pub fn max_rounds(&mut self, max_rounds: u64) -> &mut Self {
        self.instruction.max_rounds = Some(max_rounds);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn expiry_slot(&mut self, expiry_slot: u64) -> &mut Self {
        self.instruction.expiry_slot = Some(expiry_slot);
        self
    }
    #[inline(always)]
    pub fn paused(&mut self, paused: bool) -> &mut Self {
        self.instruction.paused = Some(paused);
        self
    }
    #[inline(always)]
    pub fn crank_reimbursement_lamports(&mut self, crank_reimbursement_lamports: u64) -> &mut Self {
        self.instruction.crank_reimbursement_lamports = Some(crank_reimbursement_lamports);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = UpdateAutoMinerSessionInstructionArgs {
            executor: self
                .instruction
                .executor
                .clone()
                .expect("executor is not set"),
            amount_per_round: self
                .instruction
                .amount_per_round
                .clone()
                .expect("amount_per_round is not set"),
            mask_bits_encryption_key: self
                .instruction
                .mask_bits_encryption_key
                .clone()
                .expect("mask_bits_encryption_key is not set"),
            mask_bits_nonce: self
                .instruction
                .mask_bits_nonce
                .clone()
                .expect("mask_bits_nonce is not set"),
            mask_bits_ciphertext: self
                .instruction
                .mask_bits_ciphertext
                .clone()
                .expect("mask_bits_ciphertext is not set"),
            mask_bits_key_version: self
                .instruction
                .mask_bits_key_version
                .clone()
                .expect("mask_bits_key_version is not set"),
            max_rounds: self
                .instruction
                .max_rounds
                .clone()
                .expect("max_rounds is not set"),
            expiry_slot: self.instruction.expiry_slot.clone(),
            paused: self.instruction.paused.clone().expect("paused is not set"),
            crank_reimbursement_lamports: self
                .instruction
                .crank_reimbursement_lamports
                .clone()
                .expect("crank_reimbursement_lamports is not set"),
        };
        let instruction = UpdateAutoMinerSessionCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            auto_miner_session: self
                .instruction
                .auto_miner_session
                .expect("auto_miner_session is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct UpdateAutoMinerSessionCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    auto_miner_session: Option<&'b solana_account_info::AccountInfo<'a>>,
    executor: Option<Address>,
    amount_per_round: Option<u64>,
    mask_bits_encryption_key: Option<[u8; 32]>,
    mask_bits_nonce: Option<u128>,
    mask_bits_ciphertext: Option<[u8; 32]>,
    mask_bits_key_version: Option<u16>,
    max_rounds: Option<u64>,
    expiry_slot: Option<u64>,
    paused: Option<bool>,
    crank_reimbursement_lamports: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
