//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::codama_rust::types::RoundRandomnessMode;
use crate::codama_rust::types::SettlementCapability;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_address::Address;

pub const UPDATE_CONFIG_DISCRIMINATOR: [u8; 8] = [29, 158, 252, 191, 10, 83, 219, 99];

/// Accounts.
#[derive(Debug)]
pub struct UpdateConfig {
    pub admin: solana_address::Address,

    pub config: solana_address::Address,
    /// Stores the currently enabled round, if any, and the next allocatable round ID.
    pub board: solana_address::Address,
}

impl UpdateConfig {
    pub fn instruction(
        &self,
        args: UpdateConfigInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: UpdateConfigInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.admin, true));
        accounts.push(solana_instruction::AccountMeta::new(self.config, false));
        accounts.push(solana_instruction::AccountMeta::new(self.board, false));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = UpdateConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateConfigInstructionData {
    discriminator: [u8; 8],
}

impl UpdateConfigInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [29, 158, 252, 191, 10, 83, 219, 99],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for UpdateConfigInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpdateConfigInstructionArgs {
    pub deploy_total_fee_bps: Option<u64>,
    pub round_duration_slots: Option<u64>,
    pub round_start_delay_slots: Option<u64>,
    pub stockpile_duration_slots: Option<u64>,
    pub stockpile_min_entry_bricks_x10k: Option<u64>,
    pub deploy_admin_fee_bps: Option<u64>,
    pub deploy_stockpile_fee_bps: Option<u64>,
    pub deploy_affiliate_fee_bps: Option<u64>,
    pub affiliate_withdrawals_enabled: Option<bool>,
    pub curve_admin_fee_bps: Option<u64>,
    pub winner_zinc_share_bps: Option<u64>,
    pub stockpile_zinc_share_bps: Option<u64>,
    pub no_winner_direct_winner_zinc_bonanza_share_bps: Option<u64>,
    pub no_winner_direct_winner_zinc_stockpile_share_bps: Option<u64>,
    pub min_deploy_lamports: Option<u64>,
    pub curve_max_round_mint: Option<u64>,
    pub curve_saturation_lamports: Option<u64>,
    pub curve_history_minted: Option<u64>,
    pub curve_target_support_lamports_per_zinc: Option<u64>,
    pub curve_max_supply: Option<u64>,
    pub crank: Option<Address>,
    pub deploy_affiliate_bonus_bricks_x10k: Option<u64>,
    pub wildcat_round_frequency: Option<u64>,
    pub wildcat_winner_zinc_share_ppm: Option<u64>,
    pub bonanza_hit_divisor: Option<u64>,
    pub round_claim_zinc_fee_bps: Option<u64>,
    pub stockpile_entry_min_zinc_fee: Option<u64>,
    pub stockpile_entry_pot_fee_bps: Option<u64>,
    pub stockpile_entry_step_bps: Option<u64>,
    pub staking_bricks_per_zinc_x10k: Option<u64>,
    pub staking_reward_vesting_slots: Option<u64>,
    pub arcium_reveal_cu_price_micro: Option<u64>,
    pub stockpile_refill_min_entry_bps: Option<u64>,
    pub round_randomness_mode: Option<RoundRandomnessMode>,
    pub settlement_capability: Option<SettlementCapability>,
    pub blockhash_reveal_delay_slots: Option<u64>,
    pub stockpile_bricks_per_zinc_x10k: Option<u64>,
    pub stockpile_winner_count: Option<u8>,
    pub stockpile_winner_share_bps: Option<[u64; 5]>,
    pub zk_mask_server_babyjub_pubkey_x: Option<[u8; 32]>,
    pub zk_mask_server_babyjub_pubkey_y: Option<[u8; 32]>,
    pub zk_mask_server_key_version: Option<u64>,
    pub zk_mask_circuit_version: Option<u64>,
    pub skip_arcium_init_cpi: Option<bool>,
}

impl UpdateConfigInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `UpdateConfig`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` config
///   2. `[writable]` board
#[derive(Clone, Debug, Default)]
pub struct UpdateConfigBuilder {
    admin: Option<solana_address::Address>,
    config: Option<solana_address::Address>,
    board: Option<solana_address::Address>,
    deploy_total_fee_bps: Option<u64>,
    round_duration_slots: Option<u64>,
    round_start_delay_slots: Option<u64>,
    stockpile_duration_slots: Option<u64>,
    stockpile_min_entry_bricks_x10k: Option<u64>,
    deploy_admin_fee_bps: Option<u64>,
    deploy_stockpile_fee_bps: Option<u64>,
    deploy_affiliate_fee_bps: Option<u64>,
    affiliate_withdrawals_enabled: Option<bool>,
    curve_admin_fee_bps: Option<u64>,
    winner_zinc_share_bps: Option<u64>,
    stockpile_zinc_share_bps: Option<u64>,
    no_winner_direct_winner_zinc_bonanza_share_bps: Option<u64>,
    no_winner_direct_winner_zinc_stockpile_share_bps: Option<u64>,
    min_deploy_lamports: Option<u64>,
    curve_max_round_mint: Option<u64>,
    curve_saturation_lamports: Option<u64>,
    curve_history_minted: Option<u64>,
    curve_target_support_lamports_per_zinc: Option<u64>,
    curve_max_supply: Option<u64>,
    crank: Option<Address>,
    deploy_affiliate_bonus_bricks_x10k: Option<u64>,
    wildcat_round_frequency: Option<u64>,
    wildcat_winner_zinc_share_ppm: Option<u64>,
    bonanza_hit_divisor: Option<u64>,
    round_claim_zinc_fee_bps: Option<u64>,
    stockpile_entry_min_zinc_fee: Option<u64>,
    stockpile_entry_pot_fee_bps: Option<u64>,
    stockpile_entry_step_bps: Option<u64>,
    staking_bricks_per_zinc_x10k: Option<u64>,
    staking_reward_vesting_slots: Option<u64>,
    arcium_reveal_cu_price_micro: Option<u64>,
    stockpile_refill_min_entry_bps: Option<u64>,
    round_randomness_mode: Option<RoundRandomnessMode>,
    settlement_capability: Option<SettlementCapability>,
    blockhash_reveal_delay_slots: Option<u64>,
    stockpile_bricks_per_zinc_x10k: Option<u64>,
    stockpile_winner_count: Option<u8>,
    stockpile_winner_share_bps: Option<[u64; 5]>,
    zk_mask_server_babyjub_pubkey_x: Option<[u8; 32]>,
    zk_mask_server_babyjub_pubkey_y: Option<[u8; 32]>,
    zk_mask_server_key_version: Option<u64>,
    zk_mask_circuit_version: Option<u64>,
    skip_arcium_init_cpi: Option<bool>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdateConfigBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_address::Address) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: solana_address::Address) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// Stores the currently enabled round, if any, and the next allocatable round ID.
    #[inline(always)]
    pub fn board(&mut self, board: solana_address::Address) -> &mut Self {
        self.board = Some(board);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_total_fee_bps(&mut self, deploy_total_fee_bps: u64) -> &mut Self {
        self.deploy_total_fee_bps = Some(deploy_total_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_duration_slots(&mut self, round_duration_slots: u64) -> &mut Self {
        self.round_duration_slots = Some(round_duration_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_start_delay_slots(&mut self, round_start_delay_slots: u64) -> &mut Self {
        self.round_start_delay_slots = Some(round_start_delay_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_duration_slots(&mut self, stockpile_duration_slots: u64) -> &mut Self {
        self.stockpile_duration_slots = Some(stockpile_duration_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_min_entry_bricks_x10k(
        &mut self,
        stockpile_min_entry_bricks_x10k: u64,
    ) -> &mut Self {
        self.stockpile_min_entry_bricks_x10k = Some(stockpile_min_entry_bricks_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_admin_fee_bps(&mut self, deploy_admin_fee_bps: u64) -> &mut Self {
        self.deploy_admin_fee_bps = Some(deploy_admin_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_stockpile_fee_bps(&mut self, deploy_stockpile_fee_bps: u64) -> &mut Self {
        self.deploy_stockpile_fee_bps = Some(deploy_stockpile_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_affiliate_fee_bps(&mut self, deploy_affiliate_fee_bps: u64) -> &mut Self {
        self.deploy_affiliate_fee_bps = Some(deploy_affiliate_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn affiliate_withdrawals_enabled(
        &mut self,
        affiliate_withdrawals_enabled: bool,
    ) -> &mut Self {
        self.affiliate_withdrawals_enabled = Some(affiliate_withdrawals_enabled);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_admin_fee_bps(&mut self, curve_admin_fee_bps: u64) -> &mut Self {
        self.curve_admin_fee_bps = Some(curve_admin_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn winner_zinc_share_bps(&mut self, winner_zinc_share_bps: u64) -> &mut Self {
        self.winner_zinc_share_bps = Some(winner_zinc_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_zinc_share_bps(&mut self, stockpile_zinc_share_bps: u64) -> &mut Self {
        self.stockpile_zinc_share_bps = Some(stockpile_zinc_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn no_winner_direct_winner_zinc_bonanza_share_bps(
        &mut self,
        no_winner_direct_winner_zinc_bonanza_share_bps: u64,
    ) -> &mut Self {
        self.no_winner_direct_winner_zinc_bonanza_share_bps =
            Some(no_winner_direct_winner_zinc_bonanza_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn no_winner_direct_winner_zinc_stockpile_share_bps(
        &mut self,
        no_winner_direct_winner_zinc_stockpile_share_bps: u64,
    ) -> &mut Self {
        self.no_winner_direct_winner_zinc_stockpile_share_bps =
            Some(no_winner_direct_winner_zinc_stockpile_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn min_deploy_lamports(&mut self, min_deploy_lamports: u64) -> &mut Self {
        self.min_deploy_lamports = Some(min_deploy_lamports);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_max_round_mint(&mut self, curve_max_round_mint: u64) -> &mut Self {
        self.curve_max_round_mint = Some(curve_max_round_mint);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_saturation_lamports(&mut self, curve_saturation_lamports: u64) -> &mut Self {
        self.curve_saturation_lamports = Some(curve_saturation_lamports);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_history_minted(&mut self, curve_history_minted: u64) -> &mut Self {
        self.curve_history_minted = Some(curve_history_minted);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_target_support_lamports_per_zinc(
        &mut self,
        curve_target_support_lamports_per_zinc: u64,
    ) -> &mut Self {
        self.curve_target_support_lamports_per_zinc = Some(curve_target_support_lamports_per_zinc);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_max_supply(&mut self, curve_max_supply: u64) -> &mut Self {
        self.curve_max_supply = Some(curve_max_supply);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn crank(&mut self, crank: Address) -> &mut Self {
        self.crank = Some(crank);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_affiliate_bonus_bricks_x10k(
        &mut self,
        deploy_affiliate_bonus_bricks_x10k: u64,
    ) -> &mut Self {
        self.deploy_affiliate_bonus_bricks_x10k = Some(deploy_affiliate_bonus_bricks_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn wildcat_round_frequency(&mut self, wildcat_round_frequency: u64) -> &mut Self {
        self.wildcat_round_frequency = Some(wildcat_round_frequency);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn wildcat_winner_zinc_share_ppm(
        &mut self,
        wildcat_winner_zinc_share_ppm: u64,
    ) -> &mut Self {
        self.wildcat_winner_zinc_share_ppm = Some(wildcat_winner_zinc_share_ppm);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn bonanza_hit_divisor(&mut self, bonanza_hit_divisor: u64) -> &mut Self {
        self.bonanza_hit_divisor = Some(bonanza_hit_divisor);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_claim_zinc_fee_bps(&mut self, round_claim_zinc_fee_bps: u64) -> &mut Self {
        self.round_claim_zinc_fee_bps = Some(round_claim_zinc_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_entry_min_zinc_fee(&mut self, stockpile_entry_min_zinc_fee: u64) -> &mut Self {
        self.stockpile_entry_min_zinc_fee = Some(stockpile_entry_min_zinc_fee);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_entry_pot_fee_bps(&mut self, stockpile_entry_pot_fee_bps: u64) -> &mut Self {
        self.stockpile_entry_pot_fee_bps = Some(stockpile_entry_pot_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_entry_step_bps(&mut self, stockpile_entry_step_bps: u64) -> &mut Self {
        self.stockpile_entry_step_bps = Some(stockpile_entry_step_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn staking_bricks_per_zinc_x10k(&mut self, staking_bricks_per_zinc_x10k: u64) -> &mut Self {
        self.staking_bricks_per_zinc_x10k = Some(staking_bricks_per_zinc_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn staking_reward_vesting_slots(&mut self, staking_reward_vesting_slots: u64) -> &mut Self {
        self.staking_reward_vesting_slots = Some(staking_reward_vesting_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn arcium_reveal_cu_price_micro(&mut self, arcium_reveal_cu_price_micro: u64) -> &mut Self {
        self.arcium_reveal_cu_price_micro = Some(arcium_reveal_cu_price_micro);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_refill_min_entry_bps(
        &mut self,
        stockpile_refill_min_entry_bps: u64,
    ) -> &mut Self {
        self.stockpile_refill_min_entry_bps = Some(stockpile_refill_min_entry_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_randomness_mode(
        &mut self,
        round_randomness_mode: RoundRandomnessMode,
    ) -> &mut Self {
        self.round_randomness_mode = Some(round_randomness_mode);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn settlement_capability(
        &mut self,
        settlement_capability: SettlementCapability,
    ) -> &mut Self {
        self.settlement_capability = Some(settlement_capability);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn blockhash_reveal_delay_slots(&mut self, blockhash_reveal_delay_slots: u64) -> &mut Self {
        self.blockhash_reveal_delay_slots = Some(blockhash_reveal_delay_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_bricks_per_zinc_x10k(
        &mut self,
        stockpile_bricks_per_zinc_x10k: u64,
    ) -> &mut Self {
        self.stockpile_bricks_per_zinc_x10k = Some(stockpile_bricks_per_zinc_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_winner_count(&mut self, stockpile_winner_count: u8) -> &mut Self {
        self.stockpile_winner_count = Some(stockpile_winner_count);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_winner_share_bps(
        &mut self,
        stockpile_winner_share_bps: [u64; 5],
    ) -> &mut Self {
        self.stockpile_winner_share_bps = Some(stockpile_winner_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_server_babyjub_pubkey_x(
        &mut self,
        zk_mask_server_babyjub_pubkey_x: [u8; 32],
    ) -> &mut Self {
        self.zk_mask_server_babyjub_pubkey_x = Some(zk_mask_server_babyjub_pubkey_x);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_server_babyjub_pubkey_y(
        &mut self,
        zk_mask_server_babyjub_pubkey_y: [u8; 32],
    ) -> &mut Self {
        self.zk_mask_server_babyjub_pubkey_y = Some(zk_mask_server_babyjub_pubkey_y);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_server_key_version(&mut self, zk_mask_server_key_version: u64) -> &mut Self {
        self.zk_mask_server_key_version = Some(zk_mask_server_key_version);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_circuit_version(&mut self, zk_mask_circuit_version: u64) -> &mut Self {
        self.zk_mask_circuit_version = Some(zk_mask_circuit_version);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn skip_arcium_init_cpi(&mut self, skip_arcium_init_cpi: bool) -> &mut Self {
        self.skip_arcium_init_cpi = Some(skip_arcium_init_cpi);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = UpdateConfig {
            admin: self.admin.expect("admin is not set"),
            config: self.config.expect("config is not set"),
            board: self.board.expect("board is not set"),
        };
        let args = UpdateConfigInstructionArgs {
            deploy_total_fee_bps: self.deploy_total_fee_bps.clone(),
            round_duration_slots: self.round_duration_slots.clone(),
            round_start_delay_slots: self.round_start_delay_slots.clone(),
            stockpile_duration_slots: self.stockpile_duration_slots.clone(),
            stockpile_min_entry_bricks_x10k: self.stockpile_min_entry_bricks_x10k.clone(),
            deploy_admin_fee_bps: self.deploy_admin_fee_bps.clone(),
            deploy_stockpile_fee_bps: self.deploy_stockpile_fee_bps.clone(),
            deploy_affiliate_fee_bps: self.deploy_affiliate_fee_bps.clone(),
            affiliate_withdrawals_enabled: self.affiliate_withdrawals_enabled.clone(),
            curve_admin_fee_bps: self.curve_admin_fee_bps.clone(),
            winner_zinc_share_bps: self.winner_zinc_share_bps.clone(),
            stockpile_zinc_share_bps: self.stockpile_zinc_share_bps.clone(),
            no_winner_direct_winner_zinc_bonanza_share_bps: self
                .no_winner_direct_winner_zinc_bonanza_share_bps
                .clone(),
            no_winner_direct_winner_zinc_stockpile_share_bps: self
                .no_winner_direct_winner_zinc_stockpile_share_bps
                .clone(),
            min_deploy_lamports: self.min_deploy_lamports.clone(),
            curve_max_round_mint: self.curve_max_round_mint.clone(),
            curve_saturation_lamports: self.curve_saturation_lamports.clone(),
            curve_history_minted: self.curve_history_minted.clone(),
            curve_target_support_lamports_per_zinc: self
                .curve_target_support_lamports_per_zinc
                .clone(),
            curve_max_supply: self.curve_max_supply.clone(),
            crank: self.crank.clone(),
            deploy_affiliate_bonus_bricks_x10k: self.deploy_affiliate_bonus_bricks_x10k.clone(),
            wildcat_round_frequency: self.wildcat_round_frequency.clone(),
            wildcat_winner_zinc_share_ppm: self.wildcat_winner_zinc_share_ppm.clone(),
            bonanza_hit_divisor: self.bonanza_hit_divisor.clone(),
            round_claim_zinc_fee_bps: self.round_claim_zinc_fee_bps.clone(),
            stockpile_entry_min_zinc_fee: self.stockpile_entry_min_zinc_fee.clone(),
            stockpile_entry_pot_fee_bps: self.stockpile_entry_pot_fee_bps.clone(),
            stockpile_entry_step_bps: self.stockpile_entry_step_bps.clone(),
            staking_bricks_per_zinc_x10k: self.staking_bricks_per_zinc_x10k.clone(),
            staking_reward_vesting_slots: self.staking_reward_vesting_slots.clone(),
            arcium_reveal_cu_price_micro: self.arcium_reveal_cu_price_micro.clone(),
            stockpile_refill_min_entry_bps: self.stockpile_refill_min_entry_bps.clone(),
            round_randomness_mode: self.round_randomness_mode.clone(),
            settlement_capability: self.settlement_capability.clone(),
            blockhash_reveal_delay_slots: self.blockhash_reveal_delay_slots.clone(),
            stockpile_bricks_per_zinc_x10k: self.stockpile_bricks_per_zinc_x10k.clone(),
            stockpile_winner_count: self.stockpile_winner_count.clone(),
            stockpile_winner_share_bps: self.stockpile_winner_share_bps.clone(),
            zk_mask_server_babyjub_pubkey_x: self.zk_mask_server_babyjub_pubkey_x.clone(),
            zk_mask_server_babyjub_pubkey_y: self.zk_mask_server_babyjub_pubkey_y.clone(),
            zk_mask_server_key_version: self.zk_mask_server_key_version.clone(),
            zk_mask_circuit_version: self.zk_mask_circuit_version.clone(),
            skip_arcium_init_cpi: self.skip_arcium_init_cpi.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `update_config` CPI accounts.
pub struct UpdateConfigCpiAccounts<'a, 'b> {
    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Stores the currently enabled round, if any, and the next allocatable round ID.
    pub board: &'b solana_account_info::AccountInfo<'a>,
}

/// `update_config` CPI instruction.
pub struct UpdateConfigCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub config: &'b solana_account_info::AccountInfo<'a>,
    /// Stores the currently enabled round, if any, and the next allocatable round ID.
    pub board: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: UpdateConfigInstructionArgs,
}

impl<'a, 'b> UpdateConfigCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: UpdateConfigCpiAccounts<'a, 'b>,
        args: UpdateConfigInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            config: accounts.config,
            board: accounts.board,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.admin.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.board.key, false));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = UpdateConfigInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::ZINC_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.board.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `UpdateConfig` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` config
///   2. `[writable]` board
#[derive(Clone, Debug)]
pub struct UpdateConfigCpiBuilder<'a, 'b> {
    instruction: Box<UpdateConfigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateConfigCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(UpdateConfigCpiBuilderInstruction {
            __program: program,
            admin: None,
            config: None,
            board: None,
            deploy_total_fee_bps: None,
            round_duration_slots: None,
            round_start_delay_slots: None,
            stockpile_duration_slots: None,
            stockpile_min_entry_bricks_x10k: None,
            deploy_admin_fee_bps: None,
            deploy_stockpile_fee_bps: None,
            deploy_affiliate_fee_bps: None,
            affiliate_withdrawals_enabled: None,
            curve_admin_fee_bps: None,
            winner_zinc_share_bps: None,
            stockpile_zinc_share_bps: None,
            no_winner_direct_winner_zinc_bonanza_share_bps: None,
            no_winner_direct_winner_zinc_stockpile_share_bps: None,
            min_deploy_lamports: None,
            curve_max_round_mint: None,
            curve_saturation_lamports: None,
            curve_history_minted: None,
            curve_target_support_lamports_per_zinc: None,
            curve_max_supply: None,
            crank: None,
            deploy_affiliate_bonus_bricks_x10k: None,
            wildcat_round_frequency: None,
            wildcat_winner_zinc_share_ppm: None,
            bonanza_hit_divisor: None,
            round_claim_zinc_fee_bps: None,
            stockpile_entry_min_zinc_fee: None,
            stockpile_entry_pot_fee_bps: None,
            stockpile_entry_step_bps: None,
            staking_bricks_per_zinc_x10k: None,
            staking_reward_vesting_slots: None,
            arcium_reveal_cu_price_micro: None,
            stockpile_refill_min_entry_bps: None,
            round_randomness_mode: None,
            settlement_capability: None,
            blockhash_reveal_delay_slots: None,
            stockpile_bricks_per_zinc_x10k: None,
            stockpile_winner_count: None,
            stockpile_winner_share_bps: None,
            zk_mask_server_babyjub_pubkey_x: None,
            zk_mask_server_babyjub_pubkey_y: None,
            zk_mask_server_key_version: None,
            zk_mask_circuit_version: None,
            skip_arcium_init_cpi: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    /// Stores the currently enabled round, if any, and the next allocatable round ID.
    #[inline(always)]
    pub fn board(&mut self, board: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.board = Some(board);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_total_fee_bps(&mut self, deploy_total_fee_bps: u64) -> &mut Self {
        self.instruction.deploy_total_fee_bps = Some(deploy_total_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_duration_slots(&mut self, round_duration_slots: u64) -> &mut Self {
        self.instruction.round_duration_slots = Some(round_duration_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_start_delay_slots(&mut self, round_start_delay_slots: u64) -> &mut Self {
        self.instruction.round_start_delay_slots = Some(round_start_delay_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_duration_slots(&mut self, stockpile_duration_slots: u64) -> &mut Self {
        self.instruction.stockpile_duration_slots = Some(stockpile_duration_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_min_entry_bricks_x10k(
        &mut self,
        stockpile_min_entry_bricks_x10k: u64,
    ) -> &mut Self {
        self.instruction.stockpile_min_entry_bricks_x10k = Some(stockpile_min_entry_bricks_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_admin_fee_bps(&mut self, deploy_admin_fee_bps: u64) -> &mut Self {
        self.instruction.deploy_admin_fee_bps = Some(deploy_admin_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_stockpile_fee_bps(&mut self, deploy_stockpile_fee_bps: u64) -> &mut Self {
        self.instruction.deploy_stockpile_fee_bps = Some(deploy_stockpile_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_affiliate_fee_bps(&mut self, deploy_affiliate_fee_bps: u64) -> &mut Self {
        self.instruction.deploy_affiliate_fee_bps = Some(deploy_affiliate_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn affiliate_withdrawals_enabled(
        &mut self,
        affiliate_withdrawals_enabled: bool,
    ) -> &mut Self {
        self.instruction.affiliate_withdrawals_enabled = Some(affiliate_withdrawals_enabled);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_admin_fee_bps(&mut self, curve_admin_fee_bps: u64) -> &mut Self {
        self.instruction.curve_admin_fee_bps = Some(curve_admin_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn winner_zinc_share_bps(&mut self, winner_zinc_share_bps: u64) -> &mut Self {
        self.instruction.winner_zinc_share_bps = Some(winner_zinc_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_zinc_share_bps(&mut self, stockpile_zinc_share_bps: u64) -> &mut Self {
        self.instruction.stockpile_zinc_share_bps = Some(stockpile_zinc_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn no_winner_direct_winner_zinc_bonanza_share_bps(
        &mut self,
        no_winner_direct_winner_zinc_bonanza_share_bps: u64,
    ) -> &mut Self {
        self.instruction
            .no_winner_direct_winner_zinc_bonanza_share_bps =
            Some(no_winner_direct_winner_zinc_bonanza_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn no_winner_direct_winner_zinc_stockpile_share_bps(
        &mut self,
        no_winner_direct_winner_zinc_stockpile_share_bps: u64,
    ) -> &mut Self {
        self.instruction
            .no_winner_direct_winner_zinc_stockpile_share_bps =
            Some(no_winner_direct_winner_zinc_stockpile_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn min_deploy_lamports(&mut self, min_deploy_lamports: u64) -> &mut Self {
        self.instruction.min_deploy_lamports = Some(min_deploy_lamports);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_max_round_mint(&mut self, curve_max_round_mint: u64) -> &mut Self {
        self.instruction.curve_max_round_mint = Some(curve_max_round_mint);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_saturation_lamports(&mut self, curve_saturation_lamports: u64) -> &mut Self {
        self.instruction.curve_saturation_lamports = Some(curve_saturation_lamports);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_history_minted(&mut self, curve_history_minted: u64) -> &mut Self {
        self.instruction.curve_history_minted = Some(curve_history_minted);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_target_support_lamports_per_zinc(
        &mut self,
        curve_target_support_lamports_per_zinc: u64,
    ) -> &mut Self {
        self.instruction.curve_target_support_lamports_per_zinc =
            Some(curve_target_support_lamports_per_zinc);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn curve_max_supply(&mut self, curve_max_supply: u64) -> &mut Self {
        self.instruction.curve_max_supply = Some(curve_max_supply);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn crank(&mut self, crank: Address) -> &mut Self {
        self.instruction.crank = Some(crank);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn deploy_affiliate_bonus_bricks_x10k(
        &mut self,
        deploy_affiliate_bonus_bricks_x10k: u64,
    ) -> &mut Self {
        self.instruction.deploy_affiliate_bonus_bricks_x10k =
            Some(deploy_affiliate_bonus_bricks_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn wildcat_round_frequency(&mut self, wildcat_round_frequency: u64) -> &mut Self {
        self.instruction.wildcat_round_frequency = Some(wildcat_round_frequency);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn wildcat_winner_zinc_share_ppm(
        &mut self,
        wildcat_winner_zinc_share_ppm: u64,
    ) -> &mut Self {
        self.instruction.wildcat_winner_zinc_share_ppm = Some(wildcat_winner_zinc_share_ppm);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn bonanza_hit_divisor(&mut self, bonanza_hit_divisor: u64) -> &mut Self {
        self.instruction.bonanza_hit_divisor = Some(bonanza_hit_divisor);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_claim_zinc_fee_bps(&mut self, round_claim_zinc_fee_bps: u64) -> &mut Self {
        self.instruction.round_claim_zinc_fee_bps = Some(round_claim_zinc_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_entry_min_zinc_fee(&mut self, stockpile_entry_min_zinc_fee: u64) -> &mut Self {
        self.instruction.stockpile_entry_min_zinc_fee = Some(stockpile_entry_min_zinc_fee);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_entry_pot_fee_bps(&mut self, stockpile_entry_pot_fee_bps: u64) -> &mut Self {
        self.instruction.stockpile_entry_pot_fee_bps = Some(stockpile_entry_pot_fee_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_entry_step_bps(&mut self, stockpile_entry_step_bps: u64) -> &mut Self {
        self.instruction.stockpile_entry_step_bps = Some(stockpile_entry_step_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn staking_bricks_per_zinc_x10k(&mut self, staking_bricks_per_zinc_x10k: u64) -> &mut Self {
        self.instruction.staking_bricks_per_zinc_x10k = Some(staking_bricks_per_zinc_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn staking_reward_vesting_slots(&mut self, staking_reward_vesting_slots: u64) -> &mut Self {
        self.instruction.staking_reward_vesting_slots = Some(staking_reward_vesting_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn arcium_reveal_cu_price_micro(&mut self, arcium_reveal_cu_price_micro: u64) -> &mut Self {
        self.instruction.arcium_reveal_cu_price_micro = Some(arcium_reveal_cu_price_micro);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_refill_min_entry_bps(
        &mut self,
        stockpile_refill_min_entry_bps: u64,
    ) -> &mut Self {
        self.instruction.stockpile_refill_min_entry_bps = Some(stockpile_refill_min_entry_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn round_randomness_mode(
        &mut self,
        round_randomness_mode: RoundRandomnessMode,
    ) -> &mut Self {
        self.instruction.round_randomness_mode = Some(round_randomness_mode);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn settlement_capability(
        &mut self,
        settlement_capability: SettlementCapability,
    ) -> &mut Self {
        self.instruction.settlement_capability = Some(settlement_capability);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn blockhash_reveal_delay_slots(&mut self, blockhash_reveal_delay_slots: u64) -> &mut Self {
        self.instruction.blockhash_reveal_delay_slots = Some(blockhash_reveal_delay_slots);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_bricks_per_zinc_x10k(
        &mut self,
        stockpile_bricks_per_zinc_x10k: u64,
    ) -> &mut Self {
        self.instruction.stockpile_bricks_per_zinc_x10k = Some(stockpile_bricks_per_zinc_x10k);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_winner_count(&mut self, stockpile_winner_count: u8) -> &mut Self {
        self.instruction.stockpile_winner_count = Some(stockpile_winner_count);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn stockpile_winner_share_bps(
        &mut self,
        stockpile_winner_share_bps: [u64; 5],
    ) -> &mut Self {
        self.instruction.stockpile_winner_share_bps = Some(stockpile_winner_share_bps);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_server_babyjub_pubkey_x(
        &mut self,
        zk_mask_server_babyjub_pubkey_x: [u8; 32],
    ) -> &mut Self {
        self.instruction.zk_mask_server_babyjub_pubkey_x = Some(zk_mask_server_babyjub_pubkey_x);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_server_babyjub_pubkey_y(
        &mut self,
        zk_mask_server_babyjub_pubkey_y: [u8; 32],
    ) -> &mut Self {
        self.instruction.zk_mask_server_babyjub_pubkey_y = Some(zk_mask_server_babyjub_pubkey_y);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_server_key_version(&mut self, zk_mask_server_key_version: u64) -> &mut Self {
        self.instruction.zk_mask_server_key_version = Some(zk_mask_server_key_version);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn zk_mask_circuit_version(&mut self, zk_mask_circuit_version: u64) -> &mut Self {
        self.instruction.zk_mask_circuit_version = Some(zk_mask_circuit_version);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn skip_arcium_init_cpi(&mut self, skip_arcium_init_cpi: bool) -> &mut Self {
        self.instruction.skip_arcium_init_cpi = Some(skip_arcium_init_cpi);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = UpdateConfigInstructionArgs {
            deploy_total_fee_bps: self.instruction.deploy_total_fee_bps.clone(),
            round_duration_slots: self.instruction.round_duration_slots.clone(),
            round_start_delay_slots: self.instruction.round_start_delay_slots.clone(),
            stockpile_duration_slots: self.instruction.stockpile_duration_slots.clone(),
            stockpile_min_entry_bricks_x10k: self
                .instruction
                .stockpile_min_entry_bricks_x10k
                .clone(),
            deploy_admin_fee_bps: self.instruction.deploy_admin_fee_bps.clone(),
            deploy_stockpile_fee_bps: self.instruction.deploy_stockpile_fee_bps.clone(),
            deploy_affiliate_fee_bps: self.instruction.deploy_affiliate_fee_bps.clone(),
            affiliate_withdrawals_enabled: self.instruction.affiliate_withdrawals_enabled.clone(),
            curve_admin_fee_bps: self.instruction.curve_admin_fee_bps.clone(),
            winner_zinc_share_bps: self.instruction.winner_zinc_share_bps.clone(),
            stockpile_zinc_share_bps: self.instruction.stockpile_zinc_share_bps.clone(),
            no_winner_direct_winner_zinc_bonanza_share_bps: self
                .instruction
                .no_winner_direct_winner_zinc_bonanza_share_bps
                .clone(),
            no_winner_direct_winner_zinc_stockpile_share_bps: self
                .instruction
                .no_winner_direct_winner_zinc_stockpile_share_bps
                .clone(),
            min_deploy_lamports: self.instruction.min_deploy_lamports.clone(),
            curve_max_round_mint: self.instruction.curve_max_round_mint.clone(),
            curve_saturation_lamports: self.instruction.curve_saturation_lamports.clone(),
            curve_history_minted: self.instruction.curve_history_minted.clone(),
            curve_target_support_lamports_per_zinc: self
                .instruction
                .curve_target_support_lamports_per_zinc
                .clone(),
            curve_max_supply: self.instruction.curve_max_supply.clone(),
            crank: self.instruction.crank.clone(),
            deploy_affiliate_bonus_bricks_x10k: self
                .instruction
                .deploy_affiliate_bonus_bricks_x10k
                .clone(),
            wildcat_round_frequency: self.instruction.wildcat_round_frequency.clone(),
            wildcat_winner_zinc_share_ppm: self.instruction.wildcat_winner_zinc_share_ppm.clone(),
            bonanza_hit_divisor: self.instruction.bonanza_hit_divisor.clone(),
            round_claim_zinc_fee_bps: self.instruction.round_claim_zinc_fee_bps.clone(),
            stockpile_entry_min_zinc_fee: self.instruction.stockpile_entry_min_zinc_fee.clone(),
            stockpile_entry_pot_fee_bps: self.instruction.stockpile_entry_pot_fee_bps.clone(),
            stockpile_entry_step_bps: self.instruction.stockpile_entry_step_bps.clone(),
            staking_bricks_per_zinc_x10k: self.instruction.staking_bricks_per_zinc_x10k.clone(),
            staking_reward_vesting_slots: self.instruction.staking_reward_vesting_slots.clone(),
            arcium_reveal_cu_price_micro: self.instruction.arcium_reveal_cu_price_micro.clone(),
            stockpile_refill_min_entry_bps: self.instruction.stockpile_refill_min_entry_bps.clone(),
            round_randomness_mode: self.instruction.round_randomness_mode.clone(),
            settlement_capability: self.instruction.settlement_capability.clone(),
            blockhash_reveal_delay_slots: self.instruction.blockhash_reveal_delay_slots.clone(),
            stockpile_bricks_per_zinc_x10k: self.instruction.stockpile_bricks_per_zinc_x10k.clone(),
            stockpile_winner_count: self.instruction.stockpile_winner_count.clone(),
            stockpile_winner_share_bps: self.instruction.stockpile_winner_share_bps.clone(),
            zk_mask_server_babyjub_pubkey_x: self
                .instruction
                .zk_mask_server_babyjub_pubkey_x
                .clone(),
            zk_mask_server_babyjub_pubkey_y: self
                .instruction
                .zk_mask_server_babyjub_pubkey_y
                .clone(),
            zk_mask_server_key_version: self.instruction.zk_mask_server_key_version.clone(),
            zk_mask_circuit_version: self.instruction.zk_mask_circuit_version.clone(),
            skip_arcium_init_cpi: self.instruction.skip_arcium_init_cpi.clone(),
        };
        let instruction = UpdateConfigCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            config: self.instruction.config.expect("config is not set"),

            board: self.instruction.board.expect("board is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct UpdateConfigCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    board: Option<&'b solana_account_info::AccountInfo<'a>>,
    deploy_total_fee_bps: Option<u64>,
    round_duration_slots: Option<u64>,
    round_start_delay_slots: Option<u64>,
    stockpile_duration_slots: Option<u64>,
    stockpile_min_entry_bricks_x10k: Option<u64>,
    deploy_admin_fee_bps: Option<u64>,
    deploy_stockpile_fee_bps: Option<u64>,
    deploy_affiliate_fee_bps: Option<u64>,
    affiliate_withdrawals_enabled: Option<bool>,
    curve_admin_fee_bps: Option<u64>,
    winner_zinc_share_bps: Option<u64>,
    stockpile_zinc_share_bps: Option<u64>,
    no_winner_direct_winner_zinc_bonanza_share_bps: Option<u64>,
    no_winner_direct_winner_zinc_stockpile_share_bps: Option<u64>,
    min_deploy_lamports: Option<u64>,
    curve_max_round_mint: Option<u64>,
    curve_saturation_lamports: Option<u64>,
    curve_history_minted: Option<u64>,
    curve_target_support_lamports_per_zinc: Option<u64>,
    curve_max_supply: Option<u64>,
    crank: Option<Address>,
    deploy_affiliate_bonus_bricks_x10k: Option<u64>,
    wildcat_round_frequency: Option<u64>,
    wildcat_winner_zinc_share_ppm: Option<u64>,
    bonanza_hit_divisor: Option<u64>,
    round_claim_zinc_fee_bps: Option<u64>,
    stockpile_entry_min_zinc_fee: Option<u64>,
    stockpile_entry_pot_fee_bps: Option<u64>,
    stockpile_entry_step_bps: Option<u64>,
    staking_bricks_per_zinc_x10k: Option<u64>,
    staking_reward_vesting_slots: Option<u64>,
    arcium_reveal_cu_price_micro: Option<u64>,
    stockpile_refill_min_entry_bps: Option<u64>,
    round_randomness_mode: Option<RoundRandomnessMode>,
    settlement_capability: Option<SettlementCapability>,
    blockhash_reveal_delay_slots: Option<u64>,
    stockpile_bricks_per_zinc_x10k: Option<u64>,
    stockpile_winner_count: Option<u8>,
    stockpile_winner_share_bps: Option<[u64; 5]>,
    zk_mask_server_babyjub_pubkey_x: Option<[u8; 32]>,
    zk_mask_server_babyjub_pubkey_y: Option<[u8; 32]>,
    zk_mask_server_key_version: Option<u64>,
    zk_mask_circuit_version: Option<u64>,
    skip_arcium_init_cpi: Option<bool>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
